### ISSUE TITLE
[BUG] "Follow back" text spilling out of button on mobile

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#105]
**Describe the Bug**
When viewing notifications on mobile, the text begins to spill from buttons when notifications are too long.

**To Reproduce**
1. Go to notifications page.
2. See "Follow back +"
3. See + spill

**Expected Behaviour**
The text should stay inside the button.

**Screenshots**
![IMG_7245](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a1dd7cce-7df6-4081-ba12-dc0173e64ff0)
![IMG_7244](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/abdc9157-a87e-4334-8334-84c56c3b7a4b)

**Device**
- Type: iPhone Xr
 - OS: iOS 16.6 
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#a8cc61a](https://github.com/Sheezy-Art/sheezy.art/commit/a8cc61a35beef3b20e71091f773fd2915eff0cce)
