### ISSUE TITLE
[BUG] Replies not appearing under comment notifications

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#107]
**Describe the Bug**
It's possible this might not be a bug since notifications are a wip but I thought I'd point it out anyways since I'm looking at old notifications.
When looking at the comments section of notifs, only parent comments appear, not replies. Replies appear under all notifications, however.

**To Reproduce**
1. View all notifs.
2. See replies in them.
3. View comment notifs.
4. See no replies.

**Expected Behaviour**
Replies included in comment notifications.

**Screenshots**
Comments notifs (this is all of them):
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/653b70c8-2efc-4f8c-b941-5820b008811f)
From all notifs:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/5df7300b-03f4-4ef7-9fd7-14da6483501a)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a8d88e6a-325f-48b0-8f42-0d134fac77be)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
There are some inconsistencies with how old notifications were formatted, so I think we need to expect history (legacy) notifications to be a little buggy. It's not a huge priority to get them fixed right away so this will have to go on the back burner for now.
