### ISSUE TITLE
[BUG] Footer links don't work when viewing account settings

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#109]
**Describe the Bug**
If you want to access one of the links in the site footer while viewing your account settings, you're instead brought to a 404 error.

**To Reproduce**
1. View account settings.
2. Click on one of the footer links, such as the about page.
3. See error.

**Expected Behaviour**
The links should be accessible from my account settings.

**Screenshots**
![firefox_lYbg055BnE](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/fdd2a9da-b074-4dca-ad5d-445cea783213)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed :)
