### ISSUE TITLE
[BUG] Brief 418 errors while browsing.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#111]
**Describe the Bug**
When browsing the site idly, there will occasionally be a 418 error while the page loads.
It's very inconsistent, but you can see it in https://github.com/Sheezy-Art/sheezy-hub/issues/110.

**To Reproduce**
1. Browse site idly.
2. See error while a page loads (usually when opening or leaving profiles, I've noticed)

**Expected Behaviour**
No errors while loading, even for a second.

**Screenshots**
![firefox_rjdIMMFyvP](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/6fa2fe8f-64ca-4a66-8402-2ee2a2469139)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
I can't replicate this. Would it be possible for you to open Developer Tools in Firefox (stay on the Console tab) and take a screen recording with the console in view? Would help me get a better idea of the errors you're getting.

**Comment by punkalope** [comment]
> I can't replicate this. Would it be possible for you to open Developer Tools in Firefox (stay on the Console tab) and take a screen recording with the console in view? Would help me get a better idea of the errors you're getting.

Tossed in the discord!

**Comment by boylett** [comment]
Can somebody confirm whether this is still happening please? :)

**Comment by Stormeko** [comment]
https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/f4befab1-c982-4443-92ef-af9eb13f2db4

https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/707d6f24-b3a4-4855-95b8-a68034e2d87f

**Comment by boylett** [comment]
Hm. Looks like this is a Firefox-specific issue - [#8324](https://github.com/remix-run/remix/issues/8324)
