### ISSUE TITLE
[BUG] Blocked user(s) will still appear in the Friends profile block

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#114]
**Describe the Bug**
When placing the 'Friends' block on a profile, any users who have been blocked from that profile will still be visible via the Friends block. This applies to all of the different display types (Oldest/Newest for both the Friends and Follower displays) in the settings menu for that block.

**To Reproduce**
1. Go to profile, click 'Edit Profile'
2. Click 'Add Block' and select the 'Friends' profile block
3. Choose any settings for Display Type
4. Click 'Save Changes', return to profile
5. See that any blocked user(s) will still be visible on the profile block

**Expected Behaviour**
Blocking user(s) will remove them from the Friends/Followers lists, visible through the Friends profile block.

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by VN-100** [comment]
Just checked, and unfortunately the bug still seems to be showing up on my end!

**Comment by boylett** [comment]
Fixed by [#d5ff8f0](https://github.com/Sheezy-Art/sheezy.art/commit/d5ff8f05e6483823439432777898d4b61344f771)
