### ISSUE TITLE
[BUG] Notication-center 'comments' give 418 error

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#115]
**Describe the Bug**
Whenever you try to click on comments in your notification list, you will be met by a '418 Something Went Wrong' error. This error does not appear on likes, followers or friend requests 

**To Reproduce**
1. Go to Notifications (default landing all notifications)
2. Click on Comments
3. See error '418 Something Went Wrong'

**Expected Behaviour**
To see the comments notifications

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153323699/3e44c1a0-a3ea-4aa5-abd7-078989c7b80a)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: FireFox
 - Version: Latest

**Comment by boylett** [comment]
A 418 error means something has gone wrong in your browser - unfortunately I can't see those in the server error log. Could you post a screen recording of this issue with your browser's Developer Console open please?

**Comment by punkalope** [comment]
Looks like it's still happening!
Took a video with the console open.
https://files.catbox.moe/fgxj3d.mp4
