### ISSUE TITLE
[BUG] Profiles of blocked user(s) are still fully visible to the user(s) who blocked them

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#124]
**Describe the Bug**
When blocking any users, their now-blocked profile is still visible to the user who blocked them in its entirety. Pages can still be visited and clicked on/scrolled through, rather than being fully hidden to the blocker as would otherwise be expected. 

**To Reproduce**
1. Go to Account Settings
2. Block any user through the Blocked Users section
3. Go to the blocked user's page
4. Blocked user's profile is still fully visible, tabs can be clicked and browsed through

**Expected Behaviour**
When blocking users, their profiles are completely hidden from the user blocking them.

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d5ff8f0](https://github.com/Sheezy-Art/sheezy.art/commit/d5ff8f05e6483823439432777898d4b61344f771)
