### ISSUE TITLE
[BUG] Custom content HTML incorrectly rendering as Prose

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#125]
**Describe the Bug**
Custom content HTML incorrectly renders as Prose, causing bugs. 
In this instance, I was trying to code a little flexbox full of stamps. They should have made a nice even row, but instead ended up extremely large.

**To Reproduce**
1. Code something in HTML.
2. See preview match intended code.
3. See as actual saved code is different.

**Expected Behaviour**
Code should work?

**Screenshots**
Without prose
![firefox_kBCkDXm894](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/39c860a8-47b7-488d-be4e-0f6a69e26782)
with
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/723c05b9-9d46-4860-9b51-f8129a9425b2)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#3179daf](https://github.com/Sheezy-Art/sheezy.art/commit/3179daf18c44524d0cad2ed2f730ed421dca5668)
