### ISSUE TITLE
[BUG] Profile blocks not working on new profiles

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#126]
**Describe the Bug**
Whenever you try to sort & save the order of your profile blocks, upon saving profile & going back to your profile, it will state your profile is empty

**To Reproduce**
1. Go to your profile
2. Click on edit profile
3. Add profile blocks & arrange them
4. Save changes
5. Back to profile
6. See 'Your profile is empty'

**Expected Behaviour**
Once profile blocks are added, you're supposed to at least view the profile blocks to edit them.

**Screenshots**
n/a, will send video to chat shortly

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: FireFox
 - Version: Latests

**Comment by boylett** [comment]
Fixed by [#7780468](https://github.com/Sheezy-Art/sheezy.art/commit/778046814024efa11546500bb3802c82bdcf18c8)
