### ISSUE TITLE
[BUG] Custom content not rendering headers properly.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#128]
**Describe the Bug**
When writing html in the custom content box, it doesn't seem to output headers as headers.

**To Reproduce**
1. Write CC.
2. Save and preview.
3. Notice the headers not working.

**Expected Behaviour**
Header tags should look different from normal text.

**Screenshots**
![firefox_3AvjCxbmT3](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/b78f7794-4585-4e81-985a-29887e7a321b)
![firefox_SqGMYg7pk5](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/8ad10973-6960-4424-b6b9-6ec1d6cab9e9)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
This is intended behaviour. If you'd like your content to render as typography, you can wrap it in the following:
`<div class="prose">` and `</div>`
