### ISSUE TITLE
[BUG] Unable to delete comment section block

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#129]
**Describe the Bug**
When removing a Comments block from my profile, instead of being deleted it gets sent to the storage area instead, and cannot be permanently deleted. Upon being moved to the storage area after an attempted deletion, the delete button is greyed out and can't be clicked. Moving it out of storage and clicking delete again repeats the process.

**To Reproduce**
1. Go to profile, click "Edit Profile"
2. Scroll to Comments block
3. Click the red delete button on the upper right of the Comments block
4. Comments block appears to be removed, but upon scrolling back up it appears in storage instead of being deleted

**Expected Behaviour**
Deleting the Comments block will completely remove it from my profile instead of putting it in storage.

**Screenshots**
![9](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/bc51012d-e3de-45f2-bdf9-0b5d57076b77)

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
This is intended behaviour for now. I plan on adding a confirmation dialog to the delete button but until then, comment blocks cannot be deleted.
