### ISSUE TITLE
[BUG] Persona block is broken

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#132]
**Describe the Bug**
No matter how I edit the paramaters or what it is set as my persona block on my profile wont show up.

**To Reproduce**
1. Go to Your Profile > Edit Profile
2. Click on 'Persona Block > Add persona block and set any parameters > Save
4. See error AKA No persona block

**Expected Behaviour**
The persona block being visible on my profile

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/2f9886f4-d71d-4660-bd31-fd40a6bbdeaf)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/9e629f0f-db4e-4a7d-b250-77fbe7efbfc1)

**Device**
- Type: PC, Desktop
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: idk

**Comment by boylett** [comment]
Fixed by [#7874e26](https://github.com/Sheezy-Art/sheezy.art/commit/7874e26b89745d20040e5cca9a0519dce3fc66ca)
