### ISSUE TITLE
[BUG] Custom cursor gif/moving no work

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#135]
**Describe the Bug**
Gif cursors dont move 

**To Reproduce**
1. Go to 'Profile
2. Click on Custom Cursor > upload a gif > save
3.  See error

**Expected Behaviour**
Gif moving cursor the gif should move
**Screenshots**

**Device**
- Type: PC Desktop
 - OS:  Windows 10
 - Browser: Google Chrome
 - Version: idk

**Comment by boylett** [comment]
This is a browser issue. Most browsers pause GIFs/WEBPs when the cursor is not moving to preserve memory. Can fix by creating a custom element that follows the cursor.
