### ISSUE TITLE
[BUG] Pinboard gets a bit wonky when placed at the bottom of the page

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#137]
**Describe the Bug**
When placed at the bottom of the page instead of the top the pinboard block doesnt size right

**To Reproduce**
1. Go to Your Page or persona
2. Click on Add Pinboard block > Add pins and size as you would like >Place at the bottom most section > save 
3. . See error

**Expected Behaviour**
For the block to size correctly

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/b2f7ffa0-d78d-4b6c-a40f-e116a15a62ab)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/475a34dd-ee59-4a78-b3f5-e8c6467b8d69)

**Device**
- Type: PC Desktop
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: idk

**Comment by DaxDoodles** [comment]
After more experimenting it still does it regardless of placement on the page, if you save the pinboard without editing or touching any of the pins it will shrink the board to the default hight but if you touch a pin then save the sizing is fine.

**Comment by boylett** [comment]
Cannot replicate this, may well be fixed. If anyone happens to experience this again please feel free to reopen the issue.
