### ISSUE TITLE
[BUG] Headers in HTML content don't work

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#148]
**Describe the Bug**
While headers wwork as expected in Markdown, they aren't functional in HTML.

**To Reproduce**

1. Create a custom content block with some headers (`<h1></h1>`, up to `<h6>`).
2. Set your profile box to have markdown content and add a header (`#`, `##`, up to `######`).
3. Notice the headers being ignored in the HTML block.

**Expected Behaviour**
Headers work in HTML just like they do in Markdown.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/e010cab7-fb25-4945-888c-9aace7c96395)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/51f359e3-f7e7-43e8-9061-6b2bf3808269)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
This is intended behaviour – please see [Custom Content](https://github.com/Sheezy-Art/sheezy-hub/wiki#custom-content) in the Wiki :)
