### ISSUE TITLE
[BUG] "More info regarding HTML on Sheezy" missing under profile info block

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#151]
**Describe the Bug**
When editing a custom content block, a message can be seen reading "[Click Here](https://github.com/Sheezy-Art/sheezy-hub/wiki#custom-content) for more info regarding HTML on Sheezy." This message is, however, absent when editing the profile information block, even if the current mode is set to HTML.

**To Reproduce**
1. Start editing your profile.
2. Add a profile information block and a custom content block.
3. Note the inconsistent appearance (or lack thereof) of the message.

**Expected Behaviour**
The message appears when editing HTML in the profile information block.

**Screenshots**

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/18d10033-006b-4e2d-8dc7-07ed49c3683b)

**Device**
 - Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#29723ac](https://github.com/Sheezy-Art/sheezy.art/commit/29723ac2d57284f25179710c8550613671bbad40)
