### ISSUE TITLE
[BUG] Artwork uploaded one after another not showing up in the browse tab...

### ISSUE THREAD

**Issue by Dorfde** [Sheezy-Art/sheezy-hub#152]
When uploading multiple artwork onto the site by uploading 2 or more artwork into the upload tab at once and once filling out the info and clicking upload it will in fact upload but it will only show up on the user profile and the sites home page. It doesn't show up to other users in browse tab but it shows up for the uploader in there but only showing that its still being uploaded. If clicked it will lead to a 404 page. Even when you remove an artwork from the upload page, choosing not to upload it will still appear in the browse tab for the uploader.

1. Go to the "Upload artwork" button
2. Click on plus icon, or drag and drop, and add artwork. Keep doing this till you reach the maximum amount of uploads allowed, minimum must be 2 to get this bug and or 3 to get the "removed art" bug to show up. I did 5.
3. Once you fill out all the necessary details upload 2 of the artwork to the site, if you have the third just chose to remove it and it should do the trick.
4. Go to browse and see the bug in action and to see that the artwork is actually uploaded check the users profile.

The browse page should have updated with the new artwork uploaded and it the removed artwork should not still be sitting in the browse tab as if its waiting to be uploaded.

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/87979250/8f0a7891-d315-44f3-964f-8679c5f0c3c4)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Google Chrome
 - Version: 120.0.6099.130

**Comment by boylett** [comment]
This was caused by the browse page cache, which should now be fixed
