### ISSUE TITLE
[BUG] sheezy.blog webpage error

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#153]
**Describe the Bug**
Roadmap webpage not working

**To Reproduce**
1. Go to ‘sheezy.blog’ on an iPad (?)

**Expected Behaviour**
See screencap below

**Screenshots**
![DE48821E-7648-42F0-BB6F-8230B95090CA](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/164848f4-d042-4f8d-acdf-c389b57590d6)

**Device**
- Type: tablet
 - OS: iOS 15.1
 - Browser: Safari and Firefox
 - Version: idk sorry ^^;
 - Note:it works fine on my phone

**Comment by boylett** [comment]
Fixed by [#156aaf1](https://github.com/Sheezy-Art/sheezy.blog/commit/156aaf1dea43b11d09681337b2039d65f70f5823)
