### ISSUE TITLE
[BUG] Conncting Ko-Fi/Discord accounts removes secret feature from profile options

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#156]
**Describe the Bug**
Before connecting my Discord and Ko-Fi accounts to my profile, I was able to see the secret feature but unable to upload a new file. Assuming that this was due to my accounts not being connected/my subscription not being picked up by the code, I connected both accounts, refreshed the page, and then found the secret feature was completely removed from the customization options. 

**To Reproduce**
1. Go to profile, hit Edit Profile
2. Navigate to the left sidebar for profile customization
3. Click the Page options, see that secret feature is visible but cannot upload a file
4. Navigate to Account Settings, then to Integrations
5. Integrate account with Discord or Ko-Fi
6. Return to profile, hit Edit Profile
7. Navigate to the left customization sidebar
8. Click the Page options, see that secret feature is now completely missing

**Expected Behaviour**
Opening the profile customization will show the secret feature on the Page options after subscription accounts are integrated.

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#fd58b02](https://github.com/Sheezy-Art/sheezy.art/commit/fd58b0250d20e6d88f10b2a0b9faa58b0c0907ef)
