### ISSUE TITLE
[BUG] Internal Server Error on trying to link Patreon

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#157]
**Describe the Bug**
Upon clicking the Patreon button on the side bar of Account Settings, I get an Internal Server Error. (I suspect this might be because I was a patreon sub back in 2021?)

**To Reproduce**
1. Go to Account Settings page
2. Click on Patreon
3. See Internal Server Error

**Expected Behaviour**
A form to enter my patreon email in order to link it. 

**Device**
Windows 10, Firefox 121.0 (64-bit)

**Comment by pyrrhuria** [comment]
I'm also experiencing this, with Windows 11, Firefox 121.0 (64-bit).
