### ISSUE TITLE
[BUG] Website is very nonfunctional on Pale Moon browser

### ISSUE THREAD

**Issue by nocapss** [Sheezy-Art/sheezy-hub#158]
**Describe the Bug**
Using the Pale Moon browser, a large amount of the website is nonfunctional or has graphical issues . Trending artwork on the front page displays as stretched, profile gallery blocks and comments do not load, and clicking on the profile photo in the header only works on certain pages.
This is a very obscure bug that i'm sure only like 2 people will ever encounter but its nice to at least report it so

**To Reproduce**
1. Use Pale Moon browser (https://www.palemoon.org/)
2. Open sheezy and log in
3. Open a profile with gallery/comment blocks or try clicking on the profile photo in the header on the frontpage

**Expected Behaviour**
I mean .. I was expecting the whole website to work completely fine on my browser

**Screenshots**
Video of my issue(s) : http://nocaps.leprd.space/video/clip0001.avi (forgive the low quality)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/22258110/280df4bb-57a3-4719-9496-2fb3a22e80d9)
^Note the weird looking stretched trending art
**Device**
- Type: Desktop PC
 - OS: Windows (7 SP1)
 - Browser: Pale Moon
 - Version: 32.5.2

**Comment by nocapss** [comment]
Adding on to this : profile galleries themselves just do not load
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/22258110/74a02dd0-7d70-4ed7-9ab7-8cb855a0b82e)

**Comment by nocapss** [comment]
Adding on to this - i now cannot log in on it anymore
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/22258110/b3198671-af0a-4bcc-8891-7b4092701c7c)

**Comment by xnyoom** [comment]
Unfortunately, we don't have the resources to support Pale Moon.

Pale Moon is based off a pretty old version of Firefox and doesn't support many of the modern web technologies Sheezy requires.

If you must use Sheezy on an older Windows computer, consider checking out the [Mypal browser](https://www.mypal-browser.org/) instead. It should be a lot better supported, though I haven't checked. That said, if there are problems on Mypal only, we will not fix them.
