### ISSUE TITLE
[BUG] Submitting Art while uploading art deletes current draft

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#160]
**Describe the Bug**
Submitting a draft while uploading art causes the current draft to disappear

**To Reproduce**
1. Go to Upload art
2. Upload an image
3. Add stuff to image
4. Add some images to upload (4 or 5 big ones?)
5. click publish on the current draft
6. watch as your current draft disappears and is replaced by all the other images you just uploaded

**Expected Behaviour**
The image i submitted should... submit

**Screenshots**

**Device**
Windows 10, Firefox 121.0 (64-bit)

**Comment by boylett** [comment]
Should be fixed by [#3a93ba9](https://github.com/Sheezy-Art/sheezy.art/commit/3a93ba960d362e383f5841a2b61bbb669d67a72b). Let me know if this still happens and I'll reopen the issue.
