### ISSUE TITLE
[BUG] Line Breaks entered in any text block is not interpreted as a line break

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#164]
**Describe the Bug**
Whenever I press Enter to enter a line break in a text box, when I preview or submit the text box, it does not include any line break. It is still visible if you go to edit it, but it is not displayed in the final text.

**To Reproduce**
1. Enter text with a line break (enter) in the image description or journal entry text box
2. Preview or submit your text
3. No line breaks

**Expected Behaviour**
A line break should be in the final text

**Screenshots**

**Device**
Windows 10, Firefox 121.0 64 bit

**Comment by boylett** [comment]
This is the default behaviour of markdown and is part of the [CommonMark spec](https://spec.commonmark.org/0.30/#characters-and-lines). To add a full line break, you need to add an extra line break after the end of your line.
