### ISSUE TITLE
[BUG] Clicking Browse displays my 5 newest images as Drafts, despite not being drafts

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#165]
**Describe the Bug**
 Clicking Browse displays my 5 newest images as Drafts, despite not being drafts

**To Reproduce**
1. Upload a bunch of images to the site
2. Submit them so they are not drafts
3. Click on Browse
4. Your images are still displayed as drafts, it is unknown if others can see them yet (is this just the server not updating?)

**Expected Behaviour**
My 5 newest works are not drafts and should not be faded out as if they are

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/015edcce-605d-41a8-ae74-772f47147605)

**Device**
Windows 10 Firefox 121.0 (64-bit)

**Comment by boylett** [comment]
Is this still the case? I'm seeing these artworks as fully published in your gallery

**Comment by CytricAcid** [comment]
> Is this still the case? I'm seeing these artworks as fully published in your gallery

it seems to be just server catchup. my apologies!

**Comment by boylett** [comment]
Ah phew! All good :D
