### ISSUE TITLE
[BUG] Personas unable to view profile art

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#166]
**Describe the Bug**
When viewing a profile as a Persona, you are unable to view the artwork for a user's profile.

**To Reproduce**
- Go to any user's profile
- Select a Persona
- View either the profile's gallery block or the gallery page
- "Couldn't find any artwork matching your filters"

**Expected Behaviour**
Personas should be able to view artworks the same way a regular user would.

**Screenshots**
Regular User:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/aaef45a4-ad73-4e9a-b1ef-9bbadc9ac13a)
Persona User:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/8d0c2253-3c48-4d6e-827f-26a4652c7406)

**Notes**
Also worth mentioning is that the persona page lacks any setting for _viewing_ artworks behind filters unlike regular users.

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: Firefox 121.0

**Comment by DaxDoodles** [comment]
To add onto this personas dont seem to be able to view galleries of other users/profiles when main profile’s can. Viewing the galleries of other personas when active as a persona DOES seem to be working tho

**Comment by boylett** [comment]
This should be fixed as of [#e2051fc](https://github.com/Sheezy-Art/sheezy.art/commit/e2051fced3684f5dfbc996098e99f57b39bd9e10). Please let me know if you're still experiencing this issue!
