### ISSUE TITLE
[BUG] Viewing main gallery from Persona shows Persona-submitted art

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#167]
**Describe the Bug**
When I view my account's gallery from my main persona, it only displays art submitted from the main account. If I switch to my persona, it displays art from my persona's gallery instead.

**To Reproduce**
1. Have a main account and at least 1 persona
2. Submit art on both personas
3. Switch to your side persona
4. Look at your main account's gallery
5. It's your persona's gallery instead

**Expected Behaviour**
It should be displaying my main accounts gallery instead of my persona's gallery. This only happens when i'm using the side persona

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/7f272359-d79a-446f-9ed9-6d225a792b50)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/126a8559-7a6c-4aa6-ab31-a1ed0a095fd2)
(sorry for the censoring)

**Device**
Windows 10, Firefox 121.0 (64-bit)

**Comment by CytricAcid** [comment]
apparently other people can't see my gallery at all and my art does not appear in the search??? but only for some people????

**Comment by boylett** [comment]
This should be fixed as of [#e2051fc](https://github.com/Sheezy-Art/sheezy.art/commit/e2051fced3684f5dfbc996098e99f57b39bd9e10). Please let me know if you're still experiencing this issue!
