### ISSUE TITLE
[BUG/OVERSIGHT] Ability to stack likes with Personas

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#168]
**Describe the Bug**
A user is able to use personas to 'stack' likes on an image by rotating through personas, liking a single image with each persona.

**To Reproduce**
- Go to any image
- Like the image
- Switch to any persona
- Like the image
- Switch to another persona
- Like the image
- Switch to another persona
- Like the image
- Easy, instant 4 likes on a single image

**Expected Behaviour**
Not sure, but this feels like more of an oversight with personas having a separate like database (or whatever you call it) than the original user.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/172e64cd-4a18-4782-8641-387ac2004f5e)

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: Firefox 121.0

**Comment by boylett** [comment]
Definitely an oversight, thank you for pointing this out! Will fix.
