### ISSUE TITLE
[BUG] YouTube embeds not working

### ISSUE THREAD

**Issue by boylett** [Sheezy-Art/sheezy-hub#17]
**Describe the bug**
YouTube embed blocks are not working

**To Reproduce**
1. Go to 'My Profile'
2. Click on 'Edit Profile'
3. Add an embed block
4. Paste in a YouTube video link
5. Click 'Save Changes'
6. Open Profile

**Expected behavior**
The video should display in an embed block on the user's profile

**Screenshots**
While Editing:
<img width="1180" alt="Screenshot 2023-12-05 at 14 28 29" src="https://github.com/Sheezy-Art/sheezy-hub/assets/145017198/ba911b5b-1efd-4dd9-a3a5-b5c7dc6bd573">

While Viewing:
<img width="1179" alt="Screenshot 2023-12-05 at 14 28 38" src="https://github.com/Sheezy-Art/sheezy-hub/assets/145017198/4daa2371-aae5-4fdc-a11e-dd7e1e1e22f9">

**Comment by punkalope** [comment]
Seems like some people are still having issues with this, along with Ko-fi!

**Comment by pink2004luigi** [comment]
Here's a video and screenshot providing more information as this issue has been happening to me. It appears blank in preview as well.

https://github.com/Sheezy-Art/sheezy-hub/assets/64936334/bba40952-ab58-41c3-8d7a-468833694cfa
_Same issue happens with embed block_

When reopening Edit Profile:
https://github.com/Sheezy-Art/sheezy-hub/assets/64936334/796012ba-627d-4541-b32b-9e44dc9457ea

**Comment by boylett** [comment]
Fixed by [#5064e1c](https://github.com/Sheezy-Art/sheezy.art/commit/5064e1cd5eb82a7d8711521bf88056315f9cb0cf)
