### ISSUE TITLE
[BUG] Clicking on image gives 418 page

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#171]
**Describe the Bug**
Clicking on an images thumbnail takes me to the 418 page.

**To Reproduce**
1.Clicking on any thumbnail while using iPad (I do not have this error on phone or desktop 

**Expected Behaviour**
the image doesn’t load and I am taken to https://sheezy.dev/mutant/gallery/stupid-guy

**Screenshots**
![3D7223C0-125C-4AD7-BB0E-F94FDAE197BD](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/51a811b8-b07e-4e35-b25f-77e61eaa8e47)

**Device**
- Type: iPad (I am not having this issue oh my phone or desktop)
 - OS: iOS 15.1
 - Browser: Safari, Firefox 
 - Version: unsure. But they are up to date

**Comment by waningw** [comment]
418 is a browser error, Ry has requested we leave a screen recording with devtools (f12) open for these ones! You can leave a video in the staff private beta, that's what the rest of us have done hehe :-)
