### ISSUE TITLE
[BUG] Comments do not show up on Persona Notifications page but still notify you

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#173]
**Describe the Bug**
When someone commented on one of my art pieces that I posted on one of my persona's pages, I get a notification that they liked and commented on the image on my main account, but the persona's notification page only displays the like. It still "notices" the comment as indicated by a 2 next to the notification icon, but i am unable to see the notification in the notification center under All Notifications and there is no filter for just comment notifications. 
It does not count this as "seeing" the notification, so even when I visit my notification center on my side page, it still displays a 1 next to my notifications indicating an unread notification.

**To Reproduce**
1. Have a side persona
2. Get a comment on a side persona's art
3. Go to notifications
4. There is no comment notification

**Expected Behaviour**
I should be able to see the comment notification, the comments filter on my notifications, and the notifications notifier should update to know that i have seen the comment notification.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/fcfa1345-6e1e-4c5f-9c26-eadd75adca6f)

**Device**
Windows 10, Firefox 121.0 (64-bit)

**Comment by lumiscosity** [comment]
had this happen, but the notification was completely rerouted to my main account

**Comment by boylett** [comment]
Fixed by [#02b61b4](https://github.com/Sheezy-Art/sheezy.art/commit/02b61b41c08211b0176d51733a8c6388644603e5)
