### ISSUE TITLE
[BUG] Cannot change username capitalization

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#174]
**Describe the Bug**
I wanted to change my username from majestea to MAJESTEA (because I like to scream), but when changing it it doesn't save.

**To Reproduce**
1. Go to account settings.
2. Change username capitalization.
3. Save and refresh.
4. See that my change hasn't saved.

**Expected Behaviour**
My username edit should save.

**Screenshots**
Email (and thus the save button) cropped out for privacy.
![firefox_3ntYVh8J5l](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/47c573d3-ae52-4667-bd2f-2c68fc3403d4)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by waningw** [comment]
Confirming this is also an issue on my end, tried to change capitalization of first letter, 4 weeks wait penalty.

**Comment by punkalope** [comment]
ALAS. It still seems to not be working, at least for me.

**Comment by boylett** [comment]
I haven't published the changes yet :')

**Comment by punkalope** [comment]
> I haven't published the changes yet :')

FORGOVE ME I HAVENT SLEPT YET 💔 Sorry Ry LOL I'll let you know if its broken for real next time.

**Comment by boylett** [comment]
IT'S SO OK!! I need to make it clear when changes are synced to the server. Will work on an auto poster for the Discord
