### ISSUE TITLE
[BUG] Mods/Admins do not see the "report" button on the submission dropdown

### ISSUE THREAD

**Issue by Ellteo** [Sheezy-Art/sheezy-hub#175]
**Describe the Bug**
When viewing an image, moderators do not seem to see the "report" button on the image [...] dropdown.

**To Reproduce**
1. Go to any image as moderator/admin
2. Click on '...' under the image
3. See missing option

**Expected Behaviour**
Mods + Admins should be able to see the option to report an image!

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/57603841/730e2030-a752-49c0-abed-9104df14be87)

(used my own art for an example just so we wouldn't be putting anyone on blast LOL)

**Device**
- Type: Laptop
 - OS: Windows
 - Browser: Opera GX
 - Version: Latest

**Comment by boylett** [comment]
Is this in the mod queue or on artwork pages?

**Comment by Ellteo** [comment]
> Is this in the mod queue or on artwork pages?

Artwork pages in general! I've gone to a few to check (my own and others) and do not encounter a report button - I believe Avery had the same issue. It's not present in either case (in queue or on individual pages)!
