### ISSUE TITLE
[BUG] Like buttons on journals are broken

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#183]
**Describe the Bug**
Trying to like blog posts causes the like count to drop to 1 after a pause, which continues until you refresh the page. You also can't see the likes of other people on blog posts.

**To Reproduce**
1. Go to any blog post.
2. Try to like / unlike it.

**Expected Behaviour**
Likes behave normally on blog posts.

**Screenshots**
![firefox_4LUEuq9TRT](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/6903187c-5e02-41b2-98f1-8ce75e79b988)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Should be fixed by [#77c7b23](https://github.com/Sheezy-Art/sheezy.art/commit/77c7b23b5526b500b0cb7b313a28286cf1f29e28). Please let me know if not.
