### ISSUE TITLE
[BUG]  Changing the username in the settings page URL to the username of an existing account takes you to a 404 page

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#187]
**Describe the Bug**
Trying to change the username in the settings page URL to the username of an existing account takes you to /login/undefined/settings. This only happens with activated accounts; other accounts or nonexistent accounts bring you back to your settings page.

**To Reproduce**
1. Go to the account settings.
2. Change the username in the URL to the username of any active user (other than yourself).
3. Go to the link.

**Expected Behaviour**
All URL change attempts should bring you back to your settings page.

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#5064e1c](https://github.com/Sheezy-Art/sheezy.art/commit/5064e1cd5eb82a7d8711521bf88056315f9cb0cf)
