### ISSUE TITLE
[BUG] 2FA account recovery codes overlap on mobile

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#188]
**Describe the Bug**
2FA account recovery codes overlap on mobile.

**To Reproduce**
1. Go to the account settings > Password and authentication
2. Set up 2FA, if you haven't already
3. Notice the overlapping recovery codes; especially the dots

**Expected Behaviour**
The codes do not overlap.

**Screenshots**
i am NOT adding screenshots for that

**Device**
 - Type: Mobile
 - OS: Android
 - Browser: Firefox
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#0fd6984](https://github.com/Sheezy-Art/sheezy.art/commit/0fd6984f55f5f8f2acfdada9a006adbfa5448b84)
