### ISSUE TITLE
[BUG] "Pin link" box deselects pin, visually carries over previously selected data

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#189]
**Describe the Bug**
Clicking on the "Pin link" box deselects the currently selected pin, making the only way to insert a link to the pin copying it in directly. Additionally, the box will appear to carry over the text from the previously selected pin if another pin is clicked (deselecting the pin cancels this).

**To Reproduce**
1. Add a pinboard block and start editing it.
2. Add some pins to the board.
3. Try adding links to the pins.

**Expected Behaviour**
Clicking on the "Pin link" box doean't deselect the pin, and the previously selected data isn't visually carried over from the previous pin.

**Screenshots**
![firefox_FD6dcqGqhn](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0726eb30-35e3-4f95-b3a4-ffb0f1f0a7dd)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#1125bb0](https://github.com/Sheezy-Art/sheezy.art/commit/1125bb0b412cb800c0f7bc50af6030c251d9bdfd)
