### ISSUE TITLE
[BUG] Pins with links become distorted

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#190]
**Describe the Bug**
When a link is added to a pin, the pin will become offset and incorrectly scaled.

**To Reproduce**
1. Create a pinboard block and start editing it.
2. Add some pins.
3. Add a link to a pin.
4. Save your profile and check the pins' position and size relative to how they appear in the editor.

**Expected Behaviour**
Pins with links don't become distorted.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/3fe95600-cde3-4e12-9021-59dc87265865)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/ba724354-7072-46a6-b43e-b75824102574)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#1125bb0](https://github.com/Sheezy-Art/sheezy.art/commit/1125bb0b412cb800c0f7bc50af6030c251d9bdfd)
