### ISSUE TITLE
[BUG] Links in signatures aren't functional

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#195]
**Describe the Bug**
While links can be placed and render correctly (with an underline) in signatures, they cannot be clicked on.

**To Reproduce**
1. Put a link in your signature.
2. Post a comment.
3. Try to click on the link.

**Expected Behaviour**
The link is clickable.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/5fdf2858-7cf3-4484-82bc-9bad11c988c6)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by Sheishori** [comment]
Links added to signatures before a certain commit are working, when edited break.

**Comment by boylett** [comment]
Fixed by [#0fd6984](https://github.com/Sheezy-Art/sheezy.art/commit/0fd6984f55f5f8f2acfdada9a006adbfa5448b84).

Note that you will need to edit and save your comment signature for this fix to take effect.
