### ISSUE TITLE
[BUG] Comment Notification Mislabeled 

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#199]
**Describe the Bug**
Responded to my own comment on a friends profile page, the notification labels it as a comment on my page, but not as if its my page (sorry about the weird wording)

**To Reproduce**
1. Go to someone else's profile
2. Comment
3. Reply to yourself

**Expected Behaviour**
Receive notification shown below
I have also included the comments that the notification links to.

**Screenshots**
![Screen Shot 2024-01-02 at 5 43 17 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/716b91b4-fb24-467c-a650-177aaaa2f372)
![Screen Shot 2024-01-02 at 5 43 43 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/8d017b51-366c-4c73-b7a7-5afc5f598090)

**Note**
This does NOT happen when I comment on my own page/respond to my own messages

**Device**
- Type: Laptop
 - OS: iOS
 - Browser: Firefox
 - Version: unsure

**Comment by betalambda** [comment]
I noticed this bug too when someone replied to a comment made on someone else's profile.

_OS: Windows_

**Comment by boylett** [comment]
Should now be fixed by [#772bc6a](https://github.com/Sheezy-Art/sheezy.art/commit/772bc6a1d2b6f31ebba45d76a2cc5729bf26b8fe). Let me know if not!
