### ISSUE TITLE
[BUG] Clicking Journal Titles in Mod Queue goes to 404 page

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#200]
**Describe the Bug**
Cannot click on a journal in the mod page 

**To Reproduce**
1. Go to 'Sheezy Admin" then 'Mod Queue'
2. Click on 'Journals'
3. Click on a Journal Title

**Expected Behaviour**
404 Page

**Screenshots**
![Screen Shot 2024-01-02 at 7 32 37 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/765419b8-3694-4d31-aa4c-c7bbb12aed5b)

**Note**
The "See More" and "See Less" Buttons work just fine and i can expand the preview to see the whole journal. Just the redirection does not work

**Device**
- Type: Laptop
 - OS: iOS 10.15
 - Browser: Firefox
 - Version: Unsure

**Comment by boylett** [comment]
Fixed by [#e6453a1](https://github.com/Sheezy-Art/sheezy.art/commit/e6453a1f8c51e5ff0b366751ce1f316aea542721)
