### ISSUE TITLE
[BUG] Persona art shows up in feed when subscribed to the main user behind the persona.

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#203]
**Describe the Bug**
When you subscribe to a user, their persona's art shows up in your feed despite you not subscribing to the persona.

**To Reproduce**
- Subscribe to a user with a persona
- Look at your feed
- Persona art

**Expected Behaviour**
Subscribing to a user should fill your feed with *just* the user's art. If you wanted to see persona art, you would subscribe to the persona individually.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/e7482945-4490-44f1-b9e2-94323884a930)

**Device**
(site-side issue)

**Comment by betalambda** [comment]
Update: This bug appears to not have been fixed

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/218dcc04-a874-41d4-8a2b-ff301cdc6b4e)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/8f1466e0-b1be-4df3-8253-92ab0afcb91e)

**Comment by boylett** [comment]
Can you reload the homepage and see if it's still there?
