### ISSUE TITLE
[BUG] Adding "Journals"block to profile gives Internal Server Error whenever you try to edit profile

### ISSUE THREAD

**Issue by nocapss** [Sheezy-Art/sheezy-hub#204]
**Describe the Bug**
If you add a Journals block to your profile, you get a 418 error and then an Internal Server Error whenever you try to edit your profile further.

**To Reproduce**
1. Open the edit profile thing
2. Add a "Journals" block
3. Should get a 418 error
4. Every time you press the edit profile button after that, you get internal server error

**Expected Behaviour**
Journals block is expected to show my journals and also let me edit my profile in general
**Screenshots**
http://nocaps.leprd.space/video/clip0003.avi 
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/22258110/1582e8ec-2589-4b5f-8add-94ef835fd5ca)

**Device**
- Type: Desktop PC
 - OS: Windows 7
 - Browser: Google Chrome
 - Version: 109

**Comment by nocapss** [comment]
should note just for specifics , i only had 1 journal on my profile when it did this . not sure if that actually means anything or has anything to do with the issue but just think i should specify

**Comment by boylett** [comment]
Fixed by [#c801a5e](https://github.com/Sheezy-Art/sheezy.art/commit/c801a5ed2c42b888239b30635eeb97299a6e112f)
