### ISSUE TITLE
[BUG] Mod Queue Item link in Notifications leads to 404

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#205]
**Describe the Bug**
Tried to view what comment Teo liked from the mod queue and it gave me a 404 page

**To Reproduce**
1. Go to 'Notifications'
2. Click on 'Mod queue Item' link

**Expected Behaviour**
404 Page

**Screenshots**
![Screen Shot 2024-01-02 at 11 41 08 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/5cf64265-845a-45d8-870b-91335f784ad6)
![Screen Shot 2024-01-02 at 11 41 15 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/371ac63d-a606-4d72-bcee-e7a3f32ee6a8)

**Device**
- Type: Laptop
 - OS: iOS 10.15.5
 - Browser: Firefox
 - Version: 121.0

**Comment by crocojaws** [comment]
I realise now this is from clicking on "mod queue item" and not "comment", because the piece is probably not in the queue anymore

**Comment by boylett** [comment]
Fixed by [#020eae9](https://github.com/Sheezy-Art/sheezy.art/commit/020eae9b921f713756e7d3de7f2a9e121730f91d)
