### ISSUE TITLE
[BUG] Internal Server Error cropping up on specific userpage

### ISSUE THREAD

**Issue by Ellteo** [Sheezy-Art/sheezy-hub#206]
**Describe the Bug**
Kryxyo's user profile cannot be accessed by *anyone* attempting to view their profile. In addition, changing settings to make their profile publicly visible hasn't changed this issue.

**To Reproduce**
1. Go to https://sheezy.dev/kryxyo (User profile is ADULT rated)
2. See error

**Expected Behaviour**
Seeing the profile?

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/57603841/8050f1c1-1b56-4d6f-b913-140b5aecf7fd)
not sure if the console is...helpful at all but! There u go

**Device**
- Type: Laptop
 - OS: Windows
 - Browser: Opera GX
 - Version: Latest

**Comment by boylett** [comment]
Fixed by [#c801a5e](https://github.com/Sheezy-Art/sheezy.art/commit/c801a5ed2c42b888239b30635eeb97299a6e112f)
