### ISSUE TITLE
[BUG] New notifications in the "Followers" tab lack the "Follow" button

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#207]
**Describe the Bug**
All notifications in the "Followers" tab sent after the current beta test started lack the side button that older notifications have.

**To Reproduce**
1. Go to your notifications.
2. Go to the "Followers" tab.

**Expected Behaviour**
All notifications in the tab have the side button.

**Screenshots**
![Screenshot_20240103_092037_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/9612ada2-d2c1-40d2-98f3-71aa7b43a1cd)

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Firefox Nightly
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#a8cc61a](https://github.com/Sheezy-Art/sheezy.art/commit/a8cc61a35beef3b20e71091f773fd2915eff0cce)
