### ISSUE TITLE
[BUG] Following someone from the notifications makes a notification saying you followed yourself

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#208]
**Describe the Bug**
Following someone from the notifications gives you a notification saying you followed yourself.

**To Reproduce**
1. Go to the notifications.
2. Unfollow and refollow someone through the side buttons.

**Expected Behaviour**
No message appears.

**Screenshots**

https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/4f27f49b-6ed0-4572-8b54-942f1dad2faa

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#a8cc61a](https://github.com/Sheezy-Art/sheezy.art/commit/a8cc61a35beef3b20e71091f773fd2915eff0cce)
