### ISSUE TITLE
[BUG] Unfollowing and refollowing someone through notifications causes the button to appear as "Follow"

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#209]
**Describe the Bug**
Unfollowing and refollowing someone who is following you through notifications causes the button to appear as "Follow" instead of "Follow Back", even though the other person is still following you. This is fixed on a refresh.

**To Reproduce**
1. Go to your notifications.
2. In the "Followers" tab, unfollow and refollow someone.
3. Notice the button text.

**Expected Behaviour**
The button text is properly set to "Follow Back".

**Screenshots**
see the video for issue #208, this issue can be seen there too; my phone is refusing to resend the video

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Firefox Nightly
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#a8cc61a](https://github.com/Sheezy-Art/sheezy.art/commit/a8cc61a35beef3b20e71091f773fd2915eff0cce)
