### ISSUE TITLE
[BUG] Reply and options buttons on comments can be moved off screen under certain conditions

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#211]
**Describe the Bug**
Reply and options buttons on comments can be moved off screen under certain conditions, such as an extremely long pronoun field or a long string.

**To Reproduce**
1. Set your pronouns to something extremely long.
2. Try posting a comment.
3. Notice the missing buttons.

**Expected Behaviour**
The buttons are anchored to the side of the box.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/56338dc8-770f-4654-9319-10bdad8f1d64)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#bd607d7](https://github.com/Sheezy-Art/sheezy.art/commit/bd607d72562379ba0289a7d98c93a88ec96b8719)
