### ISSUE TITLE
[BUG] Most text inputs lack a maximum length

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#212]
**Describe the Bug**
Many things around the site lack a maximum length, leading to ultimately harmless silliness at best and site breaking bugs at worst:
- pronouns
- tag names
- artwork/journal names (too long a post name causes the URL to be too long to process a request for)
- journal feeling tab
- descriptions
- signatures
- comments
- and probably any other text field i may have missed.
(searching will stop you from filing too long a request though!)

**To Reproduce**
1. Go to any text field
2. Paste an extremely long string
3. Chaos

**Expected Behaviour**
Text inputs are appropriately capped.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/10a43985-f6b3-45ad-a890-b718c81cecb7)
![firefox_OAbSWLjGyG](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/32870698-718b-4574-8c3e-5b4efde9f795)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by tewm** [comment]
G.G.I.S. '24
Issue intact as of Jan 8th
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/9f0ed135-f22a-4553-bdc7-a2491f6c5f6a)
 (and this isn't even the whole thing lmao)

**Comment by boylett** [comment]
Fixed by [#312ae30](https://github.com/Sheezy-Art/sheezy.art/commit/312ae30a479cecdc431943aedc1fc85ae4b50f45)
