### ISSUE TITLE
[BUG] Hiding or deleting other users' comments on your work doesn't work

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#215]
**Describe the Bug**
Hiding or deleting other users' comments on your work doesn't work, despite the options being there.

**To Reproduce**
1. Make a journal or artwork.
2. Have someone else comment on it.
3. Try to hide or delete the comment.

**Expected Behaviour**
The comment gets deleted or hidden.

**Screenshots**
![firefox_Ys7dzFoQqt](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/9b070812-0e01-4740-adf1-35c700f1a1d6)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d2ef7e3](https://github.com/Sheezy-Art/sheezy.art/commit/d2ef7e37db7c801b5d2e940b2e3f1e1b9c0b98ed)

**Comment by boylett** [comment]
Fixed by [#4497750](https://github.com/Sheezy-Art/sheezy.art/commit/4497750d8db713f3664e3e2f66cb7c1655c6e225)
