### ISSUE TITLE
[BUG] Hidden comment indicator only updates on a refresh

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#216]
**Describe the Bug**
When hiding a comment, the indicator icon on it denoting that it's hidden only appears once the page is refreshed, not directly after toggling the option.

**To Reproduce**
1. Go to a comment.
2. Try to hide/unhide it.
3. Refresh the page.

**Expected Behaviour**
The indicator updates when you click the option.

**Screenshots**
![firefox_tKFn4LOwmX](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/9a3f3216-fc79-4884-845a-5087c246839f)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d2ef7e3](https://github.com/Sheezy-Art/sheezy.art/commit/d2ef7e37db7c801b5d2e940b2e3f1e1b9c0b98ed)
