### ISSUE TITLE
[BUG] "Hide" button on comments says "Hide" even when the comment is already hidden

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#217]
**Describe the Bug**
The "Hide" button on comments says "Hide" even when the comment is already hidden

**To Reproduce**
1. Go to a comment.
2. Hide it.
3. Refresh the page (optional, updates the visual indicator, see #216).
4. Check the name of the "Hide" button.

**Expected Behaviour**
The button says "Show", or some other variation that conveys the changed action.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/f11d4bde-28db-4289-88f1-1e9f8c3a5ae5)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d2ef7e3](https://github.com/Sheezy-Art/sheezy.art/commit/d2ef7e37db7c801b5d2e940b2e3f1e1b9c0b98ed)
