### ISSUE TITLE
[BUG] Following anyone as a persona follows the persona of the other person with the same name

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#218]
**Describe the Bug**
Following anyone as a persona follows the persona of the other person with the same name as yours instead, even if one doesn't exist. Following a persona will do the same for the owner of that persona.

**To Reproduce**
1. Switch to a persona.
2. Try to follow someone.
3. Check your followers.

**Expected Behaviour**
You can follow other users normally as a persona.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/f475b67d-6e7e-4d54-8a77-70c97b66cbe6)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Could you check this again and let me know if this is still happening for you?

**Comment by lumiscosity** [comment]
nope! works fine now
