### ISSUE TITLE
[BUG] Preview pane on comments does not reset after sending a comment

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#220]
**Describe the Bug**
Preview pane on comments does not reset after sending a comment.

**To Reproduce**
1. Go to a comment field.
2. Type and send a comment.
3. Check the preview pane.

**Expected Behaviour**
The preview pane resets after sending a comment.

**Screenshots**
![firefox_xKH4VpKSte](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/e79363d8-18de-4350-aa2d-18e0da974188)

**Device**
 - Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by tewm** [comment]
The Great GitHub Issues Sweep of '24
Issue still intact as of Jan 8th
https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/67b85132-4640-4c16-bcd9-2acc6c1c81b4

**Comment by boylett** [comment]
Fixed by [#05ff32d](https://github.com/Sheezy-Art/sheezy.art/commit/05ff32da38fe16cb31ac48d8b7407d0cf1058a16)
