### ISSUE TITLE
[BUG] "Archive this page" link doesn't send the correct data

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#221]
**Describe the Bug**
The "Archive this page" link only sends the path after the domain name, with the actual domain name missing.

**To Reproduce**
1. Go to any page.
2. Click on the "Archive this page" button.

**Expected Behaviour**
The "Archive this page" link includes the full URL.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/178f528f-1e99-40c8-bba8-fe4b6ed142fd)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/04a15e47-9b5f-4580-ab65-8b37b9813fd6)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by tewm** [comment]
The Great GitHub Issues Sweep of '24
Issue intact
https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/9909e9c4-5f67-44c4-b2c9-0de0aea75559

**Comment by boylett** [comment]
Archive link should not be active on the Private BETA as none of the permalinks are final. Have removed the link for now, thanks for the heads-up.

The archive link will return when we migrate to the production Sheezy.Art domain name.
