### ISSUE TITLE
[OVERSIGHT] Shuffle includes own art and liked art

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#222]
**Describe the Bug**
A minor oversight where your own art and liked art are included in the Shuffle pool.

**To Reproduce**
For own art:

- Include either a completely original tag you came up for one of your pieces or a rare tag only you and maybe 2 other people have used in the search bar
- Shuffle
- Your art should show up

For liked art:
- Put "liked" in the search bar
- Shuffle
- Liked pieces show up

**Expected Behaviour**
Shuffle shouldn't return your own pieces. Liked pieces on the other hand may either be a possible feature to make out of this oversight or may be intentional all along.

**Notes**
This is a very minor oversight that is unlikely to show up when using the shuffle feature unless half the database consists of your own art or you have 75% of the site consistently liked.

**Device**
(on-site oversight)

**Comment by boylett** [comment]
Fixed by [#3598c69](https://github.com/Sheezy-Art/sheezy.art/commit/3598c6901e216d58f6e319fb3f765b6261f704dd)
