### ISSUE TITLE
[BUG] Internal server error on select users profiles

### ISSUE THREAD

**Issue by voxaz** [Sheezy-Art/sheezy-hub#223]
**Describe the Bug**
Going to some profiles causes an internal server error. Journals, arts, and going to their gallery work fine, just the actual profile.

**To Reproduce**
Click on a users username or try to link to their profile:

https://sheezy.dev/brodent
https://sheezy.dev/sang
https://sheezy.dev/wildegeist
https://sheezy.dev/bunnybambi
https://sheezy.dev/cattytheartcat
https://sheezy.dev/lunabracer
https://sheezy.dev/moon
https://sheezy.dev/marukuro
https://sheezy.dev/notaprofessional
https://sheezy.dev/blackbox
https://sheezy.dev/tom
https://sheezy.dev/imorb
https://sheezy.dev/cookie-waffle
https://sheezy.dev/ibby

theres probably more, these are just the ones from my mutuals list

**Expected Behaviour**
Profile should load

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/a3f88179-ebcd-4513-9a86-dc1e68215bd2)

**Device**
- Type: Laptop
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by boylett** [comment]
Have pinpointed this as an issue with excluded tags
