### ISSUE TITLE
[BUG] Removing a comment while on its page throws a 418 error instead of a 404 error

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#224]
**Describe the Bug**
Removing a comment while on its page throws a 418 error instead of a 404 error. Refreshing the page correctly shows the 404 error.

**To Reproduce**
1. Go to a comment's page.
2. Remove it.

**Expected Behaviour**
The 404 error is shown.

**Screenshots**
![firefox_L5KazSSAS7](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/b0a3abca-b67a-4fb0-8456-d1095622b13c)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d7994e2](https://github.com/Sheezy-Art/sheezy.art/commit/d7994e20a40ad45eff926827b1ff216a8b48248c)
