### ISSUE TITLE
[BUG] "See more" on Similar Artworks section doesn't show more similar art

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#226]
**Describe the Bug**
The "See More" button for Similar artworks is nonfunctional, instead showing you the same results as if you clicked on the Browse button in the search bar.

**To Reproduce**
- Go to any artwork with tags
- Scroll down to "Similar Artworks"
- Click on See More
- The results are the same as Browse

**Expected Behaviour**
The button should show me more artwork with the same tags as the one I just viewed.

**Screenshots**
Same results, different thing in address bar
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/20e5ff99-b432-494b-97be-5d655c9aaedc)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/88e0fbda-3d24-45bb-905d-495d150d32c8)

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: Firefox 121.0

**Comment by boylett** [comment]
Fixed by [#b3beb6d](https://github.com/Sheezy-Art/sheezy.art/commit/b3beb6d321c8ffda7b6f2d9e0153bf3d16de9cb9)
