### ISSUE TITLE
[BUG] Setting Gallery block as any combination of row number and 1 column makes it 1 column by 6 rows

### ISSUE THREAD

**Issue by voxaz** [Sheezy-Art/sheezy-hub#227]
**Describe the Bug**
Initially tried 1x1, came out as 1 column by 6 rows, column number seems to work normally, but any number of rows combined with one column makes it 6 rows

**To Reproduce**
1. Add gallery block
2. Set column to 1 and row to any number
3. Save changed
4. Profit (have your artwork displayed in a column of 6 at low quality)

**Expected Behaviour**
1 row by 1 column should give 1 artwork - was trying to use it like featured artwork but to always feature the most recent upload

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/65f60a53-26ee-489f-abe1-d91d9f4a0513)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/898173a2-fd37-4fda-9c2a-2b0339c76570)

**Device**
- Type: Laptop
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by Sheishori** [comment]
Fixed by [#8735a00](https://github.com/Sheezy-Art/sheezy.art/commit/8735a0075de8cf9a42c6ef6cb4c1048ec598880b) (I think)
