### ISSUE TITLE
[BUG] Images don't appear in comment signatures

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#228]
**Describe the Bug**
Images don't appear in comment signatures.

**To Reproduce**
1. Add an image to your signature.
2. Notice that it's missing.

**Expected Behaviour**
Images appear in comment signatures.

**Screenshots**
![firefox_evR5tLP0SZ](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/b494e7c9-38d7-4b45-a35f-d5591fa59aca)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
For the time being, this is intentional. We are still deciding whether we want to allow images in comment signatures.
