### ISSUE TITLE
[BUG] "Share" button on blog posts doesn't work

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#229]
**Describe the Bug**
The "Share" button on blog posts doesn't work.

**To Reproduce**
1. Go to a blog post.
2. Scroll down to the bottom and click on the three dots
3. Try clicking on "Share"

**Expected Behaviour**
The "Share" button on blog posts works.

**Screenshots**
![firefox_xfEmPcm6uZ](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/113f11a1-f57e-48bc-8dd7-3069b8352264)

**Device**
 - Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#3ba2c07](https://github.com/Sheezy-Art/sheezy.art/commit/3ba2c077d37dc8d3386987630fc882b3f61ec98b)
