### ISSUE TITLE
[BUG] gallery block ingnores row amount lower than 4 rows

### ISSUE THREAD

**Issue by zaten-p** [Sheezy-Art/sheezy-hub#230]
**Describe the Bug**
I was trying to set my gallery block to 2 rows from 4, but after saving changes the gallery block still displays 4 rows.

**To Reproduce**
1. Go to gallery block
2. set row number to a number lower than 4
3. Save changes

**Expected Behaviour**
row number should be reset from 4 rows to 2 rows

**Screenshots**
![image (2)](https://github.com/Sheezy-Art/sheezy-hub/assets/110613199/2336b09f-b25f-420f-8d4d-2f9485e34eb2)
![image (3)](https://github.com/Sheezy-Art/sheezy-hub/assets/110613199/3fab31f8-497f-4e60-a389-5c29e2288478)
I have censored a few images as they're labelled as Adult on the site

**Device**
- Type: laptop
 - OS: windows 
 - Browser: google chrome
 - Version: unsure

**Comment by RainyJackalope** [comment]
I've got the same problem as of today.
The columns will update to be correct if I change them but the rows seem to ignore anything I put.

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/114519699/4f0b45ad-bc86-4911-86cf-8254b1013c9f)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/114519699/d61af6a9-3a28-4bbd-9cd4-77474778781f)

I have personally found on my end that it seems to be tied to the sort order. Setting it to random order ignores my row settings for any gallery widget I assign it to, but setting it to literally any other order makes it follow my settings again.

**Comment by boylett** [comment]
Fixed by [#8735a00](https://github.com/Sheezy-Art/sheezy.art/commit/8735a0075de8cf9a42c6ef6cb4c1048ec598880b)
