### ISSUE TITLE
[BUG] Journals on front page not showing most recent journals

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#231]
**Describe the Bug**
On the main/front page, in the "Journals from People You Follow" section, it should be showing most recent journals from people I follow. Instead of most recent, it just shows the most recent from when the site shut down previously. 

**To Reproduce**
1. Go to (https://sheezy.dev/)
2. View "Journals from People You Follow" 
3. See error

**Expected Behaviour**
Should be showing most recent journals - multiple people I follow have posted new journals, but they don't appear in this section. 

**Screenshots**
![rtqearteart](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/77dff80e-0d4a-406c-8a08-b807fbe90874)
this screenshot is from today, all of these submissions from "2 years ago", none of these are recent

**Device**
- Type: desktop
 - OS: windows
 - Browser: firefox
 - Version: Version 121.0 (64-bit)

**Comment by boylett** [comment]
Fixed by [#5d8389](https://github.com/Sheezy-Art/sheezy.art/commit/5d8389987ec377b76b0aee685660d46d4f7a2ba4)
