### ISSUE TITLE
[BUG] Unthemed buttons in subpages

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#235]
**Describe the Bug**
Certain buttons on subpages or the user page ignore the custom button colours:
- the "Load more" button in the gallery,
- the page pickers in the journal and friends tabs,
- the comment section toggle in a journal,
- the "More info" button next to the tone indicator picker,
- the "View profile" buttons on other users' Friends pages

**To Reproduce**
1. Set custom button colours.
2. Try checking the affected buttons.

**Expected Behaviour**
All buttons on the user's page are themed.

**Screenshots**
![Screenshot_20240104_100114_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/d019299e-7d87-4f29-85b0-0ffa657cfd36)

![Screenshot_20240104_100146_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/c6e951bb-95a7-4a6c-badf-08d14e528984)

![Screenshot_20240104_100206_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/a55d483d-b3c1-4a86-94bb-3fdcf00d8e20)

![Screenshot_20240104_100228_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/86c4e25f-dece-45f2-9e3f-c0a798509b1d)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/63de3ce7-b5b7-4578-9254-9be7730bb660)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0693a202-fac2-4b49-b4dd-9a4d19e951a7)

**Device**
- Type: Smartphone
 - OS: Android
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by lumiscosity** [comment]
(happens on PC too, I use Firefox 121.0 on Windows)

**Comment by boylett** [comment]
Fixed by [#7b15de9](https://github.com/Sheezy-Art/sheezy.art/commit/7b15de9830166a421661ab1d2583af85117628c2)
