### ISSUE TITLE
[BUG] Journal attribute text setting field gets squished on mobile

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#237]
**Describe the Bug**
On mobile, the attribute text setting field gets squished by the "Add attribute" button and the line it leaves behind.

**To Reproduce**
1. Start writing/editing a journal on mobile.
2. Take note of the attribute fields.

**Expected Behaviour**
The "Add attribute" button is either simplified to a "+" similarly to the attribute icon picker or moved to a separate line below all the attributes on mobile.

**Screenshots**
![Screenshot_20240104_101621_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/45b31935-0a21-437c-bd35-5eae8fde599e)

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#6d2c5d3](https://github.com/Sheezy-Art/sheezy.art/commit/6d2c5d3d0df841ef343839cd9aba48cb958ffb90)
