### ISSUE TITLE
[BUG] Pagedolls render over the mobile menu

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#240]
**Describe the Bug**
Pagedolls render over the mobile menu seen by tapping on the rightmost bottom bar option or your PFP.

**To Reproduce**
1. Go to a page with a pagedoll on mobile.
2. Open the menu.

**Expected Behaviour**
The pagedoll remains below the menu.

**Screenshots**
![Screenshot_20240104_142936_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/468b6487-04b9-4c34-b182-d70af0dffd6a)

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#77c7b23](https://github.com/Sheezy-Art/sheezy.art/commit/77c7b23b5526b500b0cb7b313a28286cf1f29e28)
