### ISSUE TITLE
[BUG] Persona Account Cannot View Other Profile's Gallery

### ISSUE THREAD

**Issue by puppyknife** [Sheezy-Art/sheezy-hub#242]
**Describe the Bug**
Maturity settings panel is completely missing from Persona account, where it is visible and interactive on main account. 

**To Reproduce**
1. Log in to main account. 
2. Click on Account Settings. 
3. Click on Content Settings (the third option)
4. Scroll down to see the Maturity Settings panel, which sits below the "Content Settings" panel and above the "Exclude Tags" panel. 
5. Click on profile picture and click on switch Personas. 
6. Repeat steps 2 and 3.
7. See Error. There is no Maturity Settings Panel. 

**Expected Behaviour**
I expect to see the Maturity Settings panel to show up in the settings of my Persona account, in the Content Settings section. 

**Screenshots**
In the below screenshot, you can see that I have the Maturity Settings panel in the settings of my main account. 
![15f75956-f888-46ec-ae0f-e21d2ad89dd3](https://github.com/Sheezy-Art/sheezy-hub/assets/116110184/cc7dd485-159b-4380-b1f4-8a8efbb2155e)

In the below screenshot, you can see that no such panel exists once I switch to my Persona. 
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/116110184/2879fadb-56b2-4204-824f-8245631138fc)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Firefox
 - Version: Version 121.0

**Comment by puppyknife** [comment]
Adding a clarifying comment at Ry's request: My main issue was that when I'm on my persona's account I cannot view other people's artworks. I assumed this had to do with maturity rating hence the previous post. So the issue is this: When I'm on my main account I can visit other people's profiles and view their gallery, but cannot do so on my Persona account. I can see peoples art on the front page, I can even click on them and see them. But when I visit their profile and click on "Gallery" suddenly all their artwork is gone with a message saying "Couldn't find any artworks matching your filters" 

Main Account "Content Specifications" is Adult, Main Account "Maturity Settings" is Explicit, Side Account "Content Specifications" is explicit

**Comment by boylett** [comment]
This should be fixed as of [#e2051fc](https://github.com/Sheezy-Art/sheezy.art/commit/e2051fced3684f5dfbc996098e99f57b39bd9e10). Please let me know if you're still experiencing this issue!
