### ISSUE TITLE
[BUG] Making more than 1 pinboard duplicates the original pinboard

### ISSUE THREAD

**Issue by voxaz** [Sheezy-Art/sheezy-hub#243]
**Describe the Bug**
Adding another pinboard block just makes a copy of the already existing pinboard

**To Reproduce**
1. Already have a pinboard set up with images
2. Edit profile and create a new pinboard
3. its just a duplicate
4. profit

**Expected Behaviour**
New, blank pinboard should be created

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/bd166cf5-206b-4109-b30e-bd249963b74d)

Top - new pinboard
Bottom - original

**Device**
- Type: laptop
 - OS: windows 11
 - Browser: chrome
 - Version: Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by voxaz** [comment]
update - deleting the pins on one board also deletes them on the other

**Comment by boylett** [comment]
Should be fixed by [#4d13941](https://github.com/Sheezy-Art/sheezy.art/commit/4d139416172a4e6dfeef7e5d8f50489674433bbd). Please feel free to reopen if you are still experiencing this!
