### ISSUE TITLE
[BUG] Auto-Likes / Replies?

### ISSUE THREAD

**Issue by phantacode** [Sheezy-Art/sheezy-hub#244]
**Describe the Bug**
There is a minor issue when I post a comment on someone else's profile, there is a chance that the comment would automatically be hit with a like and/or be liked & replied with no replies and/or likes when I refresh the page.

**To Reproduce**
1. Go to anyone's profile in the Comments section.
2. Type in comment.
3. Hit reply and see if the reply is liked and/or reply. (Auto-liked / reply)
4. Hit refresh button on browser and the like / reply mysteriously vanishes. 

**Expected Behaviour**
There would be no likes / replies after a comment is made unless someone hits like and/or reply.

**Screenshots**
![bugimage1](https://github.com/Sheezy-Art/sheezy-hub/assets/155670144/b12a1383-4987-44f2-b4b1-b2380bfca671)

**Device**
- Type: Desktop
 - OS: MacOS
 - Browser: Safari
 - Version: 16.6

**Comment by boylett** [comment]
Should be fixed by [#77c7b23](https://github.com/Sheezy-Art/sheezy.art/commit/77c7b23b5526b500b0cb7b313a28286cf1f29e28). Please let me know if not.
