### ISSUE TITLE
[BUG] "Trending this month" on front page displays old art

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#245]
**Describe the Bug**
The "Trending this month" part of the front page displays art from "2 years ago"

**To Reproduce**
1. Go to (https://sheezy.dev/)
2. Scroll down to "Trending this month"

**Expected Behaviour**
I assume that what this usually shows is random art that has a lot of favorites/likes from a certain time period. It's totally possible that right now it just hasn't had enough time to accumulate "Trending" pieces, but it was suggested I report this since I didn't see it reported yet!

**Screenshots**
![2024-01-04 14_13_53-Window](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/a1c207d0-60a7-44f6-8176-487244e20c94)
Images in screenshot are all from "2 years ago" - no other images that scroll through this feature are from any more recent than that. 

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0 (64-bit)

**Comment by boylett** [comment]
Fixed by [#5d8389](https://github.com/Sheezy-Art/sheezy.art/commit/5d8389987ec377b76b0aee685660d46d4f7a2ba4)
