### ISSUE TITLE
[BUG] Blocking a user results in a 404 "user not found" page

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#246]
**Describe the Bug**
I blocked a user on the site and for a moment I was able to view their page - until I refreshed, and received a 404 User Not Found error. I had a two tabs of the blocked user's page open - one of their gallery and one of their front page. After blocking and refreshing, the gallery redirected me to https://sheezy.dev/browse?q= and their front page to the 404 User Not Found message. 

**To Reproduce**
1. View user's page
2. Click "block"
3. Attempt to view user's page
4. See 404 error

**Expected Behaviour**
I assumed I would be able to view the user's page even while they're blocked in case I wanted to unblock them in the future. 

**Screenshots**
![2024-01-04 15_43_45-](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/421734b4-9b87-46cf-a217-d2cad448cf12)

**Device**
-Type: Desktop
-OS: Windows 10
-Browser: Firefox
-Version: 121.0 (64-bit)

**Comment by boylett** [comment]
This is intended behaviour – the whole point of blocking a user is so that you can't see any of their content, or their profile. You can unblock users from your **Account Settings** page under **Security & Privacy** > **Blocked Users** :)

**Comment by kushbreth** [comment]
Awesome, wasn't sure if it was intended or not! Thanks so much for your work!!!
