### ISSUE TITLE
[BUG] Tagging is CaseSeNsITive

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#248]
**Describe the Bug**
Tagging is case sensitive

**To Reproduce**
1. Tag a piece  (ie. dog)
2. Tag a second piece but capitalize a letter (ie. DOG)
3. Use one of the versions to search for the image or load it into a gallery block

**Expected Behaviour**
That as long as its spelled the same, it would be picked up by the search

**Screenshots**
![Screen Shot 2024-01-04 at 4 04 16 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/d4d53e13-f365-4f46-9d03-40cab60c6397)
![Screen Shot 2024-01-04 at 4 04 36 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/271f9869-0291-4abd-ae97-7a79f81ea09f)

**Device**
- Type: Laptop
 - OS: iOS 15.5
 - Browser: Firefox
 - Version: Up to date

**Comment by Sheishori** [comment]
Similarly two word tags ie. "mr man" require either an underscore or a dash (mr-man, mr_man), but the dash and underscore aren't recognized in the search as an empty space between the words, instead both need separate searches specifically including either the dash or the underscore

**Comment by boylett** [comment]
This issue is now fixed as of [#34adcb1](https://github.com/Sheezy-Art/sheezy.art/commit/34adcb1eb47af3c2b5613bc629faad22f6ffc5fb)

> Similarly two word tags ie. "mr man" require either an underscore or a dash (mr-man, mr_man), but the dash and underscore aren't recognized in the search as an empty space between the words, instead both need separate searches specifically including either the dash or the underscore

This is no longer the case as of [#6a28ed7](https://github.com/Sheezy-Art/sheezy.art/commit/6a28ed72f7270873266346ef230fc212454a49ed) – see [this example](https://sheezy.dev/browse?q=%23test_tag) :)

**Comment by Sheishori** [comment]
> This issue is now fixed as of [#34adcb1](https://github.com/Sheezy-Art/sheezy.art/commit/34adcb1eb47af3c2b5613bc629faad22f6ffc5fb)
> 
> > Similarly two word tags ie. "mr man" require either an underscore or a dash (mr-man, mr_man), but the dash and underscore aren't recognized in the search as an empty space between the words, instead both need separate searches specifically including either the dash or the underscore
> 
> This is no longer the case as of [#6a28ed7](https://github.com/Sheezy-Art/sheezy.art/commit/6a28ed72f7270873266346ef230fc212454a49ed) – see [this example](https://sheezy.dev/browse?q=%23test_tag) :)

Is it an intended feature for test_tag and test-tag to show different things?
Also searching for anything with two words just doesn't work at all
[![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/b7909deb-26a5-40cb-9bf9-9d7da56ce152)](https://sheezy.dev/browse?q=don%27t+starve)
