### ISSUE TITLE
[BUG] Some replies not sending notifications

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#249]
**Describe the Bug**
Inconsistently, some replies do not send notifications. This has happened on submissions where I've received content moderation, comments on profiles, and others that I've missed/forgotten about. 

**To Reproduce**
1. Receive comment 
2. Do not receive notification for comment
3. See error

**Expected Behaviour**
Expected to receive a notification for replies/comments, especially for the one that was moderation related. 

**Screenshots**
![2024-01-04 15_52_31-Window](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/b4b908ef-e96c-4374-9bd1-1691e6230de1)
![2024-01-04 16_12_32-Window](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/8ce77ff3-9f93-41a1-a9c3-59fc4b6bcc4c)
![2024-01-04 16_13_16-Window](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/0317345a-8fa3-4713-a729-dafdc3d47ec4)
Would like to note, that the notification from Wake is a notification for a reply to me telling them I didn't get the notification for their moderation - just to be clear. I hope that makes sense LOL
Both replies shown here are ones I did not get notifications for - this has happened to other replies as well but I honestly can't remember which ones and obviously with no notification it's difficult to track where it happened.

**Device**
-Type: Desktop
-OS: Windows 10
-Browser: Firefox
-Version: 121.0 (64-bit)

**Comment by kushbreth** [comment]
![2024-01-04 19_06_45-Window](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/fffe337c-0768-4a73-baff-a64f891bd25d)
Let me know if I should add this to my original post, but this is another reply on someone else's profile that I didn't receive a notification for!

**Comment by boylett** [comment]
Should now be fixed by [#772bc6a](https://github.com/Sheezy-Art/sheezy.art/commit/772bc6a1d2b6f31ebba45d76a2cc5729bf26b8fe). Let me know if not!
