### ISSUE TITLE
[BUG] Mobile (phone) displaying as main but commenting as persona

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#250]
**Describe the Bug**
Mobile Displays active account as main but comments as last persona changed to.

**To Reproduce**
1. Change to a persona on desktop
2. Open Sheezy.dev on your phone
3. Leave a comment

**Expected Behaviour**
Whichever icon is displayed on the top right is the one that is interacting with the website.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/9805be8c-654a-4ac6-a367-b77e1f51745a)

**Note**
I know Personas cant be changed on phones yet, so i assume it has to do with that.

**Device**
- Type: Galaxy A42 5G 
 - OS: Android 
 - Browser: DuckDuckGo
 - Version: unsure

**Comment by boylett** [comment]
Fixed by [#e875b1e](https://github.com/Sheezy-Art/sheezy.art/commit/e875b1e3fbc953a8bd7326797654944c2a517faa)
