### ISSUE TITLE
[BUG] Putting text on a new line only works when using HTML

### ISSUE THREAD

**Issue by voxaz** [Sheezy-Art/sheezy-hub#257]
**Describe the Bug**
Enter doesn't work for making a new line of text, in the preview it puts it all on the same line

**To Reproduce**
1. Use any text input area on the site
2. Press enter to try and make a new line
3. Preview or post to see it didn't work and it's all on the same line
4. Profit

**Expected Behaviour**
Enter should create a new line, makes typing more accessible to those who don't know/don't want to learn code

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/9b9315b5-3cb9-486f-9fc1-f743a8786fa9)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153233215/26a5733a-cd8a-4002-adb8-a51de44ec2d8)

**Device**
- Type: Laptop (also doesn't work on ipad)
 - OS: Windows 11
 - Browser: Chrome
 - Version: Version 120.0.6099.130 (Official Build) (64-bit)

**Comment by lumiscosity** [comment]
sorry to say but this is an Intentional Markdown Feature™️. newlines in markdown are two newlines, and a break is `<br>`.
