### ISSUE TITLE
[BUG] "Sign Out" button icon in session management gets offset when the menu has to scroll

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#259]
**Describe the Bug**
The "Sign Out" button icon in session management gets offset when the menu has elements that are too wide and is forced to enable scrolling.

**To Reproduce**
1. Log in with a particularly long session name.
2. Check the session management menu.

**Expected Behaviour**
The icon remains within the button.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/2f595452-b99e-4b65-baba-cd4c35e3033a)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#81bc880](https://github.com/Sheezy-Art/sheezy.art/commit/81bc88048ed5c4fe18a652ac33f6c36a155f78f7)
