### ISSUE TITLE
[BUG] 418 Error when changing youtube embed link

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#261]
**Describe the Bug**
When updating my embed box's link from one youtube link to another I'm greeted with a 418 error. This happens to some youtube links but not all.
[Here's the video I tried to embed in case it's relevant. ](https://youtu.be/Ff1DjBe3LOM?si=KrlFBpZg7YYhlAIf)
[Here's what it was before.](https://youtu.be/fP_3oo3RCGo?si=m1mljAho3fCn6NpJ) It wasn't working on youtube's end so I wanted to change it.
[When I changed it to this, ](https://youtu.be/6gwVy9NsgrA?si=1dRL36rtZH32OR5O) it worked.

**To Reproduce**
1. Edit profile page.
2. Edit existing youtube embed.
3. Try to save.

**Expected Behaviour**
My page should save instead of giving me an error.

**Screenshots**
https://files.catbox.moe/66hdk9.mp4

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#9ea0955](https://github.com/Sheezy-Art/sheezy.art/commit/9ea09556b62153d80d931d26056692aa9d8c6a84)
