### ISSUE TITLE
[BUG] Its saying I don't exist ;v; u gave me a passcode though

### ISSUE THREAD

**Issue by GrungeTeeth** [Sheezy-Art/sheezy-hub#265]
It's saying I have not signed up with you guys when I give my email and the passcode you gave me.

**Comment by boylett** [comment]
Your account is linked up – you should be able to sign in with your username, **GrungeTeeth**, though you will likely need to reset your password via the [Help](https://sheezy.dev/account/help) page.

For future reference - account queries are better off sent to our [Contact Email](mailto:contact@sheezy.art) as they will get picked up a lot quicker! :)
