### ISSUE TITLE
[BUG] Capitalization error in the site rules

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#266]
**Describe the Bug**
"You must not Impersonate" is written instead of You must not impersonate" on the site rules

**To Reproduce**
1. Go to the site rules
2. Note the capitalization error.

**Expected Behaviour**
There is no capitalization mistake.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/87c124d7-a9d5-44a8-94ba-76b2f8f2d87a)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Goodness me, now that's scrutiny! I love it! 😆

**Comment by lumiscosity** [comment]
just found it when looking at the changed files in github lol. it was introduced in the recent revisiopn

**Comment by lumiscosity** [comment]
just a reminder to update it on the github too! it's fixed on the site but the .md document still has it
