### ISSUE TITLE
[BUG] Sorting doesn't work in galleries

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#268]
**Describe the Bug**
The sorting search modifiers seen in the advanced search menu don't work when viewing user galleries.

**To Reproduce**
1. Go to any user's gallery.
2. Change the sort settings in the sidebar.
3. Update the filters.

**Expected Behaviour**
Sorting works as intended.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0ef48b0d-d627-471a-b6ac-e75048322388)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/7f6bb141-1800-4c67-9545-497a4744cf05)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#f0be72c](https://github.com/Sheezy-Art/sheezy.art/commit/f0be72c10a2513fb29ea690c0ebefeb9147da097)
