### ISSUE TITLE
[BUG] Cannot remove yourself from friends or cancel/accept a contact request sent to yourself

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#269]
**Describe the Bug**
If, through any bug, you manage to follow yourself, then add yourself to friends/send yourself a contact request, you cannot remove yourself from your friends list and you cannot cancel or accept the contact request you've sent to yourself.

**To Reproduce**
1. Follow yourself.
2. Add yourself to friends/send yourself a contact request.
3. Try to remove yourself from friends/cancel the contact request (the option for accepting it doesn't appear).

**Expected Behaviour**
You can remove yourself from friends or cancel a contact request sent to yourself.

**Screenshots**
![firefox_w879ZLY6jJ](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/37aa6d7b-2def-490d-b7ab-7f49b49ae3c7)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Should be fixed now. Please let me know if you're still seeing these in your friends list.
