### ISSUE TITLE
[BUG] Search Load More freaking out

### ISSUE THREAD

**Issue by voxaz** [Sheezy-Art/sheezy-hub#27]
**Describe the Bug**
idk now im looking at it maybe its just the non admin stuff coming through for a second? idk youre the expert

**To Reproduce**
Search artworks, load more, scroll down

**Expected Behaviour**
Stuff loading without images jumping around

**Screenshots**
https://github.com/Sheezy-Art/sheezy-hub/assets/145017198/5102aabb-dce8-44d0-ae86-4383f0f59aae

**Device**
- Type: PC
 - OS: Windows
 - Browser: Chrome
 - Version: version of what? chrome? windows? idk chrome but windows 11

**Comment by boylett** [comment]
That is extremely odd! Thanks, will look into it

**Comment by voxaz** [comment]
it does the same thing if you scroll to the bottom of an artwork and look at the similar artworks section, it loads in and then refreshes with new images

**Comment by boylett** [comment]
Fixed with [#2fd840f](https://github.com/Sheezy-Art/sheezy.art/commit/2fd840fa9cc21b073baa533196d5704994fdafa1)
