### ISSUE TITLE
[BUG] Persona galleries take a long time to load

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#271]
**Describe the Bug**
Persona galleries take a long time to load compared to other galleries. Seems to have started happening a few hours ago. Affects profile gallery blocks as well. Happens regardless of the active persona (or lack thereof).

**To Reproduce**
1. Go to any persona account.
2. Note the empty gallery blocks/gallery page.
3. Wait for about 10 seconds; the images should load.

**Expected Behaviour**
Persona galleries and gallery blocks load at a reasonable speed.

**Screenshots**
![firefox_8BpsAivkAP](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0395c3c1-e06e-458e-810f-8a48799c10cb)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#5aa17ef](https://github.com/Sheezy-Art/sheezy.art/commit/5aa17ef9282e40bb0314e821c7f2081951a54898)
