### ISSUE TITLE
[OVERSIGHT] Unnecesary filters in user gallery

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#274]
**Describe the Bug**
Since a user's gallery is specific to that user, there is no need for the "users and personas" bar, the "created by me" filter and "followed by me" filter.

**To Reproduce**
1. Go to any user's gallery.
2. Check the advanced search sidebar.

**Expected Behaviour**
The unnecesary filters don't appear.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/ba93a62f-1730-45b0-9d5a-fadd47d7fc25)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#14e866a](https://github.com/Sheezy-Art/sheezy.art/commit/14e866a8a0344d41bca050c9874cb5e935ced2ab)
