### ISSUE TITLE
[BUG] Persona artworks don't appear in search results

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#276]
**Describe the Bug**
Persona artworks don't appear in search results.

**To Reproduce**
1. Post an artwork as a persona.
2. Try to look it up.

**Expected Behaviour**
Persona artworks appear in search results.

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#79505f8](https://github.com/Sheezy-Art/sheezy.art/commit/79505f85429ead83bad7e9b107560089a88d0904)
