### ISSUE TITLE
[BUG] Disabling the theme causes cover repeat settings to be ignored

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#277]
**Describe the Bug**
Using the disable theme feature causes the cover repeat settings to be ignored, despite the cover itself staying.

**To Reproduce**
1. Go to a user profile with a non-looping cover.
2. Disable the theme.

**Expected Behaviour**
Either the cover is completely removed when disabling a theme, or the cover looping (and background colour) are respected.

**Screenshots**
![firefox_jEZVliPfl4](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/75d7d4ce-5cf6-4b58-b063-ba8f98647cd7)

![firefox_tv3JTLjmeE](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/ab2942d1-f9a2-4d17-b758-7f07ea64d270)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by tewm** [comment]
G.G.I.C '24
Issue intact as of Jan 8th
https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/44d2687d-3056-465b-92de-25e35c4d2780

**Comment by boylett** [comment]
As this is an opinion-related report rather than an actual bug, I'll be closing this for the time being. The way it currently works is fine and does not break anything.
