### ISSUE TITLE
[BUG] Animated .webp files get lossily compressed

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#278]
**Describe the Bug**
Animated files uploaded as .webp files get lossily compressed; this is especially noticeable on pixel art.

**To Reproduce**
1. Upload an animated .webp file.
2. Note the compression.

**Expected Behaviour**
Much like other art on the site, animated .webp files are compressed losslessly.

**Screenshots**
![i_view64_ESd3AYlJ8F](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/a4670513-62d3-4d6b-bd47-b3101e9ea8f7)

![firefox_NXPlWUPQEy](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/5b14c801-32ac-4a9b-89ea-3180619d56ec)

File used: https://cloud.dissonant.dev/s/9Wz2b2ZkiRzzx7W

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
This *should* be fixed now with the new uploader. Let me know if not.
