### ISSUE TITLE
[TODO] Journals Mod Queue

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#280]
**Describe the Bug**
Currently, you cannot view the maturity rating of any journals in the mod queue. Right clicking the journal to manually review leads to '404 Not Found'.

**To Reproduce**
1. Go to 'Admin Panel'
2. Click on 'Menu' > Mod Queue > Journals
3. See no rating even on T, A or X journals. 
4. Click journal title > '404' page

**Expected Behaviour**
To see the journal's maturity rating.

**Screenshots**
N/A

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
The journal mod queue should still be considered a "Work In Progress" and so does not warrant bug reports just yet. Moving this to ToDos.
