### ISSUE TITLE
[BUG] Newly made Custom Content Block has content from older block

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#281]
**Describe the Bug**
Newly created Custom Content blocks have the information (Title and HTML) from older blocks.

**To Reproduce**
PREREQUSITES
- Create a Custom Content block if you haven't
- Put some HTML in it

THE ACTUAL BUG

- Create another Custom Content block
- It has the data from the older one copied over

**Expected Behaviour**
Newly created blocks should be freshly made and not copies of older blocks

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/7125128e-3ea9-44b1-8336-7741724e1dc9)

**Known Workarounds**
Putting the Custom Content block in storage (either manually or leaving the profile without saving on creation) will reset its contents.

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Should be fixed by [#4d13941](https://github.com/Sheezy-Art/sheezy.art/commit/4d139416172a4e6dfeef7e5d8f50489674433bbd). Please feel free to reopen if you are still experiencing this!
