### ISSUE TITLE
Tailwind breakpoint prefixes cause CSS declarations to fail

### ISSUE THREAD

**Issue by hasnogame** [Sheezy-Art/sheezy-hub#282]
**Describe the Bug**
CSS declaration classes prefixed with Tailwind breakpoints e.g. `sm:`, `md:`, etc. no longer activate even when the browser viewport is within the bounds of the specified breakpoint.

**Steps to reproduce the behavior:**
1. [Verify your viewport is greater than 640px width](https://whatismyviewport.com)
2. Create a new Custom Content block
3. Use the following or similar code:
```html
<h1 style="sm:font-size:64px; sm:line-height:64px; text-align:center;">WARNING: PAGE MAY BE A TRIGGER FOR PEOPLE WITH SENSITIVITIES TO FLASHING LIGHTS</h1>
```
4. Remove the `sm:` prefixes to see what the CSS should look like

**Expected Behaviour**
Prefixed CSS declarations should activate so long as the viewport is the adequate width.

**Screenshots**
Without breakpoint prefixes:
![IMG_9027](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/99595aca-6802-4218-9cb2-b387291723fd)

![IMG_9029](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/b2982dda-d5bb-416f-bb66-c9fc88adad09)

With breakpoint prefixes:
![IMG_9030](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/552c2804-aaba-4615-a25d-d06b1e2d9b4d)

![IMG_9031](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/17039210-2517-4f0c-b441-701b2774e084)

**Device**
- Type: Desktop
 - OS: Windows 11
 - Browser: Firefox
 - Version: 121

Also occurs on iOS Firefox and Android Firefox.

**Comment by boylett** [comment]
You are attempting to mix Tailwind CSS classes with inline CSS. Tailwind classes must always be inside the `class` attribute in order to work, and are not compatible with raw CSS. Your above code would need to be written like so:

```<h1 class="sm:text-[64px] sm:leading-[64px] text-center">WARNING: PAGE MAY BE A TRIGGER FOR PEOPLE WITH SENSITIVITIES TO FLASHING LIGHTS</h1>```

[See this working example](https://play.tailwindcss.com/SzuUbX5fM8) in Tailwind Play.

**Comment by hasnogame** [comment]
Sorry for the confusion Ry, I think I may have screwed up my example during troubleshooting. The issue seems to be persisting even with proper config:

![IMG_9145](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/9e50b7ec-83f7-4f7f-bc44-c82758073645)
![IMG_9142](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/2ba64497-39bb-4c8c-97f6-5edf6ff68a62)
![IMG_9143](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/a21973ce-f11a-4e8c-a796-9aee2a97fb0f)
![IMG_9144](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/98c1ea63-bbc1-49d5-a5f6-af22e9b9711d)

I believe based on my viewport size it should be triggering the text to be centered.

**Comment by boylett** [comment]
Aye, if the issue is just that it doesn't work on Sheezy then it's the same as #291 – I'll be fixing this soon :)
