### ISSUE TITLE
[BUG] Gallery disappears when tagging in and out as a persona

### ISSUE THREAD

**Issue by tewm** [Sheezy-Art/sheezy-hub#283]
**Describe the Bug**
My own gallery disappears when I tag in as a persona, and remains absent when I tag back out into my main account. Oddly enough, other users' galleries are unaffected.

**To Reproduce**
1. Tag in as a persona. Notice how my own gallery is already gone. (The following screenshots are from the persona's perspective)
![librewolf_gsxhOQ2C9w](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/4910b3cb-8419-4165-bf1f-7632ef970e02)
![librewolf_q7sY4zsqko](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/afed4772-f0fc-44c4-b86a-1dc1ad14214d)
![librewolf_gj0Bc9AFfd](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/1767182a-37d9-4ff6-a683-09a92a62650f)
![librewolf_pRmLkwLhnp](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/062c2bd4-57ce-41bf-8458-18b85ae97d07)

2. Tag out. The gallery is still gone. (The following screenshots are from my main account's perspective)
![librewolf_88zGTfHBmp](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/0ef627e1-7e0c-4c93-aa42-06e91110a5b2)
![librewolf_rtRjbW9LSc](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/690a90bd-3d54-4dc6-b432-b0e78b55b76d)
![librewolf_TuxHwyAj71](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/8fbeb0f1-2d47-4cac-8c24-21df549a68be)
![m1e6NKgQ5d](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/247fa902-9022-4b5c-83f2-dca3a4a41e12)

**Expected Behaviour**
Obviously, the galleries should have been left intact.

**Additional screenshots**
Other user's galleries still appear. (Following screenshots are from the persona's perspective, but this also happens in my main account)
![librewolf_PWSzRbOi6h](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/3bf012e5-f92c-4868-99ff-c4353cacde8c)
![librewolf_cZexKmGJNo](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/e1cfb06c-80c5-479a-adc5-8c3ad354e2da)

**Device**
- Type: Laptop
 - OS: Windows 10
 - Browser: Librewolf (Firefox fork)
 - Version: 119.0.1-1

**Comment by tewm** [comment]
Ah. Beautiful.
Here's the missing, glitched out screenshot.
![librewolf_rtRjbW9LSc](https://github.com/Sheezy-Art/sheezy-hub/assets/47818176/690a90bd-3d54-4dc6-b432-b0e78b55b76d)

**Comment by tewm** [comment]
oh my god what
update: as of the latest update my gallery block has been fixed, but not the tab. I still can't see my persona's gallery at all. However, it turns out that this may have not even been caused by switching in and out of personas, since this is a global thing and no one can see my gallery -- assuming I didn't get shadowbanned, that is (which is unlikely because I never broke any in-site rules as far as I'm aware).

https://discord.com/channels/1143702362091966654/1191539111987777547/1194116064666206368

**Comment by tewm** [comment]
And so, with commit [02ae414](https://github.com/Sheezy-Art/sheezy.art/commit/02ae4143cff9cd5e280c894bb398821604dd682f), this issue has been resolved.
TYBR (THANK YOU BASED RY)

**Comment by Sheishori** [comment]
Are we sure this has been fixed? I can't see that block from my own account, but gallery works just fine.
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/8491b674-48fe-4a81-aaf8-c03c422fa1f0)
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/8182c2ac-5ffd-4ac6-95bb-103f724a3e74)

**Comment by Sheishori** [comment]
It seems like now personas can see their own profile gallery blocks, but other accounts can't

**Comment by Sheishori** [comment]
Fixed with [711137a](https://github.com/Sheezy-Art/sheezy.art/commit/711137af5abe354de1ba94696dbc283a3f3ee5a2)
