### ISSUE TITLE
[BUG] Button to edit Persona profiles from main profile no longer exists

### ISSUE THREAD

**Issue by CooperationIsKey** [Sheezy-Art/sheezy-hub#284]
**Describe the Bug**
Normally, at least up to now, I've been able to edit my Personas' profiles from my main account without switching to the Persona account. However the "edit profile" button has vanished. I can still edit Persona profiles if I'm in their account, however.

**To Reproduce**
1. From main account, navigate to any own persona account.
2. "Edit Profile" button is simply not there.

**Expected Behaviour**
Normally you can edit persona accounts' profiles when logged into main account.

**Screenshots**
![edit profile button missing](https://github.com/Sheezy-Art/sheezy-hub/assets/13866512/9c8a23c5-36e1-426b-bd28-7e8a71acc1ff)

**Device**
- Type: Laptop PC
 - OS: Windows 11
 - Browser: Firefox
 - Version: 121

**Comment by boylett** [comment]
Fixed by [#3d4f953](https://github.com/Sheezy-Art/sheezy.art/commit/3d4f953ebb1030cbc08473e9a59942314572e9ac)
