### ISSUE TITLE
[BUG] "Followed by me" filter is completely ignored when you follow nobody

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#288]
**Describe the Bug**
The "Followed by me" filter is completely ignored when you follow nobody. This affects profile blocks, searches, the home page "new from people you follow" section and so on. The other filters correctly report that they can't find anything.

**To Reproduce**
1. Ensure that you aren't following anybody.
2. Search for anything with the "Followed by me" filter.

**Expected Behaviour**
The "Followed by me" filter is respected.

**Screenshots**
![firefox_vEH8eB5bQF](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/71e953bb-3b49-4f38-8fd7-92863805d935)

![firefox_86pEqfK3Tp](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/b8230432-8d4e-40a5-ad81-39137ec6a829)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by punkalope** [comment]
Should be fixed now.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a7d1097d-89c5-4cbc-bd6c-de0e58196e66)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/7f417d0b-25ae-4e48-a571-0776361be801)
