### ISSUE TITLE
[BUG] Views are not correctly reflected on artwork

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#290]
**Describe the Bug**
An artwork's viewcount on site is not accurate to its 'true' viewcount.

**To Reproduce**
- Upload art
- Nag people to look at it until they do (or they block you)
- Notice that the viewcount isn't accurate.

Ry has offered an explanation for the bug:
> "Views are added to the database as expected, but are not reflected by the View Counter underneath artworks"

**Expected Behaviour**
The viewcount should be synced between the database and the onsite viewcount

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/d2ed9cf7-1e4b-491c-9423-7522353abae4)

**Device**
*On-site bug*

**Comment by lumiscosity** [comment]
![firefox_TqFGz9Y9kc](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/f5b9ba5d-951a-4bbb-9ea4-27bfe2e235f1)

can confirm on my artwork as well

**Comment by boylett** [comment]
Fixed by [#b20b722](https://github.com/Sheezy-Art/sheezy.art/commit/b20b722c0f67628eac09bc3374f5bd3b18746aa8)
