### ISSUE TITLE
[BUG] Multiple tailwind classes not working (custom box)

### ISSUE THREAD

**Issue by Exodus-Drake** [Sheezy-Art/sheezy-hub#291]
**Describe the Bug**
Trying to use certain tailwind classes in custom box yields no styling. Some tailwind classes do still work, ex. class="relative" results in
position: relative style being added to element.

**To Reproduce**
1. Go to 'Edit page'
2. Create a new custom box
3. add an Html tag and give it tailwind classes (ex. use classes "pt-32 px-16 pb-16")

**Expected Behaviour**
Style classes should result in styles being applied to element (ex, "px-16" should result in tailwind class adding padding-right: 16px and padding-left: 16px)

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/c5525f2b-2624-4839-b4db-80018d8d137f)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/6d86e108-02cc-4c61-a57c-82d97eeae47f)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/fbb96205-8640-48e6-a270-a8bc8a74d37f)

**Device**
- Type: [Desktop PC]
 - OS: [Windows 10]
 - Browser: [Firefox (Waterfox)]
 - Version: [Version G6.0.7 (64-bit)]

**Comment by boylett** [comment]
Fixed by [#1538dc3](https://github.com/Sheezy-Art/sheezy.art/commit/1538dc37a3b615f7dbb45e2861ce20a67ac12ba5)
