### ISSUE TITLE
[BUG] Replies don't update when changing comment pages

### ISSUE THREAD

**Issue by Sheishori** [Sheezy-Art/sheezy-hub#292]
**Describe the Bug**
If a reply to a comment is open on a profile and then the comment page is switched, the replies to comments on the next page get overriden by the replies form the previous one until refreshed.

**To Reproduce**
1. Go to a profile with more than 1 page of comments.
2. Expand replies under a comment.
3. Switch comments page to a different one.

**Expected Behaviour**
When changing a page, the opened reply should go away and the comments page should show appropriate replies to displayed comments.

**Screenshots**
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/c203221f-abfd-489a-8d6b-2e8357fa3a70)
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/b3c33608-cf95-4255-97f4-de8f95e5a74f)
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/ffc78952-7ad7-4f39-a3ca-d77028dd55c7)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Google Chrome, Firefox

**Comment by Sheishori** [comment]
Also it looks like comments like/reply status doesn't update on client's side after posting a new comment (if the 1st comment on profile had a like/reply and a new comment is added, it shows the status of the previous comment)
![comments](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/ed9a1c6a-d199-4ce1-8c6c-c0c7a52fc494)

**Comment by boylett** [comment]
Fixed by [#4d13941](https://github.com/Sheezy-Art/sheezy.art/commit/4d139416172a4e6dfeef7e5d8f50489674433bbd)
