### ISSUE TITLE
[BUG] Cant tell the rating of a persona profile at a glance/ in the username in the persona block

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#293]
**Describe the Bug**
When a persona is listed in a persona block there is no indication of what rating the profile of that persona is set to.

**To Reproduce**
1. Go to your profile
2. add persona block and put a persona in there with a rating other than everyone
3. see issue

**Expected Behaviour**
Little indication next to the name or something that indicates the rating of the persona profile

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/aa287e59-05d9-4e8e-ada0-0c30d1fb4c57)

**Device**
- Type: Dekstop PC
 - OS: Windows 10
 - Browser: Google Chrome

**Comment by boylett** [comment]
Fixed by [#37fb820](https://github.com/Sheezy-Art/sheezy.art/commit/37fb82097c026cbfc76dffad1c9b85ae1af13d56)
