### ISSUE TITLE
[BUG] Persona block custom list is case sensitive

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#294]
**Describe the Bug**
You cant use capital leters in the search term for the persona or it wont find it

**To Reproduce**
1. Go to profile and add a persona block
2. make the persona block a custom list one
3. add an persona name with capitalization 
4. see error

**Expected Behaviour**
able to imput the capitals of the username of the persona and the list still show the persona in the list

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/15cc0e81-261e-4439-ac4d-6fcd79f8f6dc)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/2cd2cafb-6d04-4538-83ec-9d46b221eb1d)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/a59cd231-8cb8-4454-b3b6-3b31c6546c37)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/fd8f49c1-55ec-4d94-b53d-46d534a00e25)

**Comment by boylett** [comment]
Fixed by [#d0d1b91](https://github.com/Sheezy-Art/sheezy.art/commit/d0d1b91d5c0d45469ee6ca9783c9761f636aa412)
