### ISSUE TITLE
[BUG] Comment Signature Character limit break

### ISSUE THREAD

**Issue by Exodus-Drake** [Sheezy-Art/sheezy-hub#295]
**Describe the Bug**
Oversight for going above intended character limit in comment signature

**To Reproduce**
1. Go to Content Settings
2. Instead of using spaces in-between words, use this character "⠀"

**Expected Behaviour**
Word count should still be able to detect words between special characters

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/39057bf1-0642-4d3a-8a62-1e112fc71678)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/d7057342-c0a3-4f25-acfa-5cf6c4fc45a1)
Curse you Dax...
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/7166d7c8-5a13-40af-9c2c-e359abbc2f90)

**Device**
 - Type: [Desktop PC]
 - OS: [Windows 10]
 - Browser: [Firefox (Waterfox)]
 - Version: [Version G6.0.7 (64-bit)]

**Comment by boylett** [comment]
Fixed by [#0fd6984](https://github.com/Sheezy-Art/sheezy.art/commit/0fd6984f55f5f8f2acfdada9a006adbfa5448b84)
