### ISSUE TITLE
[BUG] Small images cannot be enlarged

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#296]
**Describe the Bug**
Small images cannot be enlarged.

**To Reproduce**
1. Go to a small artwork.
2. Try to enlarge it.
3. If the button appears in the first place, it does nothing.

**Expected Behaviour**
Small images can be enlarged, preferrably with integer scaling.

**Screenshots**
![firefox_YNbL5LTphg](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/4a4918f7-ec0d-4b84-bd05-34ba4426235a)

![firefox_OvbrvplZLd](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/269af7c6-0020-4fc7-b31f-724f516350b8)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Enlarging small artworks is not on the docket for the moment. There are too many variables to consider;
- How do we determine how large to make the artwork?
- How do we know what kind of scaling algorithm to apply? (ie. bilinear, nearest neighbour, etc.)
- What is the smallest an artwork can be before it can be resized?

For the time being the zoom button will simply be removed if an artwork is smaller than the screen width, or 660px on desktop. Will revisit this later.
