### ISSUE TITLE
[BUG] Cannot View Custom Cursor on Own Profile On Chrome

### ISSUE THREAD

**Issue by Robinik** [Sheezy-Art/sheezy-hub#299]
**Describe the Bug**
As the title describes, I am completely unable to view my custom cursor when I view my own profile on my default browser unless I go into edit profile mode. I am able to view custom cursors on other people's profiles and on Opera GX but am completely unable to on my default browser on my own profile unless I click on the edit page button. It reverts back into my Windows default cursor.

**Expected Behaviour**
I should be able to view my custom cursor on any browser on my profile in public view and in edit mode.

**Screenshots**
https://cdn.discordapp.com/attachments/1191539111987777547/1192494024876105768/Sheezy.Art_Grimmgalls_Profile_-_Google_Chrome_2024-01-04_10-38-27.mp4

**Device**
- Type: "Desktop" PC (Laptop)
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 120.0.6099.200 (Official Build) (64-bit)

**Comment by boylett** [comment]
Unsure if this is still happening – I've done my own testing with Chrome, Firefox and Edge on Windows 11 and cursors are working fine. Please let me know if you're still having this problem and I'll reopen the issue.
