### ISSUE TITLE
[BUG] SWF artwork sort icon is miscoloured in galleries

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#300]
**Describe the Bug**
The SWF artwork sort icon is miscoloured in galleries due to not being coloured to match the gallery theme like the other icons.

**To Reproduce**
1. Go to a gallery.
2. In the advanced search tab, open the artwork type filter list.
3. Note the mismatched colours.

**Expected Behaviour**
The SWF artwork sort icon is correctly recoloured.

**Screenshots**
![firefox_ynwuAEK46c](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/bd6c549a-6101-4465-b552-cc33ce89e3c2)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#b0fc86a](https://github.com/Sheezy-Art/sheezy.art/commit/b0fc86a717cc6166819ce25ea8e204f8082c1a1d)
