### ISSUE TITLE
[BUG] Comments send but you get sent to a 418 page

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#301]
**Describe the Bug**
When you send a comment somewhere, you get sent to a 418 page. The comment successfully sends though

**To Reproduce**
1. Go to a profile or art piece, anywhere you can comment
2. Write something and send
3. 418 page
4. Refresh and see your comment

**Expected Behaviour**
No 418 page

**Screenshots**

https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/de7a89d9-4d9f-42fc-9c49-f294ac673b20

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by Stormeko** [comment]
I pressed the wrong button thinking it'd do something else whoops
This also happens with accepting friend requests. Though so far that's only happened once

**Comment by pawsu** [comment]
In addition to this, accessing the second page of your own profile's comments leads to the same error

**Comment by boylett** [comment]
Fixed by [#c1151e4](https://github.com/Sheezy-Art/sheezy.art/commit/c1151e4760b30164af198719175ef684520d2630)
