### ISSUE TITLE
[BUG] Like list popup renders above the mobile menus

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#302]
**Describe the Bug**
The likes popup that appears when liking or long pressing on the like button on any work or journal appears above the mobile menus, including the bottom and top bars and the big slide-out menu.

**To Reproduce**
1. Go to an artwork.
2. Bring up the likes lost popup.
3. Check how it interacts with mobile menus.

**Expected Behaviour**
The popup renders below the menus.

**Screenshots**
![Screenshot_20240110_123148_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/f7c16fd4-61d1-4e54-baa2-13938983e116)

**Device**
- Type: Smartphone
 - OS: Android
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#77c7b23](https://github.com/Sheezy-Art/sheezy.art/commit/77c7b23b5526b500b0cb7b313a28286cf1f29e28)

**Comment by boylett** [comment]
Fixed by [#02f0437](https://github.com/Sheezy-Art/sheezy.art/commit/02f0437e3163a478916621dd8f86f608916a50e5)
