### ISSUE TITLE
[BUG] Upload info box doesn't expand on mobile

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#304]
**Describe the Bug**
The upload info box on upload popups doesn't expand to fit the screen width on mobile, causing it to stay in the corner.

**To Reproduce**
1. Open any upload popup (thumbnail, cover, cursor etc.)
2. Note the info box's position.

**Expected Behaviour**
The info box is either centered or stretched to fit the screen.

**Screenshots**
![Screenshot_20240110_200734_Firefox Nightly](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/219ead8f-4c27-4f00-9baf-26e878d63e08)

**Device**
- Type: Smartphone
 - OS: Android
 - Browser: Firefox Nightly 
 - Version: 123.0a1

**Comment by boylett** [comment]
Fixed by [#af39ad9](https://github.com/Sheezy-Art/sheezy.art/commit/af39ad95608c28af3d931724be148f191dface96)
