### ISSUE TITLE
[BUG] Button to edit Persona profiles is back, but does not work as it should.

### ISSUE THREAD

**Issue by CooperationIsKey** [Sheezy-Art/sheezy-hub#307]
**Describe the Bug**
When in my main account, there is a button to 'Edit Profile" on my persona's profile pages, however said button only succeeds in refreshing the page.

**To Reproduce**
1. Go to any own Persona profile while logged into main account (or another own Persona account).
2. Click on "Edit Profile" button.
3. Page refreshes instead of going to the profile editing interface.

**Expected Behaviour**
Clicking the "Edit Profile" button should bring the user to the profile editing interface for that profile.

**Screenshots**
n/a

**Device**
- Type: PC (laptop)
 - OS: Windows 11
 - Browser: Firefox
 - Version: 121

**Comment by boylett** [comment]
Fixed by [#9ed0576](https://github.com/Sheezy-Art/sheezy.art/commit/9ed0576b11165a52650c35439e224ab62ade88a4)
