### ISSUE TITLE
[BUG] Pinboard resized itself to wrong size

### ISSUE THREAD

**Issue by hasnogame** [Sheezy-Art/sheezy-hub#308]
**Describe the Bug**
Basically the same issue as #41. Pinboard is massive on profile page instead of the normal size.

**To Reproduce**
1. Open Sheezy profile
2. Have a pinboard on it
3. There is a chance that when you open your profile the pinboard will suddenly be huge

**Expected Behaviour**
Pinboard stays the normal size.

**Screenshots**
Bug Size:
![Screenshot 2024-01-10 214737](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/69041540-61ec-4ff4-b17b-691a3eefc258)
Normal Size:
![Screenshot 2024-01-10 215007](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/16b7ffc1-6f61-4e40-b0b9-57248c4453e4)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121

**Comment by boylett** [comment]
Merging this into #141 as it is part of the same issue
