### ISSUE TITLE
[BUG] Featured artwork block is only visible to its creator

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#309]
**Describe the Bug**
The featured artwork block is only visible to its creator

**To Reproduce**
1. Go to an account with a featured artwork block.
2. Note that it's missing.

**Expected Behaviour**
The featured artwork can be seen by other users.

**Screenshots**
![firefox_bYfPbfQU77](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/7a4fa25e-7a4d-420c-a8f8-2bbac34ea31c)

(dorfde's page is supposed to have a featured artwork block on the top left)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#8a500c2](https://github.com/Sheezy-Art/sheezy.art/commit/8a500c2699cec38d323bfb6e54939e3b94dc195d)
