### ISSUE TITLE
[BUG] Likes are broken on certain users' artworks

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#310]
**Describe the Bug**
On kushbreth's and kryxo's accounts, whenever I like a post, the like button immediately retracts (the post is liked anyways, and you can see this when you refresh the page and see the like count go up). Not sure what the cause is; my only assumption is that it's because their accounts are set to Mature while my content level is set to Teen. This doesn't happen with the presumably Adult account of CautionCat.

**To Reproduce**
1. Go to a mature account's artwork on a teen content level account.
2. Try to like the post.

**Expected Behaviour**
Likes behave normally on all artworks.

**Screenshots**
![firefox_xm7gUhsEAH](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0c75f695-c81f-49ce-b450-2b28abaa55fb)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
This *should* be fixed by [#7a3dcd3](https://github.com/Sheezy-Art/sheezy.art/commit/7a3dcd3ded3cf3a932d4d9f9a4dea86b9b009e72). Feel free to reopen if not.
