### ISSUE TITLE
[BUG] 'More from...' and 'Similar Artworks' do not function properly

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#311]
**Describe the Bug**
The 'More From...' and 'Similar Artworks' sections are dysfunctional.

**To Reproduce**
- Go to any artwork
- Scroll down to the two sections mention in the title
- Few artworks show up or none at all

**Expected Behaviour**
'More from...' will show more artwork from the user and 'Similar Artworks' will show art with matching tags as the submission.

**Screenshots**
Tags for [Artwork 1](https://sheezy.dev/lambda20xx/gallery/orangeinspirational) (created by me)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/420aea06-22a3-44a6-a81a-0a6345ab91f9)
Sections for Artwork 1
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/4506dfce-15f1-4dbd-8321-9da36db55356)

Tags for [Artwork 2](https://sheezy.dev/sugar-buck/gallery/athlete-levi) (created by someone else)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/9a27ce19-563c-47cd-8344-33df22cbbb2e)
Sections for Artwork 2
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/de802c80-c5d6-4b16-83e1-9afddbc51a48)

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#2a62b4b](https://github.com/Sheezy-Art/sheezy.art/commit/2a62b4b9f6feb7890d749017bf7337458ee5db3e)
