### ISSUE TITLE
[BUG] Markdown buttons does not change color to adapt to profile theming

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#312]
**Describe the Bug**
The markdown buttons do not change color to adapt to profile theming, and remain the same color.

**To Reproduce**
- Go to a profile that has the block color changed to white (basically any profile that has a 'dark' theme
- Go to comment section if there is one
- Observe the markdown buttons

**Expected Behaviour**
Markdown buttons should at least be the color set in 'Block Text'

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/f74fa1c5-f80f-40f8-be8e-60921bb844e6)

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by lumiscosity** [comment]
they do adapt, but to the header text colour, not the main block text colour

**Comment by boylett** [comment]
Fixed by [#accda0e](https://github.com/Sheezy-Art/sheezy.art/commit/accda0e151c91cc52dd3fc354cca6831f4e8f03a)
