### ISSUE TITLE
[BUG] Kerning error on content warning tags 

### ISSUE THREAD

**Issue by zaten-p** [Sheezy-Art/sheezy-hub#313]
**Describe the Bug**
There is no space between the letter and the name of a content warning on art posts. ( e.g: the Teen tag displays as "Tteen")

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any artwork with a content warning tag
2. Scroll down to the content warning tag (next the like button)
3. See Error

**Expected Behaviour**
there should be a space between the letter and the tag name. e.g: "Tteen" should be displayed as "T teen"

**Screenshots**
![Screenshot 2024-01-12 223815](https://github.com/Sheezy-Art/sheezy-hub/assets/110613199/4bbf87f7-01cc-489b-b2af-200bbf4ab139)
![Screenshot 2024-01-12 225207](https://github.com/Sheezy-Art/sheezy-hub/assets/110613199/92662ce1-f979-4705-a400-a7034f2b20c1)
![Screenshot 2024-01-12 225217](https://github.com/Sheezy-Art/sheezy-hub/assets/110613199/99cd58c6-7ab1-4550-8f9f-0debce13337c)

**Device**
- Type: laptop
 - OS: Windows 11
 - Browser: Google chrome
 - Version: unsure

**Comment by boylett** [comment]
Fixed by [#78741b0](https://github.com/Sheezy-Art/sheezy.art/commit/78741b0b41be4ed3758cae2f8c0346df681bd5a7)
