### ISSUE TITLE
[BUG] Other users profile comments not deleting

### ISSUE THREAD

**Issue by Sheishori** [Sheezy-Art/sheezy-hub#315]
**Describe the Bug**
Profile comments from other users return when the page is refreshed after deleting them.

**To Reproduce**
1. Add a comment to a profile.
2. Delete the comment
3. Refresh
4. See the comment come back

**Expected Behaviour**
Comment should go away after being deleted.

**Screenshots**
https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/8b2efd87-14e1-47d6-abe9-aa148f4465b2

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121

**Comment by boylett** [comment]
Fixed by [#772bc6a](https://github.com/Sheezy-Art/sheezy.art/commit/772bc6a1d2b6f31ebba45d76a2cc5729bf26b8fe)
