### ISSUE TITLE
[BUG] Missing Follow Back button in Notifs

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#316]
**Describe the Bug**
"Follow Back" Button not available in notifications for some users.

**To Reproduce**
1. Go to "notifs"
2. Click on 'followers"
3. See if theres any with a missing button

**Expected Behaviour**
"Follow Back" would be available for all users I'm not mutual with.

**Screenshots**
![Screen Shot 2024-01-12 at 5 54 41 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/7840a090-dbff-490e-887c-a0a47c8ca573)

**Note**
These are not persona accounts, However they ARE the oldest starting from the site returning. I do not have this issue with notifs from two years ago. I can give an uncensored version privately.
It is marked as "follow back" when i go to their profile pages.

**Device**
- Type: Laptop
 - OS: iOS 15.5
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
Fixed by [#ffee666](https://github.com/Sheezy-Art/sheezy.art/commit/ffee666fd8ce0a5c9f1dcfd75f320a469186df9b)
