### ISSUE TITLE
[BUG] Unable to dismiss Friend request from non-mutual

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#317]
**Describe the Bug**
Friend Request prompts "Follow Back"

**To Reproduce**
1. Use two accounts (?)
2. Follow a user
3. Send friend request despite not being mutuals (?)
4. See notif

**Expected Behaviour**
-The choice to accept or deny the request
-According to https://github.com/Sheezy-Art/sheezy-hub/wiki#custom-content , Friend requests can only be sent if mutuals.

**Screenshots**
![Screen Shot 2024-01-12 at 6 06 10 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/c6707ec0-fe5f-4366-9510-f1227d116d08)

**Note**
This notif is two years old

**Device**
- Type: Laptop
 - OS: iOS 15.5
 - Browser: Firefox
 - Version: Up to date

**Comment by boylett** [comment]
Requiring mutual status is a new addition – a lot of the old notifications will likely be coming from people who sent you a request before it was a requirement.

Soft blocking the user – that is – blocking them and then unblocking them – should fix this up. Let me know if not!
