### ISSUE TITLE
[BUG] Gif Transparency is wonky on mobile

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#319]
**Describe the Bug**
When viewing transparent gifs on mobile, the last frame is not cleared properly, meaning the frames "stack".

**To Reproduce**
- Go to any artwork that is a transparent gif on mobile. Examples: [[1]](https://sheezy.dev/spacialcube/gallery/animated-satellite-spin) [[2]](https://sheezy.dev/lambda20xx/gallery/camera-anim)
- Notice that the last frame played is often not cleared properly.

**Expected Behaviour**
Transparent gifs on mobile behave the same as PC

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/be90d43e-0a1e-4e26-a6ee-9fa218e579db)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/68e32029-5fdf-41aa-9c67-bc5cbd0c4781)

**Device**
- Type: Smartphone
 - OS: iOS
 - Browser: Firefox
 - Version: 121.2

**Comment by boylett** [comment]
This is an issue specific to Apple's WebP support. Viewing the same images on different systems and browsers removes the artefacts.

Unfortunately, there is nothing I can do to fix this apart from asking people to re-upload their images. For the time being, until, Apple, issues a fix, I have disabled conversion to animated WebP on our side.
