### ISSUE TITLE
[BUG] Journals from personas appear on the main page if you follow their owner, have broken links

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#322]
**Describe the Bug**
Journals from personas appear on the main page even if you only follow their owner. In addition, the links to them are missing the persona part of the URL, leading to a missing journal by the main account.

**To Reproduce**
1. Follow an account with a persona, but not the persona itself.
2. Have the persona post a journal.
3. Note how it appears on the main page.
4. Try clicking on it.

**Expected Behaviour**
Journals from personas only appear if you follow the persona, and the links to them work.

**Screenshots**
![firefox_eQfRNat1Lw](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/d9dc0831-0c11-413b-8150-540e00f6e011) 
(this goes to a 404 page; i only follow Dorfde, not the persona)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Should be fixed as of [#4cefb2c](https://github.com/Sheezy-Art/sheezy.art/commit/4cefb2cb4371331bbb58c936a966e6717bbe79a9). Please feel free to re-open the issue if not.

**Comment by Sheishori** [comment]
Seems like the link omits the persona part from the url,
so instead of https://sheezy.dev/A/persona/B/journal/name
there is https://sheezy.dev/A/journal/name

**Comment by boylett** [comment]
Fixed by [#6bb6c2d](https://github.com/Sheezy-Art/sheezy.art/commit/6bb6c2dd983ab81a5a65fb34c1c94f591456c3af)
