### ISSUE TITLE
[BUG] Content settings for Spotlight and Trending do not persist on page reload

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#323]
**Describe the Bug**
In Content Settings, the Spotlight and Trending options are automatically set to 'off' despite originally being set to 'on'. Flipping them back to 'on' and saving will reset both of them back to 'off' on page reload.

**To Reproduce**
1. Go to Account Settings
2. Click on Content Settings
3. Scroll down to secondary Content Settings box
4. See that both Spotlight and Trending are set to 'off'
5. Set both to 'on', hit Save Changes
6. Reload page
7. Spotlight and Trending are now set to 'off' again

**Expected Behaviour**
Setting Spotlight and Trending to 'yes' and saving will persist on page reload.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/f651cb66-5b60-4d62-8354-610e4bb56fc5)

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#24afe9e](https://github.com/Sheezy-Art/sheezy.art/commit/24afe9e911cbcd417ee32fb3d8cc3e5ed2e0bac1)
