### ISSUE TITLE
[BUG] Comments notificiation page 418s if the latest comment is from a deleted artwork

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#325]
**Describe the Bug**
The comments notificiation page 418s if the latest comment is from a deleted artwork.

**To Reproduce**
1. Create an artwork.
2. Recieve a comment on the artwork.
3. Remove the artwork.
4. Check the comments page of notifications.

The comment was a mod comment, if that changes anything...

**Expected Behaviour**
The page works as expected.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/0dbce3c5-9744-440c-afc0-9287d2c4733d)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#9850eb5](https://github.com/Sheezy-Art/sheezy.art/commit/9850eb5fcd8900a7d263546e51b577eb0fe9bc1a)
