### ISSUE TITLE
[BUG] Unable to add Tags to Pieces on iPad 

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#327]
**Describe the Bug**
When adding a tag on a piece of artwork, using the search bar (both horizontal at the top AND the Advanced search), or certain sections of custom blocks on my profile (I dont have this issue with the larger squares to type), the keyboard is not working.

**To Reproduce**
1. Try to type in the spots listed above with an ipad.

**Expected Behaviour**
Pressing keys will add letters in these spaces.

**Screenshots**
https://cdn.discordapp.com/attachments/618678242949464066/1197019075759575060/IMG_2209.png?ex=65b9bde3&is=65a748e3&hm=e3a098b87d738d30e820637087fd3344a214c69d9997754790d4af6508be8712&

**Note**
Sorry I dont know a better way to phrase it!

**Device**
- Type: iPad Pro
 - OS: 15.1
 - Browser: Safari  and Firefox
 - Version: Unsure

**Comment by boylett** [comment]
As with #343;

> I can't replicate this at all, no matter what I try.
> 
> I think the only way to really get to the bottom of this is if you plug your iPad into your computer and use a tool like [Inspect](https://inspect.dev) to observe the Console for warnings.

**Comment by crocojaws** [comment]
I downloaded inspect to my laptop and in the process of trying to get it to register that things were plugged in- I updated my ipad iOS from 15.1 to 17.3, so now it seems to be working fine!

**Comment by boylett** [comment]
Good to know! I think perhaps there are some aspects of Sheezy that don't work well with iOS 15. Will keep an eye on this going forward.
