### ISSUE TITLE
[BUG] Privated works showing in Trending carousel

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#328]
**Describe the Bug**
Privated pieces are showing up in the Trending carousel - I understand that no one else can see it, but even so, I'm fairly certain that private pieces shouldn't be showing up in Trending regardless

**To Reproduce**
1. Go to front page
2. View "Trending"
3. See error

**Expected Behaviour**
Private works should not be showing in Trending (I assume)

**Screenshots**
![2024-01-17 12_45_16-Sheezy Art – Main Page — Mozilla Firefox](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/90a40d4e-8042-4679-b41b-380cd8ed287c)

**Device**
-     Type: desktop
-     OS: windows
-     Browser: firefox
-     Version: Version 121.0 (64-bit)

**Comment by boylett** [comment]
Fixed by [#0401233](https://github.com/Sheezy-Art/sheezy.art/commit/04012335a5f9b4f88f0f9f9bd484e3ba7e9ab3d6)
