### ISSUE TITLE
[BUG] Sheezy.blog links on the site lead to undefined

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#329]
**Describe the Bug**
On the main page where you can see the two latest blogs, clicking either of the links lead to /undefined and gives an empty application error

**To Reproduce**
1. Go to the main Sheezy page
2. Click on one of the latest blogs (Not read more. That works fine)
3. See error

**Expected Behaviour**
The blogs to be linked correctly

**Screenshots**
N/A

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
Should be fixed now. Please feel free to reopen if not!
