### ISSUE TITLE
[BUG] Friends tab displaying relationships incorrectly

### ISSUE THREAD

**Issue by Sheishori** [Sheezy-Art/sheezy-hub#332]
**Describe the Bug**
Followers/following in the friends profile tab don't update the relationships (follow back/unfollow/mutuals/friends) when switching from one page to another.

**To Reproduce**
1. Go to the Friends tab on profile.
2. Click on Followers/following (make sure to have more than 1 page of people).
3. Switch from one page to another.
4. See relationships from the previous page.

**Expected Behaviour**
Labels should reflect correct relationship between users.

**Screenshots**
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/3387c228-0695-4795-b2e2-a6c39ff2a245)
![obraz](https://github.com/Sheezy-Art/sheezy-hub/assets/92861357/1d2b03a3-98d7-443e-bad4-3fdbbcef1018)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Google Chrome
 - Version: 120

**Comment by boylett** [comment]
Fixed by [#4d13941](https://github.com/Sheezy-Art/sheezy.art/commit/4d139416172a4e6dfeef7e5d8f50489674433bbd)
