### ISSUE TITLE
[BUG] Some profiles turn to 418 pages

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#333]
**Describe the Bug**
some profiles Are a 418 error page 

**To Reproduce**
1. Go to https://sheezy.dev/crocojaws
2. See error. 
(To way to getting to the page doesn’t seem to matter)

**Expected Behaviour**
The page works!

**Note:** 
- I tested out several of the staff profiles. Voxas, Ellteo, Missaroo, and Exlimixia.
- None of my personas are affected 

**Device**
- Type: iPad 
 - OS:
 - Browser: safari
 - Version:

**Comment by punkalope** [comment]
[Here's a video of it with the console as well! ](https://files.catbox.moe/cbahtg.mp4)

**Comment by willowbone** [comment]
my profile seems to be affected as well
https://sheezy.dev/willowbone

i similarly tried out some staff member profiles (ellteo and missaroo) and got the 418 error. it didn't matter how i tried to access the affected profiles, ie. through comments, posts, etc.

i'm on android using firefox (v121.1.0). turning off my add-ons and refreshing/restarting didn't change anything.

not sure if this helps at all but figured i'd comment just in case

**Comment by boylett** [comment]
Fixed by [#770b257](https://github.com/Sheezy-Art/sheezy.art/commit/770b2575eefeef83840f4d8f61fa26e24e7a5cce)
