### ISSUE TITLE
[BUG] Pagination buttons aren't fully themed on user profiles

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#334]
**Describe the Bug**
On user profiles, the new pagination numbers aren't themed to match the user theme on the gallery and jounral pages, and the floating popup only has the text and other button functions themed on the main user page (dissapearing when the button is pressed), and nothing themed on the side pages.

**To Reproduce**
1. Go to a user profile.
2. Go to their gallery/journals.
3. Note the colour of the pagination buttons.

**Expected Behaviour**
Pagination buttons are consistently themed.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/f474bd8d-fc64-472a-bfe9-0dd4fff8e430)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/590b8469-74e1-4ec5-b0ed-a3a473d60760)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/7bd9115e-6a8e-4786-9d8e-c8ec9ef049ad)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#7e50c4d](https://github.com/Sheezy-Art/sheezy.art/commit/7e50c4d7039dac964242254e98861a66bf40af3d)

**Comment by lumiscosity** [comment]
the popup menu still resets theming after clicking on a button and the theming is completely broken on the main user page

**Comment by boylett** [comment]
Fixed by [#22e122f](https://github.com/Sheezy-Art/sheezy.art/commit/22e122f73f2276b5880b8716c70ec9367672b91d)
