### ISSUE TITLE
[BUG] Artwork rated higher than General not showing up on profile 

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#335]
**Describe the Bug**
Artwork rated M or X do not show up on my profile/persona profiles. This includes custom gallery blocks, with and without tags. The artwork shows up in the gallery tab however. (I have my viewing preferences set to Explicit.)

**To Reproduce**
1. Go to a page with higher rated work. ( https://sheezy.dev/crocojaws/persona/twistedtattoo everything is rated M on this page, nothing is graphic.)
2. See error

**Expected Behaviour**
artwork would show on pages according to my viewing preferences

**Device**
- Type: iPad and android phone 
 - OS: [e.g. Windows, iOS]
 - Browser: safari and DuckDuckGo
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#8410428](https://github.com/Sheezy-Art/sheezy.art/commit/84104280b36e130f8754860169e297063a3f14fe)
