### ISSUE TITLE
[BUG] Comment toggle takes two clicks to start working

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#336]
**Describe the Bug**
The comment toggle seen on artworks and journals takes two clicks to start working.

**To Reproduce**
1. Go to an artwork or journal.
2. Click on the comment toggle multiple times.

**Expected Behaviour**
The comment toggle works on the first click.

**Screenshots**
![firefox_KkpesYi9cD](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/237d3460-3b8d-4d69-812a-24dd5a651b15)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#9f7eb32](https://github.com/Sheezy-Art/sheezy.art/commit/9f7eb324f84d23d9b7d207922a4ee3caf1c7abdd)
