### ISSUE TITLE
[BUG] Big empty space below profile block/custom content

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#337]
**Describe the Bug**
A big empty space appears under the profile block/custom block content.

**To Reproduce**
1. Go to any page with custom content/profile block with stuff in it
2. It's got a big empty space
3. It disappears if you zoom/in out of the page (like with ctrl + scrollwheel)

**Expected Behaviour**
no empty space :(

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/811b2096-772b-4cba-aa6c-eac105dbc44a)

**Device**
- Windows 10, Firefox 121.0.1 64-bit

**Comment by boylett** [comment]
Fixed by [#f374a96](https://github.com/Sheezy-Art/sheezy.art/commit/f374a96b0962ebc1de8a2923ce7e4bb4cea6469f)
