### ISSUE TITLE
[BUG] Youtube links in upload descriptions redirect incorrectly

### ISSUE THREAD

**Issue by exlimixia** [Sheezy-Art/sheezy-hub#338]
**Describe the Bug**
Using embedded hyperlinks to a youtube video in a post's description does not redirect correctly if the URL copied was from the video's URL bar and not Youtube's share button URL. 

If a user uses the video's URL bar link in their embedded hyperlink, the Sheezy redirect will bring the user to "https://www.youtube.com/watch" instead of the intended video.

Ex.
YT Links that redirect properly: https://youtu.be/dQw4w9WgXcQ?si=_4JxmpiIsiByyvat
YT Links that do NOT redirect properly: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**To Reproduce**
1. Go to upload a post (fill in the art and tags as you will)
2. Enter any text and embed a youtube link copied from the URL bar in said text. Ex. [I am an embedded hyperlink] (https://www.youtube.com/watch?v=dQw4w9WgXcQ)
3. Post the upload and view it. Click on the link.
4. See that you have been redirected to "https://www.youtube.com/watch" instead of the intended video.

**Expected Behaviour**
I expect youtube links to redirect properly, whether copied from the URL bar or from Youtube's direct sharing link.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/147447596/5a0f68f6-055d-4770-b988-5a2b1cf947c9)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/147447596/bbb518da-65b0-4970-b717-13f98a529620)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/147447596/d752349c-4b4b-4b2d-b258-e2a087716881)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/147447596/f92e832e-14a2-4983-b665-fb55d176ce93)

**Device**
- Type: Desktop PC
 - OS: Windows 11
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
Should be fixed now! [#e388a02](https://github.com/Sheezy-Art/sheezy.art/commit/e388a02577a695448952e1a724f6f6e02ceb2c33)
