### ISSUE TITLE
[BUG] Cannot upload .tga or .psd files

### ISSUE THREAD

**Issue by boylett** [Sheezy-Art/sheezy-hub#340]
**Describe the Bug**
There are likely more.

Unsupported image files should simply be rejected, but instead display a 'Missing Image' graphic in the cropper.

**Comment by lumiscosity** [comment]
i've tested a few more (everything you can export out of paint.net and krita at least)
- bmp fails to upload citing an invalid size
- mp2 uploads, but netiher firefox or chrome can play it

**Comment by boylett** [comment]
Fixed by [#d75cbed](https://github.com/Sheezy-Art/sheezy.art/commit/d75cbed829c13077956fb7616d4397c094efff96)
