### ISSUE TITLE
[BUG] Drafted art will steal the thumbnails of previous drafts & delete description + tags.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#341]
**Describe the Bug**
When uploading multiple pieces of art, if you delete one of the uploads the previous upload will steal the thumbnail. You will also lose the description and tags you had written.

**To Reproduce**
1. Upload multiple pieces of artwork. In this case I was uploading 4.
2. Edit and save three.
3. Delete the fourth.
4. Notice the thumbnail change and sudden lack of description and tags.

**Expected Behaviour**
My other drafts shouldn't be affected when I delete one.

**Screenshots**
Sorry for gif crunchiness.
![firefox_uCBmE6dgan](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/9c0d864d-777f-4267-8ddb-45d82b3d4d20)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#d75cbed](https://github.com/Sheezy-Art/sheezy.art/commit/d75cbed829c13077956fb7616d4397c094efff96)
