### ISSUE TITLE
[BUG] journals are a 418 error for me :(

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#343]
**Describe the Bug**
Clicking  on journal tabs, directly on journal links and the journal tab in the admin panel gives me a 418 page :(.. again 
I do not have this issue with my phone.

**To Reproduce**
1. Go to main page with an iPad
2. Click on a journal
3. See error

**Expected Behaviour**
for it to load !

**Device**
- Type: iPad Pro
 - OS: iOS 15.1
 - Browser: safari and Firefox
 - Version: up to date

**Comment by boylett** [comment]
I can't replicate this at all, no matter what I try.

I think the only way to really get to the bottom of this is if you plug your iPad into your computer and use a tool like [Inspect](https://inspect.dev) to observe the Console for warnings.
