### ISSUE TITLE
[BUG] Journal post attributes extend off of screen

### ISSUE THREAD

**Issue by hasnogame** [Sheezy-Art/sheezy-hub#344]
**Describe the Bug**
When making a journal post if one uses a lot of attributes the attributes will continue off of the screen instead of wrapping to the next line.

**To Reproduce**
1. Create a new journal
2. Add attributes to the post:
    1. (Desktop) Add 11+ attributes
    2. (Mobile) Add 4+ attributes 
4. Post the journal and view it

**Expected Behaviour**
Attributes should wrap rather than continue rendering on the same line.

**Screenshots**
Desktop:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/5c316793-935a-46ed-ad11-52b741c0f5e3)
Mobile (Landscape orientation):
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/42306887/6de40bba-c4b5-4b9e-86a5-b1453dcfc30e)

**Device**
- Type: Desktop/Mobile
 - OS: Windows 10/Android
 - Browser: Firefox, Firefox Mobile
 - Version:
     - Desktop: 121.0.1
     - Mobile: 121.1.0

**Comment by boylett** [comment]
Fixed by [#ee8c3e6](https://github.com/Sheezy-Art/sheezy.art/commit/ee8c3e691223f86adef562345db570a9b7dc6d4b)
