### ISSUE TITLE
[BUG] Profile Block Preview is different than actual result

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#345]
**Describe the Bug**
The CSS preview for 

**To Reproduce**
1. Make some CSS for your profile block
2. preview it
3. compare it to its saved results on your profile page
4. 

**Expected Behaviour**
The preview is double spaced for some reason when the actual result is not; as well, links have a little icon next to them and become underlined when hovered over when the resulting CSS does not.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/e319eaf8-896e-4c48-8abc-a6931c5ed09b)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/3217ef37-1546-4a16-91a4-cb0ba421f0aa)

**Device**
Windows 10, Firefox 121.0.1 64-bit

**Comment by boylett** [comment]
Fixed [#9131bab](https://github.com/Sheezy-Art/sheezy.art/commit/9131baba4dd158e8bceb3d805c9bc601538497ae)
