### ISSUE TITLE
[BUG] Certain images on mobile are made smaller after clicking on the zoom

### ISSUE THREAD

**Issue by KALECHEEPS** [Sheezy-Art/sheezy-hub#347]
**Describe the Bug**
When on mobile and viewing artworks that span the full width of the screen, clicking on the zoom button makes them slightly smaller.

**To Reproduce**
1. Go to sheezy.dev on mobile
2. Find an artwork that when viewed, is the full width of the screen
3. Click on the zoom button
4. See error, image will shrink

**Expected Behaviour**
I would expect images to either zoom in or stay the same size and not shrink

**Screenshots**
Before clicking zoom
![zoom1](https://github.com/Sheezy-Art/sheezy-hub/assets/155499119/18d11b83-37c2-4a16-b795-99beef2982c2)
After clicking zoom a margin appears around the image, making it shrink slightly
![zoom2](https://github.com/Sheezy-Art/sheezy-hub/assets/155499119/45c280a0-fe11-4245-845d-e6642da158d5)

**Device**
- Type: iPhone
 - OS: iOS
 - Browser: Safari
 - Version: 17.1.2

**Comment by boylett** [comment]
Fixed by [#6213215](https://github.com/Sheezy-Art/sheezy.art/commit/621321582db3764211b04a7ba872a2d455a081a8)
