### ISSUE TITLE
[BUG] Ids in custom content profile blocks do not work as links to content on the same page, instead linking to the front page

### ISSUE THREAD

**Issue by KALECHEEPS** [Sheezy-Art/sheezy-hub#348]
**Describe the Bug**
When attempting to use ID's in a profile's custom content block, they cannot be properly used as links. When they are clicked on they send you to the front page, with it's URL being "https://sheezy.dev/#whatever-the-id-linked-is"

I actually suspect this is at least partially intended and the result of the most recent changes to custom content blocks, because this worked for me before they where changed.

**To Reproduce**
1. Go to a profile or persona with custom content blocks that uses Id's as links
2. Click on a link using an Id
3. See error, be sent to the front page

**Expected Behaviour**
I would expect the link to scroll to the id's location on the current page, instead of sending me to the front page.

**Screenshots**
Example of this using the [persona ](https://sheezy.dev/kalecheeps/persona/unfundamental) i'm testing this on, which im linking in case that's a useful thing to do

This is using "#unfunInt" for it's link
![ID1](https://github.com/Sheezy-Art/sheezy-hub/assets/155499119/4bd2ab1c-085d-47ab-9b06-f06ea56c2fab)

When clicking on it i should be sent here
![ID4](https://github.com/Sheezy-Art/sheezy-hub/assets/155499119/4fa04aae-5323-40d0-a51b-58ad7707535c)

Instead i get sent to front page
![ID3](https://github.com/Sheezy-Art/sheezy-hub/assets/155499119/8bb70c0b-4a0f-4b65-86f8-b96d16303e37)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Firefox
 - Version: 121.0

**Comment by boylett** [comment]
Fixed by [#d75cbed](https://github.com/Sheezy-Art/sheezy.art/commit/d75cbed829c13077956fb7616d4397c094efff96)
