### ISSUE TITLE
[BUG] Artwork Upload Limit Incorrect

### ISSUE THREAD

**Issue by heliumcircus** [Sheezy-Art/sheezy-hub#349]
**Describe the Bug**
Despite having a basic subscription, the artwork upload limit is 5 rather than 10.

**To Reproduce**
1. Have a basic subscription active on account
2. Go to 'Upload Artwork'
3. See text "You have uploaded 0 of your allotted 5 artworks for the last 24 hours"
4. Upload 5 artworks
5. Face inability to upload any more artworks

**Expected Behaviour**
The text on the upload page says allotted 10 artworks, and I can upload up to 10 artworks.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157544804/7decbf6c-3558-422f-a4b4-cb6cd57ecc86)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157544804/49504f74-3bbd-4bb5-8790-d3b647953a98)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Google Chrome
 - Version: 120.0.6099.225 (Official Build) (64-bit)

**Comment by boylett** [comment]
Fixed by [#ad3397f](https://github.com/Sheezy-Art/sheezy.art/commit/ad3397f3363ed8f5ace04099c26a8d720deb331a)
