### ISSUE TITLE
[BUG] journal stretching mobile front page .

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#350]
**Describe the Bug**
if a journal is made of one really really really long word (perhaps the length of a novel with no spaces) in the description, it stretches the mobile front page horizontally.

**To Reproduce**
1. Follow someone with an extremely long recent journal 
2. Go to the front page on your phone 
3. Scroll to the right 

**Expected Behaviour**
The page would stay the same size and the text would be cropped off

**Screenshots**
https://discord.com/channels/1143702362091966654/1191539111987777547/1201026921463554108

**Device**
- Type: android 
 - OS: 
 - Browser: duckduckgo
 - Version:

**Comment by boylett** [comment]
Fixed by [#87ad4aa](https://github.com/Sheezy-Art/sheezy.art/commit/87ad4aa08f2d14c4dcc5aa66b2254856b89c7363)
