### ISSUE TITLE
[BUG] CSS Animations do not function

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#351]
**Describe the Bug**
Using CSS animations with <style> in HTML supported blocks do not work.

**To Reproduce**
- Create a Custom Content block or any other block
- Use <style> and add some CSS animation code with `@keyframes` and the `animation` properties
- Animation does not work

**Expected Behaviour**
CSS animations function

**Screenshots**
Block on Profile (no animation)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/36ccef4f-cdb6-4785-b79b-b94e02f17080)

The code
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/335d50fa-4f0b-48c3-8ca1-ef74aae0a879)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/97423420-55a0-4c6e-b0b8-3b63b57a7174)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 1.22.0

**Comment by betalambda** [comment]
noticed an error in my code, but even after correcting it, it still doesn't work
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/79066845-783c-4f59-b35d-8f8fd7746476)

**Comment by boylett** [comment]
Try changing the keyframes to the following:
```@keyframes marker {
  0% { background-color: transparent; }
  50% { background-color: #FFFFFF; }
  100% { background-color: transparent; }
}```

Also, for future reference, custom HTML issues should ideally be posted to the **#html-workshop** channel in our Discord server. The GitHub is for site-specific issues :)
