### ISSUE TITLE
[BUG] Browse leads to a 418 error

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#352]
**Describe the Bug**
Trying to access browse or https://sheezy.dev/browse will result in a 418 error

**To Reproduce**
- Click on "Browse" or navigate to https://sheezy.dev/browse
- Sheemz ate the browse function ☹

**Expected Behaviour**
Browse redirects me to, well, browse.

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 1.22.0

**Comment by betalambda** [comment]
https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/995115c9-be2a-4e7f-97e6-4566288b0137

**Comment by boylett** [comment]
Should be fixed now
