### ISSUE TITLE
[BUG] Page numbers and infinite are nowhere to be seen

### ISSUE THREAD

**Issue by OmiChu** [Sheezy-Art/sheezy-hub#353]
**Describe the Bug**
The page numbers and infinite are no where to be seen.

**To Reproduce**

Click on "Browse" or navigate to https://sheezy.dev/browse

**Expected Behaviour**
Page numbers and infinite should be listed underneath the rows of artwork thumbnails.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/4edfab8b-68c7-4443-b43f-f16ccf218594)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Should be fixed now!
