### ISSUE TITLE
[BUG] Unable to upload larger .GIF file, results in server error

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#354]
**Describe the Bug**
When uploading a somewhat large .GIF file (4.41 MB, at 1786 x 687 pixels) file will upload for a fluctuating amount of time before throwing a server error dialogue box, and failing to upload the file. Smaller .GIF files up to about 1.5-ish MB will successfully upload, but anything over that seems to have an issue.

**To Reproduce**
1. Go to Upload Artwork
2. Click on the artwork uploading box
3. Choose a .GIF file with a somewhat large file size (3MB+?)
4. Wait for .GIF file to upload for a varied amount of time
5. After that varied amount of time, website throws a server error and fails to upload

**Expected Behaviour**
Larger .GIF files that are still under the maximum file size limit will upload.

**Screenshots**
![10](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/2e246541-9885-4999-b325-5a765841ab47)

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#3a93ba9](https://github.com/Sheezy-Art/sheezy.art/commit/3a93ba960d362e383f5841a2b61bbb669d67a72b)
