### ISSUE TITLE
[BUG] Sheezy links (e.g., to Gallery or to a Persona) read as external links, result in loading screen

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#355]
**Describe the Bug**
When linking a URL to another area of the Sheezy site, such as the Gallery or a Persona page, instead of transitioning from one page to another smoothly the user is first booted to a loading screen for external links. This seems to be due to an additional URL "/url/" string being added to anything registered as a link, even if it's still within the website.

**To Reproduce**
1. Copy any URL address within the Sheezy site, such as your Gallery page, from the URL bar
2. Go into Edit Profile
3. Navigate to any HTML block and add the link using "a href" code block, and add the Sheezy link
4. Save, and exit out of Edit Profile
5. Click the link you just added (note the "/url/" string addition in the full URL, shown at the lower left edge of the screen)
6. Get redirected to the external link loading screen
7. Get redirected again from the loading screen to the proper Sheezy page

**Expected Behaviour**
Clicking a Sheezy link will smoothly transition to a Sheezy page without being booted to the external link loading page.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/11796403-6425-4a08-99f3-f23bd17af94a)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/82677c6f-5a23-44c9-8972-0c412e542469)

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
Fixed by [#3c9c51e](https://github.com/Sheezy-Art/sheezy.art/commit/3c9c51e335ee9d9c366f6e995d3c2541a4dd6c32)
