### ISSUE TITLE
[BUG] Profile info blocks not saving headings or justify

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#359]
**Describe the Bug**
When editing an info block in markdown mode, they don't save heading or justify markdowns.

**To Reproduce**
1. Edit profile information block in markdown mode.
2. Create a heading and center it.
3. Save.

**Expected Behaviour**
Justify & heading should work when saving.

**Screenshots**
https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/60cd8284-fdfa-48c7-9c1c-194db64c09d3

**Device**
- Type: Desktop PC
 - Browser: Firefox

**Comment by boylett** [comment]
Fixed by [#975876c](https://github.com/Sheezy-Art/sheezy.art/commit/975876c936907d52d280587c25f4fc048b42b8de)

**Comment by meatsfunk** [comment]
https://github.com/Sheezy-Art/sheezy-hub/assets/158455832/60403f6b-a24f-45b0-abd2-9efb5a4c6f16

**Comment by boylett** [comment]
Fixed [#36a6e5c](https://github.com/Sheezy-Art/sheezy.art/commit/36a6e5ce0b8f53671b30d9786dcdf182b5ae5139)

**Comment by punkalope** [comment]
Appears to still be happening!
