### ISSUE TITLE
[BUG] Awards Inventory Details displays innacurate awards remaining

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#361]
**Describe the Bug**
The "details" popup on the Awards Inventory page doesn't match the numbers remaining on the main page

**To Reproduce**
1. Go to "Awards Inventory"
2. Click on 'Details
3. See if the number matches 

**Expected Behaviour**
They'd be the same on both pages (see screencap)

**Screenshots**
![Screen Shot 2024-01-31 at 1 44 26 AM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/80c788f8-96e9-4f4d-b2fa-5b47d66ee6cf)
![Screen Shot 2024-01-31 at 1 44 31 AM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/d481b802-0a38-46ef-9c80-250f945c2200)

**Device**
- Type: Laptop
 - OS: [e.g. Windows, iOS]
 - Browser: Firefox
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#b181dac](https://github.com/Sheezy-Art/sheezy.art/commit/b181dac9243f5cf06373e46ff4974622ebdd3d2f)
