### ISSUE TITLE
[BUG] Feed Like highlight doesn't work

### ISSUE THREAD

**Issue by meatsfunk** [Sheezy-Art/sheezy-hub#362]
**Describe the Bug**
When scrolling the feed, your likes on posts you've already liked are not visible until you press or highlight the button again.

**To Reproduce**
1. Go to your feed
2. Find a post you've previously liked
3. Like button is not highlighted until it is moused over

**Expected Behaviour**
The Like button should be highlighted to show that the post has already been liked.

**Screenshots**
https://github.com/Sheezy-Art/sheezy-hub/assets/158455832/ca185068-7d8b-42b9-b61d-aa9d29d17d3c
Screen recording of bug is above

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#9ecddd3](https://github.com/Sheezy-Art/sheezy.art/commit/9ecddd38725a1a16d5d3ea9fbc4b2ccb54898c5f)
