### ISSUE TITLE
[BUG] Basic Subscription buttons not working.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#363]
**Describe the Bug**
On the subscribe page, the buttons linking to sub/donate do not work under the basic subscription box.

**To Reproduce**
1. Go to the subscription page.
2. Try to click any of the buttons underneath the basic tier.
3. See nothing.

**Expected Behaviour**
They should link to the donation/subscription pages when clicked.

**Screenshots**
![3oWsTFxxxV](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/c1daa5be-f377-497e-a5b0-55e586d42c84)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#0441e53](https://github.com/Sheezy-Art/sheezy.art/commit/0441e532fe7b74679a9ab1b51aa45066d10a241d)
