### ISSUE TITLE
[BUG] Adding or editing feeds causes them to break

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#364]
**Describe the Bug**
Adding or editing feeds causes them to break, making them not display anything and dissapear off of the sidebar (this means new feeds do not appear there either). Manually going to the pages of these feeds does work, but the edit button takes you to the first feed off the top, and the refresh button does nothing. Once all feeds are gone, a glithed empty feed is shown with an adress at the /feed root, where editing it does nothing and refreshing it causes a 405 error.

**To Reproduce**
1. Go to your feeds.
2. Add or edit a feed.
3. Note how it's missing in the side bar.
4. Go to the feed's page and try to edit it.

**Expected Behaviour**
Feeds can be added and edited normally and display content.

**Screenshots**
![firefox_r1877FTTYE](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/a96dc9bf-4249-49b6-a35c-42af61f5019d)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#f0ee710](https://github.com/Sheezy-Art/sheezy.art/commit/f0ee7109d12a666f4cb07e8cec5515c894caad15)
