### ISSUE TITLE
[BUG] Following pinboard links to Sheezy pages causes a 418 error

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#365]
**Describe the Bug**
Following pinboard links to any page on sheezy.art causes a 418 error.

**To Reproduce**
1. Put a link on a pinboard pin.
2. Save the pinboard
3. Click on the pin.

**Expected Behaviour**
Links take you to the desired page as expected.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/ac55aafc-4509-436e-8371-47a0a0d1b7ce)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#a12a46e](https://github.com/Sheezy-Art/sheezy.art/commit/a12a46e4bc3c1c6044708f3bcf7fe1ee088b131c)
