### ISSUE TITLE
[BUG] 405 when refreshing feed

### ISSUE THREAD

**Issue by OmiChu** [Sheezy-Art/sheezy-hub#366]
**Describe the Bug**
Gets an error 405, when clicking the refresh feed button.

**To Reproduce**
1. Go to "My Feed"
2. Click on "Refresh Feed"
3. Error 405

**Expected Behaviour**
Refresh feed should refresh the page

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/2685a09b-1a13-4901-a413-bb481c4d4388)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0

**Comment by lumiscosity** [comment]
this seems to happen when the page in the browser bar is just sheezy.art/feed. with any feed properly open, this does not happen
