### ISSUE TITLE
[BUG] "You're at the top" bar still appears when no feed is loaded

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#368]
**Describe the Bug**
If you remove all of your feeds, going to the feed page will show a supposedly empty glitched feed. The "You're on the top" bar appears, but the edit button does nothing and the reload button causes a 405 error.

**To Reproduce**
1. Go to your feeds.
2. Remove all feeds.
3. Note the "You're at the top" bar still being there.

**Expected Behaviour**
The "You're at the top" bar dissapears when no feed is available.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/766fe1d3-1b48-40b7-bfb1-b0bcb4972ce4)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#357dcdf](https://github.com/Sheezy-Art/sheezy.art/commit/357dcdfdc6fe04349623122b88924d188cd4dea4)
