### ISSUE TITLE
[BUG] Remove follower doesn't acually remove a follower

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#369]
**Describe the Bug**
When removing a follower via the friends tab, the user that has been removed still sees themselves as following the original user. On the side of the original user, the removed follower is, correctly, not following them. In order to clear this, the removed follower has to unfollow the original user on their own end, in which case the unfollow is then registered. Removed followers can still send friend requests, which can be accepted even though they aren't mutuals.

I tested this out with one of my pals, just to be sure, as we were struggling with the following option not reflecting our following statuses properly. This was especially evident when they were removed from my following list to try and fix the problem - but were still able to send a friend request, as they were still showing up as following me (thus being mutuals) on their end. This being the case, it's possible that follower removals are not actually being reflected properly between user relationships.

**To Reproduce**
1. Go to the Friends tab
2. Click on any mutual follower, remove them from your following list
3. Other user goes to your profile
4. Other user still sees 'Following' and is able to send friend requests
5. The following status on your end shows them not following you (reflected with follower count) and shows them as following on their end
6. Friend requests can be accepted with the non-mutual followers from the Notifications page

**Expected Behaviour**
Removing a follower removes their follow from you, which is reflected on both sides. Removed followers can't send friend requests.

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0.1

**Comment by boylett** [comment]
This is intended behaviour. When you remove someone as a follower, the person who followed you should not know anything has happened – this prevents followspam harassment

**Comment by boylett** [comment]
Despite my previous answer, I have adjusted the behaviour with [#cb11928](https://github.com/Sheezy-Art/sheezy.art/commit/cb119280e5e5d70350baee5fdecf742f4ad57555). Please let me know if it is more in line with expectations.
