### ISSUE TITLE
[BUG] Editing an artwork goes to the wrong page

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#370]
**Describe the Bug**
Going on an artwork page and clicking the "Edit" button takes you to `https://sheezy.art/upload/<id>` instead of `https://sheezy.art/upload/artwork/<id>`. You have to manually click on the artwork to edit it.

**To Reproduce**
1. Go to an artwork page
2. Click on "Edit"
3. See as it takes you to the wrong page

**Expected Behaviour**
The right page is opened.

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Thanks for the report! Fixed by [#8e5f8d1](https://github.com/Sheezy-Art/sheezy.art/commit/8e5f8d1403fe3c09f959e01d1a9986d43876040d)
