### ISSUE TITLE
Unable to link patreon and sheezy account

### ISSUE THREAD

**Issue by cablll** [Sheezy-Art/sheezy-hub#371]
**Describe the Bug**
When attempting to link my patreon account to sheezy instead of getting redirected to whatever site you use to link accounts i get redirected to 
https://www.patreon.com/oauth2/errors?error=invalid_request&error_description=Mismatching+redirect+URI.&state=616c9f36e9da58952b000403

**To Reproduce**
1. go to account settings 
2. go to intigration
3. go to patreon
4. click on connect with patreon

**Expected Behaviour**
link to the patreon authentication site, and be able to link accounts

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/111040151/83e4e7e4-44bf-4cf3-89b1-596edb5d4b8e)

**Device**
Desktop, vivaldi, windows

**Comment by boylett** [comment]
Please give this another try – should be fixed now! If not, please comment here and I'll reopen.
