### ISSUE TITLE
[BUG] new art isnt being updated when logged in or signed out

### ISSUE THREAD

**Issue by Uukipi** [Sheezy-Art/sheezy-hub#373]
**Describe the Bug**
When signed in and also signed out i cant see newest posted art.Its stuck on a certain amount thats been posted hours ago. Theres no error
ive cleared cookies and cache as well!

**To Reproduce**
1. Go to browse
2. Click on hit sort by newest at top

**Expected Behaviour**
see new art when updated

**Screenshots**
signed out
[If applicable, add screenshots to help explain your problem.](https://media.discordapp.net/attachments/1191539111987777547/1202718299771637841/image.png?ex=65ce79b4&is=65bc04b4&hm=f571cd74fbbba776278376c859447e03e556502a6e3c41fa947f3c1397587e4a&=&format=webp&quality=lossless)
signed in
https://media.discordapp.net/attachments/1191539111987777547/1202718300732399686/image.png?ex=65ce79b4&is=65bc04b4&hm=d2b043e4c350b5270d63f5e3d33afcb771248d17f5ba37201114d548a17dfa6f&=&format=webp&quality=lossless

**Device**
- Type: desktop
 - OS: windows
 - Browser: firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
The content you see when logged in will be different to what you see when logged out as when logged out, the site assumes the viewer can only view artwork rated 'General'.

Additionally, each gallery has its own "cache" – it is essentially frozen in place for a set amount of time to allow the moderators time to get through the most recent artworks.

This is a feature! :)
