### ISSUE TITLE
[BUG] Mysterious Mod Queue Number 

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#374]
**Describe the Bug**
Theres a Mysterious number in the moderators Artwork Queue. (I believe it may be staff pieces that bypass the queue). And it goes up when one of us post a piece.

**To Reproduce**
1. Go to the admin panel
2. Click on "Artworks"
3. See what the number is (it is over 400 for most of us)

**Expected Behaviour**
The number would be smaller to reflect what is actually in the queue

**Screenshots**
![Screen Shot 2024-02-01 at 11 44 55 AM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/7956da18-965f-4b79-9fd3-2ca392809d2a)

**Note**
I do not believe this is the amount that I have "passed" or pieces that I have tags/users blocked for, as other moderators have a similarly high number.

**Device**
- Type: Laptop
 - OS: [e.g. Windows, iOS]
 - Browser: Firefox
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#bf941edd](https://github.com/Sheezy-Art/sheezy.art/commit/bf941eddb8febc623a07000ae88bdff3c5aa904c)
