### ISSUE TITLE
[BUG] Follow, Friend, ect Button forever loading

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#376]
**Describe the Bug**
The Follow button or whatever it's suppose to be is stuck loading or stuck loading once it's clicked

**To Reproduce**
1. Go to Anyone's profile or artwork (Also happens when you see the button through notifs, but it has to be clicked)
2. Look at where the Follow/Friend/Ect button is
3. It's forever loading

**Expected Behaviour**
The button not to be stuck on forever loading

**Screenshots**

https://github.com/Sheezy-Art/sheezy-hub/assets/153317217/5b6725da-0e3b-4ffb-98db-e06fe16caff1

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
This is caused by a CORS mismatch between **www.sheezy.art** and **sheezy.art** – I have instigated a permanent 301 redirect from **www.** so this should not happen anymore.
