### ISSUE TITLE
[BUG] Opening Award from Profile "in new tab" Downloads bg image to my computer

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#377]
**Describe the Bug**
Right clicking "open in new tab" on an award takes me to a blank tab and also downloads a copy of my background image but as a text file.

**To Reproduce**
1. Go to your 
2. right click an award "open in new tab"
3. Takes you to a blank page, downloads an image in this case, my own background. 

**Expected Behaviour**
Nothing would be downloaded.

**Screenshots** Possible Trypophobia warning on third image!
![Screen Shot 2024-02-01 at 3 37 35 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/5d1e5998-1c3a-4229-9a1d-d23801cb26f0)
![Screen Shot 2024-02-01 at 3 37 46 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/506ec373-46ff-41f3-a1f8-7de29708304a)
Downloaded file:
![Screen Shot 2024-02-01 at 3 52 00 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/52384dd9-c638-4cf1-901b-212289cf40d7)

**Note**
It shows up as a blank tab on my OWN profile
But when i try it on someone elses it just shows THEIR background image/doesnt download anything.

**Device**
- Type: Laptop
 - OS: iOS 15.1
 - Browser: Firefox
 - Version: Up to date

**Comment by boylett** [comment]
Award images are copy-protected, so you cannot open their images - if you're meaning to open the Award's page, they are not quite implemented yet.

**Comment by crocojaws** [comment]
Makes sense! I was trying to grab one just to slap as a censor on the other bug i posted.

Though i guess my issue here is that it went straight to downloading my background that part I am unsure of.

**Comment by boylett** [comment]
Aye that's an issue with old files. If you re-upload the file it should stop doing it :)
