### ISSUE TITLE
[BUG] Blurred Mature/Explicit Uploads Are Not Viewable

### ISSUE THREAD

**Issue by kushbreth** [Sheezy-Art/sheezy-hub#379]
**Describe the Bug**
When account preferences are set to Blur all Mature and Explicit content, the "click to view" function does not work, whether you are browsing/looking at feed/looking directly at a piece. Basically, if the setting is enabled, anything labeled mature or explicit are completely unable to be viewed 

**To Reproduce**
1. Go to any mature or explicit work through browsing or through feed
2. Click on "click to view"

**Expected Behaviour**
The "click to view" button should un-blur the work, but it does not

**Screenshots**
Screenshots attached are of images that have been clicked multiple times
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/8e381130-b180-45d8-8625-75c60e4d8ae4)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/155499319/311a12a5-df6c-4171-b0dc-063ca35d6203)

**Device**
Type: desktop
OS: windows
Browser: firefox
Version: Version 121.0 (64-bit)

**Comment by boylett** [comment]
Fixed by [#c4a6821](https://github.com/Sheezy-Art/sheezy.art/commit/c4a6821ddf200762123a9e4e24e382182752e72a)
