### ISSUE TITLE
[BUG] Uploading Large(?) file to pinboard breaks

### ISSUE THREAD

**Issue by Missaroo** [Sheezy-Art/sheezy-hub#38]
**Describe the Bug**
Uploading large(2.92 MB or 6342x5662 pixels) Image to Pin Board brings up the "Uploading file" loading pop up forever

**To Reproduce**
1. Go to Profile
2. Click on Edit Profile
3. Scroll down to Pinboard
4. Upload image (This was the one i used https://clipart-library.com/clip-art/transparent-hearts-8.htm )

**Expected Behaviour**
I think either it would upload or say the image size is too big? 

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153320424/80370394-97a5-4aa4-ae3d-a99e5cde3d21)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Opera GX
 - Version: LVL5 (core: 104.0.4944.85)

**Comment by boylett** [comment]
Have modified server config to allow larger file uploads. Please try again and let me know the result!

**Comment by boylett** [comment]
Confirmed fixed.
