### ISSUE TITLE
[BUG] long "Links" in desc stretch screen horizontally on mobile

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#380]
**Describe the Bug**
Links or long strings of characters with no space breaks in between in image descriptions on mobile stretch the page horizontally.

**To Reproduce**
1. Go to a piece with a long link in the description. [this is the one in my screencap.](https://sheezy.art/papersquid26/gallery/cherry)
2. Scroll down to desc
3. See Error

**Expected Behaviour**
The text wraps down to fit the size of the description box

**Screenshots**
https://cdn.discordapp.com/attachments/618678242949464066/1203239284866285598/Screenshot_20240203_011613_DuckDuckGo.jpg?ex=65d05ee8&is=65bde9e8&hm=0d714da30f1124180de13f3e94d88ef7b5e3a75f5bd6d6767042be63a74b2404&

**Device**
- Type: Android
 - OS: [e.g. Windows, iOS]
 - Browser: DuckDuckGo
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#cf4eb85](https://github.com/Sheezy-Art/sheezy.art/commit/cf4eb85afbc25eac73fc4bf4cddb22d6b613a2e6)
