### ISSUE TITLE
[BUG] Custom Gallery blocks on mobile do not reflect row/column settings

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#381]
**Describe the Bug**
Looking at gallery blocks on mobile, the rows and columns do not reflect whats been assigned. 
The amount of pieces showing DOES however.

**To Reproduce**
1. Set a gallery block to 2 columns, 2 rows, with a tag that would pull more than 4 items
2. Save and check profile
3. See error

**Expected Behaviour**
it would be 2x2 instead of laid out like 2x3

**Screenshots**
**1**- https://cdn.discordapp.com/attachments/618678242949464066/1203239360632193104/Screenshot_20240202_135721_DuckDuckGo.jpg?ex=65d05efa&is=65bde9fa&hm=32ba12bc1b715b85e1ba60e2d6c9482fd75bc26a687329dbd78ca2436f0eb73d&
**2**- https://cdn.discordapp.com/attachments/618678242949464066/1203239360313692180/Screenshot_20240202_135705_DuckDuckGo.jpg?ex=65d05efa&is=65bde9fa&hm=4874fbe5799ac4fb57814567c6dc21ee76c75a6066bec2a7dc1797782f4d6dac&

**Device**
- Type: Android
 - OS: [e.g. Windows, iOS]
 - Browser: DuckDuckGo
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#294a580](https://github.com/Sheezy-Art/sheezy.art/commit/294a580b45dcf98dc06560e5a7c2c2ff26e85e03)
