### ISSUE TITLE
[BUG] Explicit Category defined as "mature" instead of "explicit" in content specifications.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#386]
**Describe the Bug**
When changing content settings, the explicit tier is described the same as the mature tier ("Your profile will only be visible to mature audiences"), not matching the description used under maturity settings ("You can view content containing explicit themes")

**To Reproduce**
1. Go to settings.
2. Scroll down to content specifications.
3. See mature and explicit match descriptions.
4. Go to content settings.
5. See maturity settings do not match.

**Expected Behaviour**
The descriptions for tiers should be consistent between settings.

**Screenshots**
*Maturity Settings*
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/e7889bed-5280-4988-8f91-58bd92cf0e11)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/8fb6975b-c293-412f-8ae2-f9360dff9161)
*Content specifications*
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/e9f893cd-72f5-4ccd-83e3-59d7c9a5beb1)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/459c1a91-abd0-41da-9e4b-64591cb922c5)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122

**Comment by boylett** [comment]
Fixed by [#4a9cdc0](https://github.com/Sheezy-Art/sheezy.art/commit/4a9cdc08492f2825ecdbbba5fc6ce659a81d85ce)
