### ISSUE TITLE
[BUG] Dark mode not fully applying to feed page

### ISSUE THREAD

**Issue by AstralBlossoms** [Sheezy-Art/sheezy-hub#387]
**Describe the Bug**

**To Reproduce**
1. Have your browser or system be in dark mode
2. Be on Sheezy
3. Go to feed
4. ![image_2024-02-04_174807086](https://github.com/Sheezy-Art/sheezy-hub/assets/53927876/234d9a7c-4002-4b25-b7c4-c6c4e4a7a390)

**Expected Behaviour**
dark mode should be applied to all sections of the food

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Opera GX

**Comment by OmiChu** [comment]
Same goes with the profile editor tool
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/af584ec2-7979-467c-8476-5c3f670e57e2)

**Comment by AstralBlossoms** [comment]
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/53927876/8721e1e7-b9c8-469e-9769-b32310fa50d8)
Comment section too on art is not in dark mode

**Comment by OmiChu** [comment]
The drop down menus are effected as well
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/2f3cfc24-7bdc-47ce-8750-7589940fb961)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/bc5d3d1d-c2a1-4163-b61a-b6157dd6458f)

**Comment by AstralBlossoms** [comment]
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/53927876/2ca7f223-e45a-457f-9ecf-c615f53dd598)

found another on an empty profile!

**Comment by Proxybat** [comment]
# The following don't have any dark themed css applied to them:

- The comments section. Both on the default user profile styling and on art posts. (Both input field and posted comments.)
- Button confirming the user is over 18 in the maturity settings.
- The thumbnail background in "Artwork details."
- The default thumbnail for literature in "Artwork details."
- Like others have said, a large majority of input fields and dropdowns.
- The list of other users that liked the post, that pops up when hovering over the like button.
- More of a nitpick if anything. In the investor section of the subscribe page the border colors of the "8 pinboard blocks."

**Oh yeah btw I'm very sorry for the large screenshots I literally don't know how to change the image size with markdown.**

## Screenshots below:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/54f1a3d9-b229-4554-bead-3d4a3859d797)
![Screenshot 2024-02-04 at 22-26-26 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/474946c2-7093-400f-a9ad-3449a0a785df)
![Screenshot 2024-02-04 at 22-53-26 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/ff2861d2-ed76-43c8-ab9a-003c9b0844d1)
![Screenshot 2024-02-04 at 22-30-23 Sheezy Art – Deer guy by @Tesspy](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/f5bfaeee-733c-4544-a785-1c11a00f62a8)
![Screenshot 2024-02-04 at 22-54-26 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/7fe43aac-2bfe-4c3d-9e07-38ab0e6cbcb4)
![Screenshot 2024-02-04 at 22-55-08 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/618b25ef-ce83-41de-ad4b-1d950898d41b)

![like-button-list](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/facd935f-68ba-465f-bec9-aab65ce0a9b1)

**Comment by boylett** [comment]
Many of these issues are now fixed with [#cf4eb85](https://github.com/Sheezy-Art/sheezy.art/commit/cf4eb85afbc25eac73fc4bf4cddb22d6b613a2e6) – though I will add that some of the comments here are opinion-based rather than actual issues.

Input boxes, for instance, will remain white across the board. Consistency is a valuable part of UX.

**Comment by Proxybat** [comment]
**Wanted to add that user profiles seem to be using the light theme instead. Even when user is on the dark mode.**

Screenshots are both in darkmode:
![Screenshot 2024-02-05 at 13-07-54 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/ea218cf2-a9bf-4051-809e-30567bbfb9df)
![Screenshot 2024-02-05 at 13-08-08 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/e04abc79-ae9b-4adf-9e75-1d5ece5a9244)
