### ISSUE TITLE
[BUG] Not all static page URLs are invalid usernames

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#391]
**Describe the Bug**
Some pages (at least [`faqs`](https://sheezy.art/faqs)) are not treated as invalid usernames, so you can rename your account username to match them. This causes the user profile and all of its subpages (including artworks and all settings) to become inaccessible, as they all take you to the page.

(On a *totally unrelated* note, I *might* need my account renamed back to `@undefined`. Maybe.)

**To Reproduce**
1. Go to user settings
2. Change your username to match one of the pages linked in the footer
3. ...congratulations, you just locked yourself out of your profile!

**Expected Behaviour**
Like for other banned pages (`browse`, `feed`, etc.), a warning pops up saying the username is invalid.

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#dd7de87](https://github.com/Sheezy-Art/sheezy.art/commit/dd7de877fa71f98974d26f7f5ab9bfea5147b9c2). And I have reverted your username to **@undefined**.
