### ISSUE TITLE
[BUG] Persona's don't have a proper title tag...

### ISSUE THREAD

**Issue by Proxybat** [Sheezy-Art/sheezy-hub#392]
**Describe the Bug**
When I go to a "persona" the tab name for that page only display's `Sheezy.Art`

**To Reproduce**
1. Go to a user with a persona.
2. Go to the persona's profile. (In this case I viewed this page via an URL sent to me.)
3. Look at the tab name.

**Expected Behaviour**
I expected to see the persona's username appended like regular profiles. Eg: `Sheezy.Art – @username's Profile`
Instead it just shows first half: `Sheezy.Art`

**Screenshots**

Screenshot of error:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/7148cda8-c850-4450-a183-713f581b3ebb)
Screenshot of non-persona account:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/cdf2217f-643d-4778-95ad-63b57e1bef85)

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1 64bit

_Also I'm very new to submitting bugs so I'm sorry if I messed something up._

**Comment by boylett** [comment]
Fixed by [#58d5702](https://github.com/Sheezy-Art/sheezy.art/commit/58d5702846fdc3acdb91f4446a5edf8490faaec5)
