### ISSUE TITLE
[BUG] long links goes outside the description box in artwork posts

### ISSUE THREAD

**Issue by coolmanatee** [Sheezy-Art/sheezy-hub#394]
**Describe the Bug**
if the link address is too long it goes outside the artwork post description container

**To Reproduce**
1. include in the artwork description a long link address (can be a new upload or editing a already existing one)
2. press to save the changes or publish it
3. go to the upload page to find the link ultrapassing the description box

**Expected Behaviour**
the link adress is supposed to break the lines to fit inside the container box

**Screenshots**
![linkissue1](https://github.com/Sheezy-Art/sheezy-hub/assets/159379448/31eac07d-2fc1-4dbc-9d67-a440d4549142)
(the post above doesnt have that long adress link anymore, has been updated to a shorter one)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Opera and Google Chrome
 - Version: 106.0.4998.70(opera) and 121.0.6167.161(chrome)

**Comment by boylett** [comment]
Fixed by [#746acd4](https://github.com/Sheezy-Art/sheezy.art/commit/746acd486000ebef3369f0782b60389bd7217144)
