### ISSUE TITLE
[BUG] Allotted uploads number is wrong

### ISSUE THREAD

**Issue by tymime** [Sheezy-Art/sheezy-hub#395]
Do I have a phantom upload or something? It's been like this for the past few days despite me only actually uploading 4 things a day (which is a pain the butt by the way). I'm unable to upload 5 a day anymore.
<img width="425" alt="Screen Shot 2024-02-08 at 6 12 26 PM" src="https://github.com/Sheezy-Art/sheezy-hub/assets/18604835/da93d3e3-b773-4670-bc9b-6ce0d33476e8">

I'm on a Mac using Chrome

**Comment by tymime** [comment]
Okay now it says "0 of 5" again finally... I don't know what's going on.

**Comment by tymime** [comment]
<img width="445" alt="Screen Shot 2024-02-10 at 7 19 21 AM" src="https://github.com/Sheezy-Art/sheezy-hub/assets/18604835/1dabe312-c64b-463a-8585-b2fbd9a32b99">
???
Now it's saying this despite 24 hours having passed??

**Comment by boylett** [comment]
This is strange. Do you have any drafts in progress?

**Comment by tymime** [comment]
I have no idea. I've tried looking to see if there was a drafts page or something, but I couldn't find one.

**Comment by boylett** [comment]
The upload page itself is the drafts page. If you have artworks 'in progress' on the upload page, those are the drafts in question, and count towards your upload limit.

**Comment by tymime** [comment]
I don't have any artwork in progress.

**Comment by boylett** [comment]
Are you still experiencing this issue?

**Comment by tymime** [comment]
No, whatever was happening seems to have cleared up on its own a while ago. I do recommend looking into it still though. I'm pretty sure there was an unsubmitted upload in limbo at some point, but I couldn't access it.

**Comment by boylett** [comment]
Aye, I think this was fixed by [#e923dc0](https://github.com/Sheezy-Art/sheezy.art/commit/e923dc0a587d4ba785c0902b9e890731302d8343). Will definitely keep an eye on it 👍
