### ISSUE TITLE
[BUG] Long words don't wrap, overflow outside of bounds

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#397]
**Describe the Bug**
Instead of wrapping around, long strings of characters overflow outside of the box. This happens in journals, literature uploads (both on the feed and while viewing them), artwork descriptions and comments (although there the overflow is contained within the comment box).

**To Reproduce**
1. Either make a journal, artwork description or comment with a string long enough to be longer than the length of the box it is contained in.
2. See the text overflow.

**Expected Behaviour**
The text wraps around. This kind of behavior can be achieved through a few means, like CSS's `overflow-wrap: break-word`; this page from MDN docs might be useful: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_text/Wrapping_breaking_text

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/1f28f2b4-a123-4e0e-92b9-0cc0fc21479c)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/efc8af29-b53d-4517-99d2-a0a58e326ed9)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/3ee969e0-30da-4809-b373-c0fe539ccc2d)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/319221ee-cc24-4331-98e5-2e4db0f4eef5)

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#ac471bb](https://github.com/Sheezy-Art/sheezy.art/commit/ac471bb8b0669f01c8aba90296e6ff9aec2d2e46)
