### ISSUE TITLE
[BUG] Unpublished drafts show up on the "Everything by Everyone" feed

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#398]
**Describe the Bug**
If there's an unpublished draft uploaded by the user, it will appear on the "Everything by Everyone" feed, with no indication that it is a draft.

**To Reproduce**
1. Upload an artwork, set up its information and click "Save changes".
2. Go to the "Everything by Everyone" feed.
3. See the unpublished draft show up.

**Expected Behaviour**
The unpublished draft doesn't appear on the feed.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/fa540051-0059-4378-91fa-3635b6b66ff9)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/e66e0687-6000-4341-92db-75de44cb2ac2)

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#6d3d980](https://github.com/Sheezy-Art/sheezy.art/commit/6d3d980843dd30b1d79c01a3796a83ec39782ba9)
