### ISSUE TITLE
[BUG] Feed doesn't indicate like status unless you hover.

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#399]
**Describe the Bug**
Artworks in the feed do not register the fact you liked it (the like button appears as if you didn't like it) unless you hover over it.

**To Reproduce**
- Go to any feed
- Like an artwork or find an artwork you know for sure you liked
   - If you liked an artwork, then refresh the page
- The like button appears as if you didn't like it, unless you hover over the button to see who liked it.

**Expected Behaviour**
The feed accurately reflects whether you liked an artwork or not without intervention.

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#fd1b7bf](https://github.com/Sheezy-Art/sheezy.art/commit/fd1b7bf83c753f64e2775af693a15a009c9cf9fb)
