### ISSUE TITLE
[BUG] Feed page 418s if you have no feeds

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#400]
**Describe the Bug**
The feed page 418s if you have no feeds. Most likely started happening after the latest feed optimization update.

**To Reproduce**
1. Remove all your feeds.
2. Try to go to the feed page.

**Expected Behaviour**
The feed page doesn't 418.

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#b24a376](https://github.com/Sheezy-Art/sheezy.art/commit/b24a376582f54d4f0225ffde1e346ec47fa386eb)
