### ISSUE TITLE
[BUG] Enabling infinite load on the last page of long feed causes huge lag

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#401]
**Describe the Bug**
Feeds have an "infinite scroll" option enabled by the "Infinite" button on the page selector at the bottom of the page. This option causes artworks in the feed to load as you scroll forwards. If you switch to a later page and then enable infinite scroll, all previous artworks will begin to load (I have gotten it to jump back to the first page a few times though, so I'm not sure how intentional this behavior is). However, on particularly long feeds, the large amount of images to load can cause the user's browser to crash at best, or unnecessarily lag the website at worst.

**To Reproduce**
1. Go to a feed (the "Everything by Everyone" feed is a pretty good example)
2. Scroll down to the page selector and go to the last page
3. Scroll down to the page selector again and click the "Infinite" button
4. Watch the "refresh feed" button display a loading spinner; if you open up the "Network" tab in your browser's dev tools, you can see it download a lot of images.

**Expected Behaviour**
Some threshold for how many images can be loaded is applied; after crossing it, either the infinite loading only goes back as far as is necessary, or forcefully takes you to the first page. Alternatively, pressing the "Infinite" button always takes you back to the top of the page.

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0

**Comment by boylett** [comment]
Fixed by [#c1195a4](https://github.com/Sheezy-Art/sheezy.art/commit/c1195a4bcf2509f7d8dc5b8c15e5c13dd15475d2)
