### ISSUE TITLE
[BUG] HR styles are incorrect in the preview tab but are correct in the 

### ISSUE THREAD

**Issue by CytricAcid** [Sheezy-Art/sheezy-hub#402]
**Describe the Bug**

**To Reproduce**
1. Edit your profile block
2. Style a hr, example 
`<hr style="height:2px;border-width:0;color:#8e4ee8;background-color:#8e4ee8">`

3. Preview HR
4. Compare to it once it's saved on your profile

**Expected Behaviour**
HR style in the preview should match the end result

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/264e388b-6007-44f0-b16f-6eb2a7e8cb2d)
^ in preview tab

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/8886304/abe74d44-bfe9-4c15-bfaa-4f171f1ca962)
^ once saved and viewed from the profile

**Device**
Windows 10, Firefox 122.0 64-bit

**Comment by boylett** [comment]
I'm not able to replicate this. Which block type are you using?

**Comment by boylett** [comment]
Fixed by [2024-03-26](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-03-26)
