### ISSUE TITLE
[BUG] Searching for newest journals results in the journals being squished

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#403]
**Describe the Bug**
When searching for new journals, they appear squished.

**To Reproduce**
1. Go to latest journals from people i follow.
2. Click on see more.
3. Disable "followed by me".
4. Observe squish.

**Expected Behaviour**
The journals should be displayed at a readable size.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/b7744d58-bde4-4803-af60-7fc173e812a8)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0.1

**Comment by Proxybat** [comment]
This also happened to me when I was browsing for journals on sheezy. (url used was https://sheezy.art/browse/journals)

The `<div>` s for the journals container and pagination container need a parent  `<div>` to hold both of them with  `flex-direction:column;` & `display:flex;` assigned to it's css.

I did this via inspect element and that fixed the issue, here's the screenshot of the inspect element attempt.
![Screenshot 2024-02-13 at 12-11-28 Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/d04522ef-4c78-4d0a-b880-bfed191d0dfd)

**Comment by boylett** [comment]
Fixed by [#230ff55](https://github.com/Sheezy-Art/sheezy.art/commit/230ff55e7533d85ebd92df998ea7647d06b1f74f)
