### ISSUE TITLE
[BUG] Content Preferences for Persona's not working

### ISSUE THREAD

**Issue by WolfenLynx** [Sheezy-Art/sheezy-hub#407]
**Describe the Bug**
I want my main account to blur explicit imagery, and my persona to allow unblurred explicit imagery (with the exception of specific tags) but my persona, when switched in, acts with the same settings as my main account. Basically content preferences for my persona are not getting properly applied.
![Screenshot 2024-02-16 115158](https://github.com/Sheezy-Art/sheezy-hub/assets/73141182/ca6ff060-e6c0-45a7-bae7-b9e36acf79f7)
![Screenshot 2024-02-16 115227](https://github.com/Sheezy-Art/sheezy-hub/assets/73141182/db11ad43-f595-4fb7-aa7e-3b92f7c2cc7c)
![Screenshot 2024-02-16 115253](https://github.com/Sheezy-Art/sheezy-hub/assets/73141182/90a9877a-aa9b-4bcf-9a41-0d47e3c8ec93)

**To Reproduce**
1. Apply the desired settings on both accounts and save changes
2. Switch to persona
3. View explicit image

**Expected Behaviour**
I want my main account to blur explicit imagery, and my persona to allow unblurred explicit imagery (with the exception of specific tags)

**Device**
- Type: laptop/pc/smartphone
 - OS: windows & android(samsung)
 - Browser: firefox and mobile google chrome
 - Version: current live version which i beleive is version 3.0.0 build 240212-ff5dca2f

**Comment by boylett** [comment]
Fixed by [#fc832bd](https://github.com/Sheezy-Art/sheezy.art/commit/fc832bd3e5564cd5d33fa2e90ce922d724c20dcd)
