### ISSUE TITLE
[BUG] Comment replies are completely borked

### ISSUE THREAD

**Issue by herdingcatz** [Sheezy-Art/sheezy-hub#409]
**Describe the Bug**
When a journal has a comment and that comment has a reply the drop down that will display the replies to that comment vanishes when it is hovered over, meaning that replies to comments can not be viewed.

**To Reproduce**
1. Go to a journal that has a comment with a reply
2. Hover cursor over the drop down that will display the reply when clicked

**Expected Behaviour**
The text should not vanish and should instead be clickable. Upon clicking the reply chain should appear.

**Screenshots**
I took a picture of my screen itself so that you can see my cursor.
![hover](https://github.com/Sheezy-Art/sheezy-hub/assets/104286125/02d26527-953a-429a-a792-03defd217faf)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox 122.0.1 (64-bit)
 - Version: 3.0.0 build 240218-608d7b40

**Comment by kushbreth** [comment]
I was about to report this myself, I would just like to add that this bug is on profile comments and art submission comments as well!

**Comment by Proxybat** [comment]
I'm having the same issue, also another thing I've noticed:
- When viewing a comment thread (i.e pages within the `https://sheezy.art/comment/`  url) the reply just doesn't load, only the original comment. 
- Also for a split second it displays the "there are no comments here" dialog that then disappears.

**Comment by boylett** [comment]
Fixed by [#320c70a](https://github.com/Sheezy-Art/sheezy.art/commit/320c70ae4dbb963c7adb414298babfa05052eb96)

**Comment by Proxybat** [comment]
While everything else on my end is fixed this part of the issue:
> When viewing a comment thread `(i.e pages within the https://sheezy.art/comment/url)` the reply just doesn't load, only the original comment.

Is still a thing.
