### ISSUE TITLE
[BUG] attempting to edit persona artworks returns a 418 error

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#410]
**Describe the Bug**
Trying to edit an artwork on a persona returns a 418 error.

**To Reproduce**
- Go to any persona artwork
  - If no personas exists, make one
  - If no persona art exists, break out your drawing tools and make something to upload to your persona
    - After adding the required fields, adding tags, tinkering with the rating, publish the artwork
- Attempt to edit the artwork made by the persona
- 418 error (Sheemz is eating the code)

**Expected Behaviour**
Editing persona artworks should function as if you were editing your own artworks.

**Device**
- Type: Desktop
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#fc64187](https://github.com/Sheezy-Art/sheezy.art/commit/fc6418733b7dfd16a49b1bf56264dd956d79fe99)
