### ISSUE TITLE
[BUG] Content blur not following content warnings

### ISSUE THREAD

**Issue by FunkyGoodVibes** [Sheezy-Art/sheezy-hub#411]
**Describe the Bug**
The content warnings and the "Blur content that has Content Warnings" toggle. 
It still blurs content even though it is removed it from the Content warnings. Like eyestrain and blood, for example.
If I turn off the "blur" toggle, then I still see the thumbnails for the content I don't want to see. 

**To Reproduce**
1. Go to Account settings > Tags & Content Warnings
2. Click on Enable "Blur content that has Content Warnings"
3. Check your content warnings and remove "eyestrain," for example.
4. Go to the search bar and search #eyestrain.
5. All images are blurred, even though the content warning is removed from the settings.  

**Expected Behaviour**
With the blur toggle active, the user set content warnings should only blur images that a user has tagged. (Under their content warnings) (My example is sexual content, I have them tagged as shown in screen shots but not blood.)

**Screenshots**
![Screen Shot 2024-02-18 at 5 23 18 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155789805/b85a7419-92ac-4515-a2d0-62cf6aa02eeb)
![Screen Shot 2024-02-18 at 5 24 59 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155789805/0e40f59f-79fd-4abc-a40e-c7acfa701169)

**Device**
- Type: Desktop
 - OS: MacOC Catalina 10.15.7
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
This is happening because the data that gets loaded into the 'Browse' page is cached. That means it is saved on the server to improve load times. To fix this type of issue, I think I need to overhaul the way data is cached altogether.

**Comment by boylett** [comment]
Fixed by [#48f15b8](https://github.com/Sheezy-Art/sheezy.art/commit/48f15b8082fc63cee4b6b0c3d9b720015c2414af)
