### ISSUE TITLE
[BUG] Ability to enter edit mode on other people's art

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#412]
**Describe the Bug**
By appending `/edit` at the end of someone else's art, you can enter edit mode for that artwork. However, you cannot save any changes to other's artworks.

**To Reproduce**
- Go to another user's artwork. Emphasis on *another user.*
  - I will be using CytricAcid's artwork, [Pastel](https://sheezy.art/cytricacid/gallery/pastel) as an example.
  - As of #410, trying this trick on personas doesn't work as it will return a 418 error.
 - Append `/edit` at the end of the url
 - You are now in edit mode, but you can't save (vandalism is impossible from my end)

**Expected Behaviour**
Trying to edit another user's artwork will return either a 403 or 418 error (most likely a 403 error).

**Screenshots**
The artwork's page, for reference
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/af908e51-8d17-4f6f-adfa-9a122d446fcc)

This is NOT my screenshot. Ask Cy.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/d0118122-64c9-45b5-8625-1b0d883f9d12)

You can type stuff in here...
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/e8e121d6-70a5-43d0-a7f7-ff8acf344c07)

But the changes won't be reflected :)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/6ba21dcf-b578-4f7a-895b-8626061c55a3)

**Device**
- Most likely a server-side issue.

**Comment by boylett** [comment]
Fixed by [#fc64187](https://github.com/Sheezy-Art/sheezy.art/commit/fc6418733b7dfd16a49b1bf56264dd956d79fe99)
