### ISSUE TITLE
[BUG] Ghost Notifications

### ISSUE THREAD

**Issue by maarblecakes** [Sheezy-Art/sheezy-hub#413]
**Describe the Bug**
there are ghost notifications on my dashboard, they do not go away when clicked on

**Screenshots**
![sheezy bug 1](https://github.com/Sheezy-Art/sheezy-hub/assets/160442864/064bef68-b7e3-4de2-bb28-50eae7147a7c)

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Google Chrome

**Comment by maarblecakes** [comment]
the ghost notifs have gone from 4 to 6 
<img width="720" alt="proof sheezy" src="https://github.com/Sheezy-Art/sheezy-hub/assets/160442864/846066dc-c00e-4072-9738-c5c0d96f199a">

**Comment by boylett** [comment]
Hm. Have you tried scrolling all the way back down using Infinite scrolling to see if it's just some old notifications hanging around?

**Comment by maarblecakes** [comment]
> Hm. Have you tried scrolling all the way back down using Infinite scrolling to see if it's just some old notifications hanging around?

holy moly. just tried it, and it did work :) thank you for your patience and help!

**Comment by boylett** [comment]
WAHOO! No problem! Happy to help :)
