### ISSUE TITLE
[BUG] Not Able to View Journals

### ISSUE THREAD

**Issue by maarblecakes** [Sheezy-Art/sheezy-hub#414]
**Describe the Bug**
clicking on a journal on the "latest journal entries" brings me an error page

**Screenshots**
<img width="1265" alt="sheezy bug 2" src="https://github.com/Sheezy-Art/sheezy-hub/assets/160442864/666f0334-2c05-4d75-bbee-7de474026155">

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Google Chrome

**Comment by boylett** [comment]
Fixed by [#fc64187](https://github.com/Sheezy-Art/sheezy.art/commit/fc6418733b7dfd16a49b1bf56264dd956d79fe99)
