### ISSUE TITLE
[BUG] 418 when entering a higher-rated account no longer shows the user's rating

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#416]
**Describe the Bug**
Before the rewrite, when going onto the profile of an account with a content setting higher than your visibility settings, there was a message on the error page indicating the user's rating and a unique graphic. As of the rewrite, this is no longer the case, and entering such profiles gives a generic 418 error.

**To Reproduce**
1. Set your content seeing rating to General.
2. Try to open an account with a higher rating

**Expected Behaviour**
The specialized error message still appears.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/534e7853-97e7-4ab2-9130-e583813f1855)

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#edf3c65](https://github.com/Sheezy-Art/sheezy.art/commit/edf3c6587de0bd0284f00e95f31d0bfdc141f5e4)
