### ISSUE TITLE
[BUG] Going to a locked user profile returns a 418 error instead of a 403 error

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#417]
**Describe the Bug**
After the site rewrite, going to a locked user profile returns a 418 error instead of a 403 error.

**To Reproduce**
1. Go to any locked user profile
2. See 418 error

**Expected Behaviour**
A "profile is locked" page appears, like before.

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#edf3c65](https://github.com/Sheezy-Art/sheezy.art/commit/edf3c6587de0bd0284f00e95f31d0bfdc141f5e4)
