### ISSUE TITLE
[BUG] Editing image on persona switches to main.

### ISSUE THREAD

**Issue by SeagullCity** [Sheezy-Art/sheezy-hub#418]
**Describe the Bug**
Editing an image on a persona ends up vanishing from the personas gallery and switches onto your main.
This happened to 3 images but in the video below I captured the third time of it happening to confirm what's been repeated.
(These are the images it happened too)
https://sheezy.art/seagullcity/gallery/sf-extras-flower-walk-18
https://sheezy.art/seagullcity/gallery/sf-extras-flower-walk-28
https://sheezy.art/seagullcity/gallery/sf-extras-flower-walk-38
They are meant to be the personas gallery here
https://sheezy.art/seagullcity/persona/swords_and_flowers/gallery

**To Reproduce**
1. Go to edit an image uploaded on a persona either just from tags, desc or reuploading an image.
2. Save changes.
3. Get 404 error cause the image somehow no long exists on that persona. 
(It might still appear like it's still there but takes a lil bit to disappear)
4. Check your main and the image that you edited appears on your main gallery instead of the persona.
(In the video below probably shows better on what happens)

**Expected Behaviour**
I expected the image that was edited on the persona's page to stay in the persona's gallery but instead it disappears and reappears on your main.

**Screenshots/Video**
https://www.youtube.com/watch?v=bPwpEvlQq0I

(The image now appearing on main)
![image1](https://github.com/Sheezy-Art/sheezy-hub/assets/160529056/ccdf7ea6-8f99-4e81-a37e-87921b8f8f49)
(The image eventually gone)
![image2](https://github.com/Sheezy-Art/sheezy-hub/assets/160529056/8970a050-c2c7-4044-8838-2edb8d1b8002)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 121.0.6167.185 (Official Build) (64-bit)

**Comment by boylett** [comment]
Fixed by [#fc6fc5a](https://github.com/Sheezy-Art/sheezy.art/commit/fc6fc5ad439c4a4436127faa56230d842a823c16). Additionally, this commit brings a feature to switch the persona that an artwork is assigned to in the form of a dropdown on the upload/edit artwork pages.
