### ISSUE TITLE
[BUG] Issue with profile customization

### ISSUE THREAD

**Issue by hopeiessdespair** [Sheezy-Art/sheezy-hub#419]
**Describe the Bug**
I recently made a persona account to post art, and when I go to edit my profile content (after pressing save changes) it bugs. I then cannot use the blocks I placed down before saving changes. I do not know if this also happens on non-persona accounts

**To Reproduce**
1. Make a persona account
2. Click on Edit Profile
3. Add any blocks to the profile
4. Press "Save Changes"
5. See error

**Expected Behaviour**
I expected the profile to save and me to be able to go back to the profile and see the blocks i placed.

**Screenshots**
![ScreenRecording2024-02-19at5 44 42PM-ezgif com-video-to-gif-converter](https://github.com/Sheezy-Art/sheezy-hub/assets/89989086/b92ecf9b-57ce-4fb0-af94-146d6eb5eafe)

**Device**
- Type: Apple Laptop
 - OS: iOS
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
This should now be fixed as of [#3c2f64a](https://github.com/Sheezy-Art/sheezy.art/commit/3c2f64a74ca9b03ba36f30d88352d7e529d43e5e). Please reopen the issue if not!
