### ISSUE TITLE
[BUG] Pieces higher than G not showing up on profiles

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#420]
**Describe the Bug**
Pieces rated M or X are not showing up on other profiles/personas profiles.
Notes: 
They show up when logged into that specific persona
My preferences are set to show me up to X content.
The pieces show up in the Gallery tab

**To Reproduce**
1. Go to a profile displaying artworks that are higher than G. ([here is one of mine where everything is rated M.](https://sheezy.art/crocojaws/persona/twistedtattoo) )
2. See error

**Expected Behaviour**
Pieces visible would reflect my preferences.

**Screenshots**
![Screen Shot 2024-02-19 at 9 20 57 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/81fad226-a906-4a12-9198-fef5dca2fe83)
![Screen Shot 2024-02-19 at 9 21 07 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/10e03b33-1588-4a26-9bef-c9294c6fddde)

**Device**
- Type: Laptop and Ipad
 - OS: [e.g. Windows, iOS]
 - Browser: [e.g. Google Chrome, Safari, Opera]
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Should be fixed by [#48f15b8](https://github.com/Sheezy-Art/sheezy.art/commit/48f15b8082fc63cee4b6b0c3d9b720015c2414af). Please reopen if you are still experiencing this!
