### ISSUE TITLE
[BUG] Text is not appearing/being inputted on login screen (iPhone 6s, iOS 15.8)

### ISSUE THREAD

**Issue by DaniJam005** [Sheezy-Art/sheezy-hub#421]
**Describe the Bug**
Text is not appearing/being inputted on login screen (iPhone 6s, iOS 15.8)

**To Reproduce**
1. Go to the sheezy.art login page using iOS 15.8 on an iPhone 6s
2. Attempt to enter in account info

**Expected Behaviour**
In the username/email tab, if you try entering anything, only one letter will appear out of what you type in and everything else either doesn't appear or isn't being inputted at all. 

**Screenshots**
Google App:
![IMG_2374](https://github.com/Sheezy-Art/sheezy-hub/assets/118861261/f45519f9-0a41-4de9-adbd-183f2bf79587)

Chrome App:
![IMG_2376](https://github.com/Sheezy-Art/sheezy-hub/assets/118861261/3aa983d0-dffb-4e0e-ac7a-aca18a0ed3e1)

Safari:
![IMG_2377](https://github.com/Sheezy-Art/sheezy-hub/assets/118861261/69abc2fc-2b58-40b2-85f9-e000143194cb)

**Device**
- Type: Smartphone (iPhone 6s)
 - OS: iOS 15.8
 - Browser:  Google App, Google Chrome, Safari
 - Version: Google App Version 303.0.605094169, Safari 15.8, Chrome App Version 121.0.6167.171

**Comment by celestialcreature** [comment]
This happens on my ipad as well

Software version 15.6.1
Hardware: ipad pro 2nd generation 
Browser: firefox, safari, chrome
