### ISSUE TITLE
[BUG] Long journal titles on the main page break up mid-word, cut off early with no ellipsis

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#423]
**Describe the Bug**
 Not necessarily a bug, mostly a style nitpick... Long journal titles on the main page break up mid-word and cut off early with no ellipsis.

**To Reproduce**
1. Go to the main page
2. See a journal with a long title.

**Expected Behaviour**
For the word break, this could be fixed by setting `word-break` to `break-word` instead of `break-all`. For ellipsize... either ellipsize it on the backend (since it's already being cut off...), or do it client-side with a CSS tweak for it (sadly ellipsizing multiple lines requires a slightly-nonstandard property but it's supported by all browsers except IE11, see https://css-tricks.com/line-clampin/#aa-the-standardized-way, [support matrix](https://caniuse.com/mdn-css_properties_-webkit-line-clamp))

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/61c4f4c1-dc4a-4c55-8ecd-be6e389e47bb)

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#46bb6ea](https://github.com/Sheezy-Art/sheezy.art/commit/46bb6ea1a41889f5b9182d7161fc3d73dc70e69d)
