### ISSUE TITLE
[BUG] Some excluded tags still show up in Browse and user Galleries, despite being filtered in Content Settings

### ISSUE THREAD

**Issue by VN-100** [Sheezy-Art/sheezy-hub#426]
**Describe the Bug**
When adding excluded tags to filter in Content Settings (e.g., 'nudity'), those tags will still show up when scrolling through the Browse and user Gallery sections. Clicking through them shows the Sheemz content warning, along with the tag that you have blocked in content warnings, but the excluded tag itself is not hidden while browsing through the site. (May also have to do with recently following a user and the tags on their work not being registered as an excluded tag post-follow, uncertain on that front.)

**To Reproduce**
1. Go to Account Settings
2. Go to Content Settings
3. Click on Tags & Content Warnings, add a tag to Excluded Tags
4. Go back to Browse or a user Gallery
5. See that pieces with that tag are still showing up while browsing
6. (additional possibility) See that the excluded tag is not filtered on an account you just followed

**Expected Behaviour**
Excluded tags will hide all content with those tags from view. Following a user will not allow excluded tags to show.

**Device**
- Type: Laptop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#48f15b8](https://github.com/Sheezy-Art/sheezy.art/commit/48f15b8082fc63cee4b6b0c3d9b720015c2414af)
