### ISSUE TITLE
[BUG] Custom Box Issue

### ISSUE THREAD

**Issue by ShadaneArts** [Sheezy-Art/sheezy-hub#427]
**Describe the Bug**
I tried to add a silly, fake advertisement using a banner from my Imgur album with "come get your mustaches here" under the picture, and trying to save my changes seems to result in an error page, plus me having one custom box marked as used that isn't even there anymore. The option for adding custom content is now grayed out with "4 of 4 used", even though there's only one showing on my page, and none of them were saved. What's happening?

**To Reproduce**
1. Go to your Profile Page
2. Click on 'Edit Profile'
3. Scroll down to 'Add Block'
4. Embed an Imgur image, and try to save your changes, and it leads to an error page.

**Expected Behaviour**
It should save the image and text, and appear on my profile, and missing custom boxes that failed to save shouldn't count towards custom content blocks I used.
**Screenshots**
I can only add this one screenshot, because the bug disallowing me from adding anymore custom content blocks prevents me from trying to recreate it. 
![2024-02-20 11 37 47 sheezy art 574157754426](https://github.com/Sheezy-Art/sheezy-hub/assets/160664461/d59313c4-e076-41c1-8a9c-ff261340c25e)

**Device**
- Type: [Laptop PC]
 - OS: [Windows]
 - Browser: [Vivaldi]
 - Version: [22H2]

**Comment by boylett** [comment]
What's your sheezy username? I can have a look at your account and see what's happening.

**Comment by ShadaneArts** [comment]
> What's your sheezy username? I can have a look at your account and see what's happening.

It's Shadane.

**Comment by boylett** [comment]
Thank you! This is now fixed as of [#3c2f64a](https://github.com/Sheezy-Art/sheezy.art/commit/3c2f64a74ca9b03ba36f30d88352d7e529d43e5e)
