### ISSUE TITLE
[BUG] Mod Queue- Modmail not showing up in "manage"/"open in admin"

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#428]
**Describe the Bug**
A journal in the moderation queue  displays that there is a modmail attached, but none show up in 'open in admin'. The modmail IS visible when viewing the tab on the journal page itself.
--- Upon writing this i realize it is an error in artworks as well- I just havent seen the (1) on pieces not in the screencap.

**To Reproduce**
1. Go to the most recent journal in disputes queue that I failed
2. Click on 'open in admin'
3. Click on modmail(1)

**Expected Behaviour**
The modmail would be visible both in admin and on site

**Screenshots**
![Screen Shot 2024-02-21 at 11 47 04 PM](https://github.com/Sheezy-Art/sheezy-hub/assets/155376814/8b486483-0681-493f-a0a9-89340ae10f75)
note: i have removed some of the information from this screenshot for the public github
The journal used as an example here is in the dispute queue.

**Device**
- Type: Laptop, Mobile and ipad all have this issue.
 - OS: [e.g. Windows, iOS]
 - Browser: [e.g. Google Chrome, Safari, Opera]
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#e2a7d2b](https://github.com/Sheezy-Art/sheezy.art/commit/e2a7d2bef569621225a8df9ea9f2dc2b7a18ed6f)
