### ISSUE TITLE
[BUG] Notification count in titlebar is not cleared when notifications are opened in another tab

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#429]
**Describe the Bug**
The notification number in the site title (as displayed on the tabs) stays even as the notifications themselves are already cleared in another tab. This change is already reflected by the notification button, but not the titlebar.

**To Reproduce**
1. Get a notification
2. Open two tabs
3. On one tab, open the Notifications page
4. Go back to the previous tab; the notification count next to the button disappears, but it stays in the site title

**Expected Behaviour**
The site title updates accordingly.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/21b53879-ddcd-4e01-b088-15546bc21c9a)

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Fixed by [#7660de5](https://github.com/Sheezy-Art/sheezy.art/commit/7660de5b8f09189934a9f2741793621ee3481e68)
