### ISSUE TITLE
[SUGGESTION] Move the "Sheezy.Art" prefix in the site title to the suffix?

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#430]
**Describe the Bug**
When a lot of tabs are open, it's very difficult to tell which tab is open on what page:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/0d915545-d859-4064-bc04-1423ddb65ed3)

This information is *already* in the title, but since it's after the site name, it's difficult to see if there's more than a few tabs open.

Nearly every other site has this the other way around - content title first, site title later:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/fa2f524d-fb96-456e-bec1-7133d1468e0c)

*(Yes, I know "feature requests" are closed, but since this is (most likely) a one line change, I thought I'd give it a shot...)*

**To Reproduce**
1. Open a lot of tabs.
2. Notice that all of them start with "Sheezy.Art" and you can't tell what's in them.

**Expected Behaviour**
The content title (e.g. the viewed artwork, username of the viewed profile, name of the page (e.g. Notifications, Feed) that's being viewed) is shown first, before the site title.

**Screenshots**
See above.

**Device**
- Type: Desktop PC
 - OS: Linux
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
This is the way it should be for accessibility! Have implemented this with [#91eb4da](https://github.com/Sheezy-Art/sheezy.art/commit/91eb4dae35f966b9191d0fa457fb4dcef70f6fa3)

**Comment by knuxify** [comment]
hmm, looks like that fixed it only for pages like the home page, still uses the old behavior on user profiles and artworks

**Comment by knuxify** [comment]
Seems to be fixed for all pages now!
