### ISSUE TITLE
Issues with excluded tags

### ISSUE THREAD

**Issue by HoneyBrownieArt** [Sheezy-Art/sheezy-hub#431]
**Describe the Bug**
Submissions containing excluded tags are still visible when browsing the site

**To Reproduce**
1. Go to content settings 
2. Add a new tag to the list
3. Click save settings
4. Return to the browse page
5. Artwork with excluded tag is still visible

**Expected Behaviour**
Submissions containing excluded tags should no longer be available to see anywhere on the site

**Device**
- Type: Smartphone
 - OS: Android 
 - Browser: Google Chrome
 - Version: Chrome 121.0.6167.178

**Comment by boylett** [comment]
Should be fixed by [#6471ee8](https://github.com/Sheezy-Art/sheezy.art/commit/6471ee8095cae73df9b4827e028f733ca6f71651) – please reopen the issue if not!
