### ISSUE TITLE
[BUG] Viewing an artwork over 20 seconds gives 418 Error message

### ISSUE THREAD

**Issue by Seldritchowl** [Sheezy-Art/sheezy-hub#432]
**Describe the Bug**
Hello! Run into a possible bug where I can't view any of my artwork page or others for more then 15-20 seconds without the page turning into '418 Something Went Wrong' message.

**To Reproduce**
1. Go to 'Gallery
2. Click on an Artwork's page
3. Be on the Artwork page for longer then 20 seconds
4. Sees error message

**Expected Behaviour**
I expect to be able to view the page for more then 20 seconds, without the page turning into an error message. ><"

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/77612056/c13dd984-a901-46ea-997c-168a982716ff)

**Device**
- Type: PC
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 121.0.2277.128

**Comment by boylett** [comment]
This must be the notifications fetcher! It wait for 20 seconds until getting the most up-to-date notification count. Will look into this!

**Comment by boylett** [comment]
Fixed by [#eed4610](https://github.com/Sheezy-Art/sheezy.art/commit/eed4610df995c9590e8d8a43a2484a1aaa59b5d2)
