### ISSUE TITLE
[BUG] Site tells me to activate account but it's been activated. Cannot post.

### ISSUE THREAD

**Issue by Viveltya** [Sheezy-Art/sheezy-hub#433]
**Describe the Bug**
Every time I try to comment or try to upload art, I get a message that I need to activate my account. Yet, I did do the activation and received the email stating that my account is activated.

**Expected Behaviour**
Being able to post comments and art.

**Screenshots**

**Device**
- Type: Desktop PC
 - OS: Windows
 - Browser: Firefox
 - Version: 123.0

**Comment by boylett** [comment]
I see that your account is active now. For future reference, please raise account questions to our staff directly rather than the GitHub!

**Comment by Viveltya** [comment]
Hi Ry!

Will do in the future! I'm sorry about this as I was guided to open a bug
on the Discord server and was very confused about it. The activation was
just delayed for some reasons because the next day everything was working
fine~

Thank you for your incredible work!

Viv~
