### ISSUE TITLE
[BUG] Comment section is nowhere to be seen!

### ISSUE THREAD

**Issue by dilflover1117** [Sheezy-Art/sheezy-hub#435]
**Describe the Bug**
Basically, my comment block isn't anywhere to be seen despite the fact it says in the editor it is in use! But nowhere in site when you visit my profile. It also doesn't appear in the editor as well!

**To Reproduce**
Very unsure how it happened, so I can't say what possible caused it :(

**Expected Behaviour**
You basically just cant see..my comment section at all, no matter what I've tried to do to fix it or make it visible again.

**Screenshots**
**Block showing Comments 1 of 1 Have been used**
![bug1](https://github.com/Sheezy-Art/sheezy-hub/assets/161094646/88d9bfd8-6ee2-419c-a81d-190ba1247021)

**Despite the block saying it's being used...obviously its nowhere to be seen on my page nor in editor**
![whereisthecomments](https://github.com/Sheezy-Art/sheezy-hub/assets/161094646/996a213e-46a0-49d2-9656-cd2ecf55e462)
![nocommentblock](https://github.com/Sheezy-Art/sheezy-hub/assets/161094646/c1260780-4e1e-421e-bac6-5db9fa34fcb0)

**Device**
- Type: PC.
 - OS: Windows 11
 - Browser: Opera GX
 - Version: core: 107.0.5045.30

**Comment by punkalope** [comment]
Heya! What is your Sheezy username? Trying to find the source of this since I can't seem to replicate it.
