### ISSUE TITLE
[BUG] Got a 418 error from trying to view a specific user's artwork

### ISSUE THREAD

**Issue by OmiChu** [Sheezy-Art/sheezy-hub#436]
**Describe the Bug**
The bug is happening when viewing a user's artwork. Seems to effect all artworks they have, except for one.

**To Reproduce**
1. Visted user's profile: https://sheezy.art/gearpunk
2. Click on "gallery tab"
3. Click again on any of the artwork's image thumbnail, except for the last one.
4. See error 418

**Expected Behaviour**
To be able to view the artwork.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/17e8c587-551e-4fbd-b9ee-31521404878e)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/157996754/d887350b-cb4a-4ff3-b727-e7dbc17071eb)

**Device**
- Type: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Version: 123.0

**Comment by boylett** [comment]
Fixed by [#22e4720](https://github.com/Sheezy-Art/sheezy.art/commit/22e47208ce9ffadaa80d3383d6a4bdc8ab98c2fd)
