### ISSUE TITLE
Blocked users art still shows up

### ISSUE THREAD

**Issue by WolfenLynx** [Sheezy-Art/sheezy-hub#437]
I blocked someone and their art still shows up on the main page

**To Reproduce**
- block someone
- look at the main page
- refresh several times

**Expected Behaviour**
art to be gone upon refresh

**Screenshots**
I dont want to make the blocked person feel bad haha

**Device**
windows 11 firefox laptop

**Comment by boylett** [comment]
Fixed by [#829e6d2](https://github.com/Sheezy-Art/sheezy.art/commit/829e6d26e6b0ed298b6710c6fa0d5ab584b0ae4b)
