### ISSUE TITLE
[BUG] Markdown spoiler syntax renders incorrectly

### ISSUE THREAD

**Issue by Proxybat** [Sheezy-Art/sheezy-hub#438]
**Describe the Bug**
Adding a spoiler using it's markdown syntax on an artworks description renders it incorrectly.

**To Reproduce**
1. Go to "upload artwork" and scroll down to the description section.
2. Type the following syntax into the description field:
```md
::: spoiler
spoiler text
:::
```

3. Click on "preview" on the description field

**Expected Behaviour**
Syntax should render the spoiler similar to how it renders on comments. Rather than a broken `<details>` and `<summary>` tag.

**Screenshots**
In editor's edit mode:
![Screenshot 2024-02-25 at 16-45-50 Upload Artwork – Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/520456da-aaf8-4815-9d6d-f4599c086f27)
In editor's preview mode:
![Screenshot 2024-02-25 at 16-46-05 Upload Artwork – Sheezy Art](https://github.com/Sheezy-Art/sheezy-hub/assets/93020192/0960825b-73f1-49ef-b65a-b5a702262c7f)

**Device**
- Type: Laptop
 - OS: Windows 11 (64-bit)
 - Browser: Firefox version 123.0 (64-bit)

**Comment by boylett** [comment]
Fixed by [#f18eb4e](https://github.com/Sheezy-Art/sheezy.art/commit/f18eb4e8b1fd3d38b6ba7430d0779be9cbfab5bb)
