### ISSUE TITLE
[BUG] Art set to be visible only by Sheezy Members still visible when logged out

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#439]
**Describe the Bug**
When I set an art piece to be visible by logged in users, I can still see it after logging out. Similarily, there is text that says "(Login)" next to the title when I am already logged in that does not appear when I'm logged out.

**To Reproduce**
1. Edit artwork to "Only visible to Sheezy Members"
2. Save.
3. Log out or open a private window.
4. Paste url of art, can still see image.

**Expected Behaviour**
I should be prompted with an error and/or a login screen.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a0022823-7345-43e2-b852-22220c3cadf7)
Logged in:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/143e5997-90f0-4695-a98f-e6c924605691)
Logged Out:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/499af5a8-f872-4daf-85ce-38b715a38d7d)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 123.0

**Comment by boylett** [comment]
Fixed by [#22e4720](https://github.com/Sheezy-Art/sheezy.art/commit/22e47208ce9ffadaa80d3383d6a4bdc8ab98c2fd)
