### ISSUE TITLE
html coding not working on journals

### ISSUE THREAD

**Issue by ghost** [Sheezy-Art/sheezy-hub#441]
**Describe the Bug**
html customization not appearing properly on journals. links and images still appear as the "raw" code both on preview and actual posting

**Expected Behaviour**
images and links should work as normal html coding

**Screenshots**
![Captura de tela 2024-02-26 131348](https://github.com/Sheezy-Art/sheezy-hub/assets/161347886/e59d0464-3836-4518-8419-cca4f566f8ff)
![Captura de tela 2024-02-26 131415](https://github.com/Sheezy-Art/sheezy-hub/assets/161347886/52b29c0f-6a7b-4ace-bde7-0de26f30e138)

**Device**
- Type: Desktop
 - OS: Windows 11
 - Browser: Opera
 - Version: 99.0.4788.77

**Comment by boylett** [comment]
Fixed by [#d0406ab](https://github.com/Sheezy-Art/sheezy.art/commit/d0406ab9ae4a689be97fa79288e6fea77e31fcf2)

**Comment by punkalope** [comment]
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/c89cbad6-3698-458a-8a6d-ed095ca29ca9)
Seems to break quite a bit now instead.
