### ISSUE TITLE
[BUG] Attempting to delete journals brings up their edit page instead

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#444]
**Describe the Bug**
When trying to delete a journal, the journal cannot be deleted. Instead it's edit page loads underneath the comments. This happens on both main accounts and personas and with drafts and private journals.

**To Reproduce**
1. Create a journal.
2. Attempt to delete it.
3. See bug.

**Expected Behaviour**
A journal should be deleted when I click the delete button.

**Screenshots**
![firefox_sTVQipc27M](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/e92e9066-4a61-4763-a6d0-d9f34ca9e8cb)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 123.0

**Comment by boylett** [comment]
Fixed by [#d99ee02](https://github.com/Sheezy-Art/sheezy.art/commit/d99ee0261be08ffcf752c90e4d307b4daff3db0f)
