### ISSUE TITLE
[BUG] Infinite Scrolling in Feed

### ISSUE THREAD

**Issue by CrescentCaribou** [Sheezy-Art/sheezy-hub#446]
The infinite scroll button on the "Feed" page breaks the site and gives me Error Code 418.

**To Reproduce**
1. Go to "Feed"
2. Scroll to the bottom
3. Click on "Infinite"

**Expected Behaviour**
The feed should become infinite (loading more images as you scroll). 

**Screenshots**
![Screenshot 2024-02-27 100437](https://github.com/Sheezy-Art/sheezy-hub/assets/158623710/0a16120d-efe4-4e2c-b484-b165781eb527)

**Device**
- Type: Acer Nitro Laptop
 - OS: Windows 11
 - Browser: Vivaldi
 - Version: Unknown (having trouble finding it, but I have auto-update on so _hypothetically_ it's the most recent one)

**Comment by boylett** [comment]
Fixed [#feb000e](https://github.com/Sheezy-Art/sheezy.art/commit/feb000e24bd6ec93b5470099541706de58d5ce9b)
