### ISSUE TITLE
[BUG] ModQueue- Cannot delete Mod Notes

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#448]
**Describe the Bug**
Cannot delete mod notes on pieces/journals, both in the admin panel and on the page for the piece itself. It may disappear but is still there upon refreshing/checking the other location.

**To Reproduce**
1. Add a mod note to any piece
2. Try to delete it
3. refresh the page / Check in admin
4. see error

**Expected Behaviour**
Deleting a note would delete a note

**Screenshots**
N/A

**Device**
- Type: [e.g. Desktop PC, Tablet, Smartphone]
 - OS: [e.g. Windows, iOS]
 - Browser: [e.g. Google Chrome, Safari, Opera]
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [#65605e5](https://github.com/Sheezy-Art/sheezy.art/commit/65605e525a0cd6ed618b0bb7b000b796023be6ba)
