### ISSUE TITLE
[BUG] Mod Notes- Editing mod note removes previous text

### ISSUE THREAD

**Issue by crocojaws** [Sheezy-Art/sheezy-hub#449]
**Describe the Bug**
When editing a modnote - the text is gone in the edit section and has to be retyped completely

**To Reproduce**
1. Go to a piece and add a mod note
2. Try to edit it
3. see error

**Expected Behaviour**
The previous text would still be present

**Screenshots**
N/A

**Device**
- Type: [e.g. Desktop PC, Tablet, Smartphone]
 - OS: [e.g. Windows, iOS]
 - Browser: [e.g. Google Chrome, Safari, Opera]
 - Version: [e.g. 22]

**Comment by boylett** [comment]
Fixed by [2024-03-26a](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-03-26)
