### ISSUE TITLE
[TODO] Refactor dropdown component

### ISSUE THREAD

**Issue by exlimixia** [Sheezy-Art/sheezy-hub#45]
**Describe the Bug**
The color selection box does not close when you either collapse or click another color customization category, which may get in the way of a user being able to see their options. The box stays in place regardless of where the user scrolls, 

**To Reproduce**
1. Go to Edit Profile
2. Click on the Customization Box on the left side of the screen.
3. Click on Colours.
4. Click on any color and open the color selection box.
5.a Scroll to see the box stay in place.
5.b Open or Collapse any other colour category to see the box stay open.

**Expected Behaviour**
When customizing, I expect any click outside of the color box to close the box. 

**Screenshots**
https://github.com/Sheezy-Art/sheezy-hub/assets/147447596/f9ce49ee-3a99-402e-ab34-204d0645daeb

**Device**
- Type: Desktop PC
 - OS: Windows 11
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
I have tried many different ways to fix this but so far have come up with nothing. It seems the dropdown engine we're using is not fit for purpose. Will look into this as a ToDo going forward as it is not a breaking issue.
