### ISSUE TITLE
[BUG] .psd files not uploading

### ISSUE THREAD

**Issue by swiftyuki** [Sheezy-Art/sheezy-hub#450]
**Describe the Bug**
When attempting to upload a .psd file, I'm running into an error saying it is an invalid file type.

**To Reproduce**
1. Click "Upload File"
2. Select .psd file
3. Click "Submit"

**Expected Behaviour**
Redirect to submission page

**Screenshots**
https://cdn.discordapp.com/attachments/903761241103818782/1212488601804480603/psd_upload.gif?ex=65f20501&is=65df9001&hm=6fb46029a1b33c803992c303e76e591de9fbeb1870cedf935dba3e45ece4c3f4&

**Device**
- Type: PC
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0.1

**Comment by boylett** [comment]
Should be fixed now – give it another try! If you're still having trouble feel free to reopen this issue.
