### ISSUE TITLE
[BUG] Unable to delete submissions

### ISSUE THREAD

**Issue by swiftyuki** [Sheezy-Art/sheezy-hub#469]
**Describe the Issue**
I am unable to delete a submission, it just refreshes the page whenever I attempt to delete the image.

**To Reproduce**
1. Be on a submission page
2. Click the dropdown menu to access "edit" or "delete" for submission
3. Click "Delete"

**Expected Behaviour**
Submission is deleted

**Screenshots**
--

**Device**
- Type: PC
- OS: Windows 10
- Browser: Firefox
- Version: 123.0

**Comment by VN-100** [comment]
Add-on to this, bug also affects journals - the page refreshes while attempting to delete from the dropdown menu, but no deletion dialogue is shown. With journals, the 'Edit' section is suddenly shown underneath the post after clicking Delete, and changing anything then hitting 'Save Changes' activates the deletion dialogue trigger before immediately redirecting the page to the 'changes saved' state. 

Deleting journal from edit page successfully deletes journal without mismatched dialogue or a secondary edit screen displaying.

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/c7d534df-5b42-4cd6-971e-f9bb1a5d62ae)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/0f43c3a5-bac2-4795-9540-452bc5034bb3)


<details>
  <summary>Console screenshots</summary>

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/598e2aca-995b-41f0-b0ca-70b7299a0934)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/81b9a50f-f505-4b4c-b8cf-d3aac1839341)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153317836/45093b39-232b-4da9-a772-4da66c0be40b)

</details>

(Laptop PC, Windows 10, Firefox, 123.0)

**Comment by boylett** [comment]
Is this still happening?

**Comment by swiftyuki** [comment]
I haven't tried to delete submissions recently, but it appears to have stopped when a moderator asked me to try again a bit after submitting this ticket

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
