### ISSUE TITLE
[BUG] Comment boxes changing colours on hover

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#472]
**Describe the Issue**
When hovering over a comment box - specifically on a profile page - the box changes colour, from the profile theme to site theme.

**To Reproduce**
1. Go to any customized profile.
2. Hover over comment box.
3. See change.

**Expected Behaviour**
The colour should stay consistent with either the site theme or profile theme.

**Screenshots**
![firefox_Ez8SUYVR2Q](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/d8a7b6bc-c6fe-4e86-be86-f96286e20e86)

**Device**
- Type: Desktop PC
- OS: Windows 10
- Browser: Firefox
- Version: 123.0.1

**Comment by boylett** [comment]
Fixed by [#537210d](https://github.com/Sheezy-Art/sheezy.art/commit/537210d0479f00f5a35d9cef4c37425faa11f014)
