### ISSUE TITLE
[BUG] Non-subscribers can see the "Subscriber Benefits" category in settings

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#477]
Although they can't actually access the linked page https://sheezy.dev/nyoom/account/awards as it redirects to https://sheezy.dev/nyoom/account 

**Video**
https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/17236a7c-cb81-49ef-898a-237de566f4ff
(carefully sized window to avoid leaking my email)

**Comment by boylett** [comment]
That is intended behaviour. When a user subscribes, they gain awards on a monthly basis. Once their subscription expires, they maintain access to the award inventory.
