### ISSUE TITLE
Markdown for linked thumbnails broken

### ISSUE THREAD

**Issue by Exodus-Drake** [Sheezy-Art/sheezy-hub#485]
**Describe the Issue**
When using sheezy's custom markdown for inserting image thumbnails for sheezy artwork, it results in a link instead of an image thumbnail

**To Reproduce**
1. Go to journal and create a new journal
2. Create  thumbnail, ex. [https://sheezy.art/edael/gallery/rainy-days-weep-away]

**Expected Behaviour**
Should result in showing thumbnail image of linked artwork.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/8cdf7dbe-2c83-4347-b78b-e59bc0885007)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/47377390/a23ab1d8-8b2b-4594-b4e1-cdd7c8abc2de)

**Device**
- Type: [Desktop PC]
- OS: [Windows 10]
- Browser: [Firefox (Waterfox)]
- Version: [Version G6.0.7 (64-bit)]

**Comment by Exodus-Drake** [comment]
Oh shoot, I was beat to it, damnit....

**Comment by Exodus-Drake** [comment]
Ahh, alright, sorry bout the repeat tho

**Comment by boylett** [comment]
This is actually a TODO - haven't got around to building this yet! Hopefully @xnyoom can help me wrangle some MarkdownIt plugins together to get this working 🤞
