### ISSUE TITLE
[SUGGESTION] Additional social icons

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#486]
Apparently adding social icons is really easy so I'll drop these suggestions:

Per user request https://github.com/Sheezy-Art/sheezy-hub/discussions/2#discussioncomment-8351447:
- [Kitsu](https://kitsu.io/explore/anime) &bull; [kitsu.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/88d021f0-cc3f-45d7-b219-53ef3bc96dd9)
- [CharacterHub](https://characterhub.com) &bull; can't find svg ;(
- [Pronouns.page](https://pronouns.page) &bull; [pronounspage.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/987b5ad6-de03-40e0-95ed-4f1ca16a6868)

Per my request:
- [Roblox](https://www.roblox.com) &bull; [roblox.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/a9455152-85d1-4165-ba2e-6dfe26f55dcb)
- [NameMC](https://namemc.com) &bull; [namemc.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/973fbbf6-86a0-404f-8706-621eb0c66dbf)
- [Minecraft](https://minecraft.net) &bull; [minecraft.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/ef537368-5e6e-4823-bf68-935f86fa6692)
- [Matrix](https://matrix.org) &bull; [matrix.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/c4ecea70-bbb6-4b2c-afbf-d08aac1fc5c1)
- [Cohost](https://cohost.org) &bull; [cohost.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/291c4b1c-aa9d-424e-b9eb-4fbf1c927cb8)
- [Nekoweb](https://nekoweb.org) &bull; contacted them about this but this is probably the best we'll get https://nekoweb.org/assets/meow.png
- [Retrospring](https://retrospring.net) &bull; [retrospring.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/e349de98-630d-46a8-b7fe-1b7a989c68c5)
- [Threads](https://threads.net) &bull; [threads.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/c8cd99f2-e2a0-47fe-89cb-99128a0e539a)
- [Session](https://getsession.org) &bull; [session.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/e8122983-89f4-404f-8219-2f05e4fe2fa7)
- [Genius](https://genius.com/) &bull; [genius.svg](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/c0b32a60-a60a-4c82-bcb6-8e95f2a6a5b8)

Lemme know if any are messed up since I crudely ripped most of these straight out of HTML/CSS.

**Comment by Stormeko** [comment]
I'd like to suggest Retrospring!
https://retrospring.net/

**Comment by boylett** [comment]
Not feasible to add the Minecraft logo as it contains colours and the icon font requires a 100% black SVG. Are there any other Minecraft logos we could use instead?

**Comment by boylett** [comment]
Works for me 👍

**Comment by boylett** [comment]
All of the above added in [#127](https://github.com/Sheezy-Art/sheezy.art/pull/127)

**Comment by boylett** [comment]
Yep, good plan!
