### ISSUE TITLE
[BUG] Blockquotes are unstyled on profiles

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#488]
Originally reported in #html-workshop: https://canary.discord.com/channels/1143702362091966654/1192455395009122324/1217183899793358918

**Notify Discord: Noir (penileperil) when fixed**

---

**HTML**
![](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/28850f03-c343-4d1b-93d9-87a52809fd26)

---

**Profile Information and Content Block**
![](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/389381b0-a92c-4a74-8cc7-26838444adc1)

---

**Journals (works fine)**
![](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/14a07a7f-4d71-46bf-9f61-c0b14ab86640)

**Comment by xnyoom** [comment]
This is because it's not getting wrapped in `<div class="prose"></div>` https://canary.discord.com/channels/1143702362091966654/1192455395009122324/1217602964672352357
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/eab6d732-6205-471c-9624-3f421936b390)

**Comment by boylett** [comment]
When the Profile Information block is set to `html` mode, and by default for Custom Content blocks, no out-of-the-can formatting is supplied. This allows the user complete freedom to control the way their HTML looks.

As above, putting `<div class="prose">` before and `</div>` after your HTML content will preformat it for you.

**Comment by xnyoom** [comment]
Ah, okay then.
