### ISSUE TITLE
[BUG] HTML previews for profile information blocks have extra spacing and other issues

### ISSUE THREAD

**Issue by knuxify** [Sheezy-Art/sheezy-hub#491]
**Describe the Issue**
The preview for the profile information block has a larger line height and extra margins between paragraphs, as well as styling for links, and weird margins on the side:

For the following code:

```html
<div style="padding: 0.85rem; text-align: center; font-family: 'Sitka Display', serif;">
<p>test <a href="https://google.com">link test</a></p>
<p>test paragraph 2</p>
</div>
```

Preview:

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/93ac13a9-4472-4da3-942c-73c76a04ba9b)

Expected result:

![Screenshot from 2024-03-12 22-51-24](https://github.com/Sheezy-Art/sheezy-hub/assets/23167991/60b6857f-4857-4228-bddf-3e8842c218cb)

Might be similar to #146, #345 - both are closed, but the issue still seems to happen.

**To Reproduce**
1. Go to your profile
2. Click on "Edit profile"
3. Go to the profile information block (add it if you don't have it)
4. Set the editing mode to HTML
5. Write your own code or paste in the example from above
6. Switch to the preview
7. Save and notice the preview should've been different

**Device**
- Type: Desktop PC
- OS: Linux
- Browser: Firefox
- Version: 123.0

**Comment by boylett** [comment]
Confirmed fixed
