### ISSUE TITLE
[BUG] Using mailto for social links causes the link to be hidden

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#492]
The link is saved in settings (refreshing still shows it) but it's not shown on profiles.

Ref: https://canary.discord.com/channels/1143702362091966654/1168515798394994811/1217233988557606932

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/7c343c38-35f2-482c-bc2a-d087a2d9f096)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/2b2fcd5b-2a29-44de-b5f1-add3ca10a0a5)

**Comment by boylett** [comment]
This is intended behaviour! Email addresses are considered 'Sensitive Information' and are not supported in social links. They can instead be added to the 'Private Contact Links' section, which doesn't currently show for personas (which is a bug)
