### ISSUE TITLE
[BUG] 2FA recovery codes are not being recognized 

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#500]
Trying to use a 2FA recovery code in place of a normal time-based code always shows the same error.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/50b6f153-e79c-4799-b084-09d1ff5ee41e)

**Comment by boylett** [comment]
Fixed by [#b36ffbf](https://github.com/Sheezy-Art/sheezy.art/commit/b36ffbf63be4b9eb5ca2dd7676a8ac161d3e2020)
