### ISSUE TITLE
[BUG] Spotlight art not blurring mature content when it should

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#506]
**Describe the Issue**
Spotlight seems to ignore "blur all mature and explicit content". Similarly, it does not blur for content warnings either.

**To Reproduce**
1. Go to content settings
2. Check Mature or Explicit art
3. Check "blur all mature and explicit content"
4. Refresh to see current spotlight
5. I have been flashed

**Expected Behaviour**
Spotlight art should follow my maturity settings

**Screenshots**
Censored for github of course
![firefox_pJYWLEQlgN](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/755ad505-6ba7-48d1-bb15-cbedc5e4f9dc)

**Device**
- Type: Desktop PC
- OS: Windows 10
- Browser: Firefox
- Version: 123.0.1

**Comment by xnyoom** [comment]
Oof, that's a bad one. Fast-tracked to the live site!
