### ISSUE TITLE
[BUG] Unable to delete personas

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#51]
**Describe the Bug**
When you go to delete an existing persona, you will get an error message after filling in the password. I did several attempts in the off-chance password was incorrect, this issue affects **all** personas.

**To Reproduce**
1. Go to 'Account Settings'
2. Click on 'Manage Personas'
3. Click "Manage" button on selected Persona
4. Click "Delete This Persona"
5. Click Delete (@ PERSONAUSERNAME)
6. Verify with Password
7. Following error: "Something went wrong! Please contact support to delete your account"

**Expected Behaviour**
Persona BEGONE.

**Screenshots**
N/A (uncomfortable sharing sc as it shows x amount of password dots)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: FireFox
 - Version: Latest

**Comment by punkalope** [comment]
![firefox_kPfW5aIgFE](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/15b7b655-a282-4d10-b22c-35e6f2baa1a0)
Screenshot for you!
