### ISSUE TITLE
[BUG] Trending thumbnails not always blurred for M ratings, on Persona

### ISSUE THREAD

**Issue by Zelleya** [Sheezy-Art/sheezy-hub#513]
**Describe the Issue**
Mature rated thumbnails on the front page's Trending do NOT always blur when logged into a Persona account, even despite having the content blur settings turned on. Most thumbnails will blur, but seemingly at random, some do not. When returning to main account (same settings) the thumbnails will all blur as expected.

**To Reproduce**
Steps to reproduce the behaviour:
Switch to Persona account.
Make sure content blur settings are turned on, of course.
Check the front/main page on Sheezy and watch the Trending selection move.
Most thumbnails blur, but occasionally they will not.

**Expected Behaviour**
As depicted in my screenshot, you'll still see the M for the rating on the thumbnail, but the thumbnail is visible. When clicking on it to open the full image, it WILL be blurred as expected. 
As the Trending selection updates to a new rotation of thumbnails, there seems to always be at least 2 that I find are not blurred but are M ratings all the same.

**Screenshots**
![Screenshot 2024-03-17 165258](https://github.com/Sheezy-Art/sheezy-hub/assets/161966890/12aa723b-70e1-4cfe-9ff0-ae9f67ac60fd)

**Device**
- Type: Desktop, PC
- OS: Windows 11
- Browser: Firefox
- Version: 123.0.1 (64-bit)

**Comment by xnyoom** [comment]
Reproduced - kind of. 

For me, no matter what, thumbnails when viewed via a persona are NEVER blurred - even though I have the option enabled on my main account. Using my main blurs the thumbnails as expected, it's only personas where this occurs. I looked for the maturity settings within the persona's account page (assuming the settings are per-persona) but the option appears to be missing for personas, so it clearly is supposed to use the main account's settings.

I did not encounter the problem where thumbnails are inconsistently blurred.

**Comment by Zelleya** [comment]
Thats interesting that the option is missing for you and that yours' is not inconsistent! 
I am able to see maturity settings on my persona account and had to manually set them to match my main account settings (by default, my persona account had no filters turned on, although my main account does Lol)

![Screenshot 2024-03-18 075619](https://github.com/Sheezy-Art/sheezy-hub/assets/161966890/61384089-4904-402e-bdd3-ffdd2a6f7cba)

I checked for mobile as well this morning (Samsung S20 FE, Android 13 on Chrome mobile browser) and the issue is exactly the same with inconsistent thumbnail blur, and the settings are visible on my persona account there too.

**Comment by Zelleya** [comment]
Its a little confusing for me since there's so many settings, but thats okay lmao
Glad this could help you find what was missing!

**Comment by xnyoom** [comment]
Yep, it can be a little confusing. Thank you so much for bringing this up!

**Comment by xnyoom** [comment]
Thanks for the report.

This has been fixed and will be reflected on the live site shortly. Please let us know if you find anything else!
