### ISSUE TITLE
[BUG] Lines breaking in inbox when artwork titles are too long

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#517]
**Describe the Issue**
If an artwork title is too long, it will break the line in the inbox.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open inbox.
2. See error if you have a notification for a long tiltle in there.

**Expected Behaviour**
Is word wrapping the right word?

**Screenshots**
![firefox_a4EIG0ti0t](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/6636197c-62b1-4444-a467-2579380ad612)

**Device**
- Type: Desktop PC
- OS: Windows 10
- Browser: Firefox
- Version: 123.0.1

**Comment by boylett** [comment]
Fixed in [2024-03-18b](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-03-18)
