### ISSUE TITLE
[BUG] Going on Sheezy on another device disables Content Warnings

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#518]
**Describe the Issue**
Accessing Sheezy on another device causes Content Warnings to be toggled off and must be turned back on. (I think)

**To Reproduce**
Steps to reproduce the behaviour:
- Have Content Warnings enabled (for best results, have "Blur Content Warnings" enabled)
- Go on Sheezy on another device
- Go to a piece with one of the warning tags
- Content warnings are disabled and must be reenabled.

**Expected Behaviour**
Content Warning setting (whether it's on or off) syncs between devices.

**Screenshots**
N/A

**Device**
- Type: Desktop | Mobile
- OS: Windows 10 | iOS
- Browser: Firefox
- Version: Unknown (Latest probably?) | 123.4

**Comment by boylett** [comment]
Fixed by [2024-03-26a](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-03-26)
