### ISSUE TITLE
[BUG] Sign up button not working

### ISSUE THREAD

**Issue by Softdoq** [Sheezy-Art/sheezy-hub#520]
**To Reproduce**
Steps to reproduce the behaviour: 

1. Subscribe via Ko-Fi (3$ sub) 
2. Receive code through email
3. Enter code
4. Claim subscription
5. Enter information 
6. Scroll down to see sign up button "grayed out"/unable to be interacted with 

**Device**
- Type: Smartphone 
- OS: Android 
- Browser: Google Chrome 122.0.6261.119

**Comment by xnyoom** [comment]
Could you tell us the exact version of Android and Google Chrome you're using?

Check android version: https://support.google.com/android/answer/7680439?hl=en#:~:text=Check%20which%20Android%20version%20you,Open%20your%20device's%20Settings%20app.&text=Android%20version.,%22%20and%20%22Build%20number.%22

Check chrome version: https://help.illinoisstate.edu/technology/support-topics/device-support/software/web-browsers/what-version-of-chrome-do-i-have#:~:text=Determining%20Chrome%20version%20on%20iOS%20and%20Android&text=Open%20the%20Chrome%20App.,top%20(See%20Figure%203).

**Comment by xnyoom** [comment]
Thanks! We're going to look into this further, but in the meantime, try using another browser such as Firefox: https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by xnyoom** [comment]
(And do let me know here if Firefox works!)

**Comment by boylett** [comment]
A few things to note as well – your email address and username must be valid and your password strength must be 60% or higher. I have just tested this on the same version of Google Chrome and it's working on my end - so may well be a validation issue.

Also: Do you see the ReCaptcha logo on the page, or is it missing/red text?

**Comment by Softdoq** [comment]
My info is valid as I've tried it with a few different emails and I'm still encountering the same issue 

I do see the logo its in the bottom corner

**Comment by xnyoom** [comment]
If you installed any browser extensions on Chrome, try disabling them and then closing and reopening the browser.

If that doesn't work, try Firefox to access Sheezy in the meantime, just so you aren't completely locked out of the site for now.

**Comment by xnyoom** [comment]
Staff Ref: https://discord.com/channels/1172529353834364979/1215676832251256902/1220043443024302181
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/eff202f4-91bd-4bac-ae43-2732f9e13b75)

Keeping this open since the root problem isn't solved, but the issue creator is now good to go so this is less urgent.

**Comment by boylett** [comment]
Validation is now handled server-side, so this should no longer be an issue
