### ISSUE TITLE
[BUG] Uploading a GIF then replacing it with a PNG does not change the artwork type

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#521]
Staff Ref: https://discord.com/channels/1172529353834364979/1215676333284393040/1220102921224458290

End result is PNG artworks end up having a GIF indicator on their thumbnail resulting in confusion. Actual functionality is not impacted.

This may also affect other combinations, e.g. image to flash, image to video, etc. Haven't checked. Need to write reproduction steps/video.

**Developer Solution**
When a file is replaced, always re-run the checks for setting the artwork type based on file.

**Comment by boylett** [comment]
Compromise: Attempting to upload a non-animated image to a GIF-type artwork now simply rejects the file upload. I feel like this solution offers more functional consistency and falls more in line with UX expectations.
