### ISSUE TITLE
[BUG] Profile link styling doesn't apply in journals

### ISSUE THREAD

**Issue by lumiscosity** [Sheezy-Art/sheezy-hub#522]
**Describe the Issue**
Despite sharing a theme with the account posting them, journals ignore the link colour settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a journal.
2. Change your link colour.
3. Notice how it isn't applied in the journal.

**Expected Behaviour**
Links are properly coloured in journals.

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/c40e0c35-defc-44ce-bd86-dbe15bc689a0)

![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26834471/fcb15244-a25d-48d3-8382-63cb0730a566)

**Device**
- Type: PC
- OS: Windows
- Browser: Firefox
- Version: 124.0

**Comment by boylett** [comment]
Fixed by [#2024-03-20b](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-03-20)
