### ISSUE TITLE
[BUG] 405 error when trying to view a journal made by a persona with a content warning page.

### ISSUE THREAD

**Issue by Proxybat** [Sheezy-Art/sheezy-hub#525]
**Describe the Issue**
When trying to view a journal posted by a persona, that has tags in your content warnings settings. It displays a 405 error when trying to view the journal. I've checked and it only seems to occur if the tags the persona has are in your content warnings.

**Error message:**
```
405 Method Not Allowed

Error: You made a POST request to "/lambda20xx/persona/betas_sketchbook/journal/occharacter-diversity-meme" but did not provide an `action` for route "routes/_frontend/$slug/_profile/persona/$persona/journal/$journal/_layout", so there is no way to handle the request.
```

**To Reproduce**
1. Make sure these tags are in your sensitive topics section of the content warning settings. `selfharm sensitivetopics trauma`
2. Go to this [url](https://sheezy.art/lambda20xx/persona/betas_sketchbook/journal/occharacter-diversity-meme)
3. Click the continue button on the content warning page.
4. See 405 error.

**Expected Behaviour**
It should load the journal page when continue button is pressed, and not display a 405 error.

**Device**
- Type: PC
- OS: Windows 11
- Browser: Firefox 64bit
- Version: 124.0.1

**Comment by xnyoom** [comment]
Reproduced.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/162844400/3beaa1d0-64db-47aa-ac42-e1260bf01758)
