### ISSUE TITLE
[BUG] Profile tabs

### ISSUE THREAD

**Issue by bunhakes** [Sheezy-Art/sheezy-hub#527]
everytime i drag a tab of code on my profile, it crashes. every. single. time.

**Comment by punkalope** [comment]
Hiya! Can you elaborate on this a little bit more please? Browser, OS, and perhaps even a screen recording if possible so we can help figure out why this is happening? Is it crashing the whole browser or just the tab? Thanks ♥

**Comment by boylett** [comment]
Closing this issue for now as we have not heard anything from you in a little while.
