### ISSUE TITLE
[BUG] Force unfollow not working

### ISSUE THREAD

**Issue by cynocardia** [Sheezy-Art/sheezy-hub#529]
**Describe the Issue**
I changed my filter to mature and forced unfollow for 2 users, but I am still showing up in at least one of their feeds. I apologize, my brain does not work, I don't know how to talk about this normally, but I believe the other person will also be submitting, I hope. I really don't think I can do this the way that is asked for.

They are still unable to view my profile, but my art is still showing up in their feed, even after blocking. They also said that "for some reason clicking on the artwork image brought me back home but your name just showed the usual blocked stuff".

**To Reproduce**
Steps to reproduce the behaviour:

What I did:

1. Followed the person back.
2. Forced unfollow.

This was before force unfollow was available on follow back.

What they did:

1. Went to feed.
2. I am still showing up in it.
4. I blocked them because I thought that would work. It did not.

**Expected Behaviour**
My art would no longer show up in their feed. I am unsure if it means they are still following me, in fact. And blocking didn't even work, which is concerning, I think.

**Screenshots**
From the other person:

![Screenshot_20240329_074602_Chrome](https://github.com/Sheezy-Art/sheezy-hub/assets/165389497/081503c6-52a9-4677-8de2-58d8d7455b16)
![Screenshot_20240329_074609_Chrome](https://github.com/Sheezy-Art/sheezy-hub/assets/165389497/1f09eae6-fdaf-44a0-bd66-db5b4e5ad2ff)

https://github.com/Sheezy-Art/sheezy-hub/assets/165389497/e5cb27e2-b947-46d6-a2ea-92d350748d39

I hope that works.

**Device**
- Type: I am on a smartphone.
- OS: iOS
- Browser: Safari
- Version: 17.3.1

**Comment by starflayers** [comment]
hihi, im the other user mentioned! the screenshots + video are mine and are taken on my (android) samsung galaxy a23 with google chrome 

i wanted to add that it seems that the bug is fixed? or its no longer happening, as i just checked on web and mobile (firefox web and chrome mobile) and cynoc's work no longer appears on my feed

im not sure if this was a cache issue/the site not processing the block as fast as expected, but i could still see their work despite being forced to unfollow

(i figured id make a comment instead of making a second report so it wouldnt flood the github)

**Comment by cynocardia** [comment]
yeah i forced the unfollow like... more than a week ago, i should not have still been showing up, i think. blocking seems to work, then, but i think i worry force unfollow may not be

**Comment by boylett** [comment]
Feeds are cached for 1 hour – if you click the 'Refresh Feed' button at the top of the feed it should reflect changes like this immediately. Please try that and let me know if you are still having this problem!

**Comment by boylett** [comment]
Closing this for now as we haven't had a response from you. If you still experience this issue please let us know!
