### ISSUE TITLE
[BUG] Icons/Button Images are Broken

### ISSUE THREAD

**Issue by KeenBTF** [Sheezy-Art/sheezy-hub#535]
**Describe the Issue**
When I log on to the site, the icons may show for 2-3 seconds, but then they break, showing the error in the screenshots. Nothing helps that I have tried. It appears that the image is replaced with the name of the image, but it only shows 1 letter, or part of two letters.

Steps I have taken to correct the issue:
Making sure my browser is UTD
Fully closing/restarting the browser
Closing/reopening the page/tab
Refreshing the tab
Clearing cache/image files

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the site
2. See error

**Expected Behaviour**
Icons/Buttons should be visible and able to be determined what their function is

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26097717/b147974c-3e39-400f-9ec9-94f83b7cb383)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/26097717/0031eb19-c6ac-41c0-98fc-8369da770d85)

**Device**
- Type: Laptop
- OS: Windows 11
- Browser: Google Chrome
- Version: Version of what? Everything I am using is the latest, non-beta version available

**Comment by xnyoom** [comment]
Browser extensions are a possible cause of this. 

See if this fixes it:
1. At the top right of Chrome, select the 3 dots -> **Extensions** -> **Manage Extensions**
2. Turn off all extensions one-by-one
3. Close and reopen Chrome
3. Visit the site and check if the icons work

Then we can go from there and see which extension specifically is causing this.

**Comment by xnyoom** [comment]
As for an ETA - We are hoping to fix this within the next month or two, as we are changing the way that icons are loaded to be more reliable.

Other people have reported similar problems to you, but reloading the page would usually fix it immediately. So, it's strange that it's not helping here.

**Comment by KeenBTF** [comment]
Ah you are right. Sadly, my extension, "Change Webpage Fonts" somehow interferes with the images for some reason. Its purpose is to alter the font to be more easily read for me, so I don't know why it would mess with images.

**Comment by xnyoom** [comment]
Discussed further on Discord. Fixed by disabling the extension for sheezy.art. 

Closing this now since it was an extension specific issue and will be fixed with the move to inline SVG icons in the future.

[Discord Reference](https://discord.com/channels/1143702362091966654/1191539111987777547/1226701058282356806)

[Change Webpage Fonts extension](https://chromewebstore.google.com/detail/change-webpage-fonts/afelmehoohjbjfpjbadonkcondbilglp)
