### ISSUE TITLE
[BUG] iframes (youtube embeds, etc.) no longer work in news posts

### ISSUE THREAD

**Issue by xnyoom** [Sheezy-Art/sheezy-hub#542]
Related: https://github.com/Sheezy-Art/sheezy-hub/issues/537
Staff Ref: https://canary.discord.com/channels/1172529353834364979/1215676832251256902/1229902949279465604

**Comment by boylett** [comment]
Fixed by [#2024-04-17](https://github.com/Sheezy-Art/sheezy-hub/releases/tag/2024-04-17)
