### ISSUE TITLE
[BUG] Sheezy email = massive eyestrain

### ISSUE THREAD

**Issue by KeenBTF** [Sheezy-Art/sheezy-hub#551]
**Describe the Issue**
I got an email from Sheezy about my subscription, but it is incredibly difficult to read. Needs an eyestrain tag lol

**To Reproduce**
Get an automated email from Sheezy

**Expected Behaviour**
An email that is contrasted properly and is accessible and easy to read

**Screenshots**
![Screenshot_20240503_062119_Gmail](https://github.com/Sheezy-Art/sheezy-hub/assets/26097717/7a6ca194-01b7-45f8-9489-e8f9086a695b)

**Device**
- Type: Smartphone
- OS: Android
- Browser: email app
- Version: version of what?

**Comment by boylett** [comment]
Hey there!

Would you mind being a little more specific in regards to the device/software you're experiencing this on?

Is it the latest version of Android, or an older version?
Which email app are you using - is it the built-in one, or Gmail, or something else?
Additionally it looks like you have Dark Mode enabled, is that correct?

**Comment by KeenBTF** [comment]
Any device I access the email from has the same issue. It is an email, sent to my Gmail address, when the subscription renews.

Screenshots are from my laptop and my Android. One has dark mode, the other doesn't. 

The formatting of the email was not done by my phone, but by whoever set up the automatic emails from Sheezy. Making the text darker is all that would be required, it seems.

**Comment by boylett** [comment]
This should now be fixed.
