### ISSUE TITLE
[BUG] Footer links don't link to each other

### ISSUE THREAD

**Issue by Stormeko** [Sheezy-Art/sheezy-hub#56]
**Describe the Bug**
Going to a footer link like FAQ and clicking on a link to a different footer link (Like the TOS) sends you to an error page

**To Reproduce**
1. Go to the FAQ or Rules
2. Click on one of the links that should send you to a different footer link (Rules, Terms, Ratings, ect)
3. Get 404

**Expected Behaviour**
The links should work properly

**Screenshots**

**Device**
- Type: Laptop
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Comment by boylett** [comment]
This is now fixed
