### ISSUE TITLE
[BUG] New artworks feed on front page refreshes only after persona switch

### ISSUE THREAD

**Issue by theoneandonlyleggy** [Sheezy-Art/sheezy-hub#563]
**Describe the Issue**
After opening again or reloading/going to front page under main profile, "New this month" feed doesn't update. However it refreshes after switching to persona profile. After going back to main profile feed is updated to the state seen under persona.
Spotted in android Firefox, reproduced in desktop Firefox as well.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to font page
2. In a time period (30 min is enough) refresh front page, or visit other pages and get back to front page, - the feed isn't getting updated
3. Switch to persona profile - the feed gets updated

**Expected Behaviour**
Feed updating properly regardless of active profile.

**Device**
- Type: smartphone / laptop
- OS: Android 11 / Windows 10 Home 64-bit 22H2
- Browser: vanilla Firefox for Android and Windows
- Version: 126.0.1 / 127.0

**Comment by theoneandonlyleggy** [comment]
Addendum: while I was writing this ticket my front page tab stayed opened under persona, same issue - not updated on page refresh / updates when switching back to main profile.

**Comment by boylett** [comment]
The homepage feed has an intentional 1 hour cache for whichever user/persona is currently viewing it.
