### ISSUE TITLE
[BUG] Infinite Subscription

### ISSUE THREAD

**Issue by betalambda** [Sheezy-Art/sheezy-hub#564]
**Describe the Issue**
Subscriptions do not expire and instead remain active until the end of time (or when the site shuts down, whichever comes first)

**To Reproduce**
Steps to reproduce the behaviour:
- Buy a subscription (or earn one)
- Wait for it to expire
- Wait for it to expire
- Wait for it to expire
- Wait for it to expire
- Wait for it to expire

**Expected Behaviour**
Subscription expires after a month. ..yeah

**More Info**
https://sheezy.art/adrimmd/journal/subscription-bug

**Screenshots**
![IMG_2545](https://github.com/Sheezy-Art/sheezy-hub/assets/118129938/717bb6f1-a525-4829-9d12-8e903bbb2adb)

**Device**
(Site specific issue)

**Comment by boylett** [comment]
This is now fixed. Thanks for bringing it to our attention!
