### ISSUE TITLE
[BUG] "See More" Button on the home page shows nothing 

### ISSUE THREAD

**Issue by DaxDoodles** [Sheezy-Art/sheezy-hub#58]
**Describe the Bug**
When I click the see more button on the homepage it does nothing but load an empty page with a tiny text that just reads "feed"
in the corner
**To Reproduce**
1. Go to 'Home page'
2. Click on 'See more'

**Expected Behaviour**
Id assume id see more from people I follow or new posts 

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/efe5c869-1803-4ede-a404-daee42736dd1)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153090008/d057a6f2-7b87-4524-87d1-1777b3cbe8fa)

**Device**
- Type: PC
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: idk

**Comment by boylett** [comment]
The feed page isn't built yet 😅
