### ISSUE TITLE
[BUG] Deleting Personas does not work

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#62]
**Describe the Bug**
Deleting an existing persona, yields in an error message after filling in the password. The error asks for you to refresh the page, refreshing the page + inputting the password again does not help.

**To Reproduce**
1. Go to 'Account Settings'
2. Click on 'Manage Personas'
3. Click "Manage" button on selected Persona
4. Click "Delete This Persona"
5. Click Delete (@ PERSONAUSERNAME)
6. Verify with Password
7. Error asking you to refresh

**Expected Behaviour**
Removal of beloved persona

**Screenshots**
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/153323699/e0618eca-76a5-41a3-96f3-23815467f262)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: FireFox
 - Version: Latest

**Comment by boylett** [comment]
Fixed! :)

**Comment by boylett** [comment]
Not Fixed! :(
