### ISSUE TITLE
[BUG] Can't reupload an image when uploading art ?

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#71]
**Describe the Bug**
This might not actually be a bug, if it's intended let me know!
When uploading an image, you can't change it if you uploaded the wrong image, forcing you to start the process all over again.

**To Reproduce**
1. Go to the art upload page.
2. Upload the art I didn't want!!
3. Can't change... Have to delete the draft and restart.

**Expected Behaviour**
If I upload the wrong image, I can change it before continuing the upload process. 

**Screenshots**
Blurred for suggestive image.
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/1de050c1-1571-44c8-a044-5c470c6be0c6)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
This is intended behaviour :)
