### ISSUE TITLE
[BUG] Profile background size changing between saved profile and active editing.

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#77]
**Describe the Bug**
Related to https://github.com/Sheezy-Art/sheezy-hub/issues/76 !
When I go to my profile, the background size doesn't seem to match what I see when I edit it. It may be because of https://github.com/Sheezy-Art/sheezy-hub/issues/76 but I am unsure.
I thought that this was because of my featured artwork being huge for a bit, but when I changed my background again and removed the featured artwork it was still happening and I swear it wasn't doing that before, haha.

**To Reproduce**
1. Go to profile.
2. Edit profile customization.
3. Watch as the background size changes?

**Expected Behaviour**
The background on my profile should stay at least mostly the same when editing.

**Screenshots**
With the giant 'featured art' block:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/b79cb672-70fd-46c2-87f7-ad903412cf56)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/b4011bcc-ec6c-4d65-9290-91b064eee780)
Without the giant 'featured art' block:
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a1aa58da-9358-4c47-8cd3-d975f4f8083a)
![image](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/0cee0111-7f3e-4eee-a321-5076fe6c27bc)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
Please see my comment on #76 :)
