### ISSUE TITLE
[BUG] Comment markdown not working

### ISSUE THREAD

**Issue by punkalope** [Sheezy-Art/sheezy-hub#83]
**Describe the Bug**
When formatting a comment with markdown, it doesn't seem to work when posted. Hyperlinks _technically_ work if you hover over and click on them, but lack any visual indication that they're a link once the comment is posted.

**To Reproduce**
1. Find somewhere to comment.
2. Write comment with excessive formatting.
3. Preview to make sure it looks right.
4. Post.
5. Only bold, italics, and links (half) seem to stay formatted.

**Expected Behaviour**
My comment formatting should match the preview.

**Screenshots**
On a profile:
![firefox_onnS4hnvrk](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/9a541afd-d3ad-4450-a682-fd0592d15701)
![firefox_cVvSOP956o](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/a395421e-ada8-46e9-86a5-4158ee70fadf)
On art:
![firefox_RrPxOOrnmD](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/86997c6b-e9ae-42f6-a839-7152a426e421)
![firefox_sg60vaUY2F](https://github.com/Sheezy-Art/sheezy-hub/assets/88009266/236f1c06-e7f1-4164-bd36-3bc0d0bb5b82)

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0.1

**Comment by boylett** [comment]
This should be fixed now. Please let me know if you're still having this issue!
