### ISSUE TITLE
[BUG] Handoff feature won't remove item from personal mod queue

### ISSUE THREAD

**Issue by waningw** [Sheezy-Art/sheezy-hub#99]
**Describe the Bug**
When selecting, or attempting to hand-off an item on it's page, it will not remove the item from your queue.

**To Reproduce**
1. Go to mod queue
2. Click on an item in the queue
3. Click the 'hand-off' button 
4. Page reloads, confirmation message that the item has been removed, but the item is still there.

**Expected Behaviour**
For said item to be removed from your mod queue

**Screenshots**
Nuh uh sir, no exposing the queue on the github smh.

**Device**
- Type: Desktop PC
 - OS: Windows 10
 - Browser: FireFox
 - Version: Latest

**Comment by boylett** [comment]
I'm not able to replicate this. Could you send a screen recording in the Discord pls? :')
